<?php
//This is generated by Nigade Software Technologies (opc) Private Limited 12/12/2020 10:32:48 am for PHP
require_once("../swappbase/formbase.php");
class issueitemdetail extends swappform
{
    Public $transactionnumber;
    Public $serialnumber;
    Public $itemcode;
    Public $itemcodetextcombo;
    Public $quantity;
    Public $jobcode;
    Public $jobcodetextcombo;

    Public $balance;
    Public $mainstore;
    Public $substore;
    Public $unit;
    public function __construct(&$connection)
    {
     		 parent::__construct($connection);
         $this->transactionnumber='';
         $this->transactionnumbertextcombo='';
         $this->serialnumber='';
         $this->serialnumbertextcombo='';
         $this->itemcode='';
         $this->itemcodetextcombo='';
         $this->quantity='';
         $this->quantitytextcombo='';
         $this->jobcode='';
         $this->jobcodetextcombo='';
	   }
    public function entryvalidation()
    {
    		$this->start_validation();
        $this->checkrequired($this->itemcode,'Item Code ','आयटम कोड');
        $this->checkrequired($this->quantity,'Quantity ','संख्या');
        //$this->checkrequired($this->jobcode,'Job Code ','जॉब कोड');
        $this->end_validation();
        return $this->invalidid;
	  }
    private function datavalidation()
    {
        $this->start_validation();
    		$this->invalidid=0;
    		$this->invalidmessagetext='Validated';
    		$this->end_validation();
    		return $this->invalidid;
    }
    public function insert()
    {
        $this->dataoperationmode = operationmode::Insert;
	    if ($this->entryvalidation() <> 0)
        {
            return 0;
            exit;
        }
        elseif ($this->datavalidation() <> 0)
        {
            return 0;
            exit;
        }
	    if ($this->transactionnumber == '')
        {
            $query = "select nvl(max(transactionnumber),0)+1 as transactionnumber from issueitemdetail";
            $result = oci_parse($this->connection, $query);
            $r = oci_execute($result);
            $row = oci_fetch_array($result,OCI_ASSOC+OCI_RETURN_NULLS);
            $this->transactionnumber = $row["TRANSACTIONNUMBER"];
        }
	    if ($this->serialnumber == '')
        {
            $query = "select nvl(max(serialnumber),0)+1 as serialnumber from issueitemdetail";
            $result = oci_parse($this->connection, $query);
            $r = oci_execute($result);
            $row = oci_fetch_array($result,OCI_ASSOC+OCI_RETURN_NULLS);
            $this->serialnumber = $row["SERIALNUMBER"];
        }
        $query = "
            insert into issueitemdetail(
            transactionnumber
            ,serialnumber
            ,itemcode
            ,quantity
            ,jobcode
	        )
	        values (
            ".$this->invl($this->transactionnumber,true)."
            ,".$this->invl($this->serialnumber,true)."
            ,".$this->invl($this->itemcode,true,true)."
            ,".$this->invl($this->quantity,true)."
            ,".$this->invl($this->jobcode,true,true)."
            )";
        $result = oci_parse($this->connection, $query);
        if (oci_execute($result,OCI_NO_AUTO_COMMIT))
        {
            return 1;
            exit;
        }
        else
        {
            return 0;
            exit;
        }
    }
    public function display()
	  {
		    $this->dataoperationmode = operationmode::Select;
		    $cond='';
		    if ($this->transactionnumber!='' and $this->transactionnumber!=0)
		    {
			      if ($cond=='')
			      {
				        $cond="t.transactionnumber = ".$this->transactionnumber;
			       }
			       else
			       {
				         $cond=$cond." and t.transactionnumber = ".$this->transactionnumber;
			       }
		    }
		    if ($this->serialnumber!='' and $this->serialnumber!=0)
		    {
			      if ($cond=='')
			      {
				        $cond="t.serialnumber = ".$this->serialnumber;
			       }
			       else
			       {
				         $cond=$cond." and t.serialnumber = ".$this->serialnumber;
			       }
		    }
		    if ($this->itemcode!='' and $this->itemcode!=0)
		    {
			      if ($cond=='')
			      {
				        $cond="t.itemcode = ".$this->itemcode;
			       }
			       else
			       {
				         $cond=$cond." and t.itemcode = ".$this->itemcode;
			       }
		    }
		    if ($this->jobcode!='' and $this->jobcode!=0)
		    {
			      if ($cond=='')
			      {
				        $cond="t.jobcode = ".$this->jobcode;
			       }
			       else
			       {
				         $cond=$cond." and t.jobcode = ".$this->jobcode;
			       }
		    }
        if ($cond!='')
		    {
		        $query = "select t.* from issueitemdetail t where ".$cond." order by transactionnumber,serialnumber";
			      $result = oci_parse($this->connection, $query);
            $r = oci_execute($result);
			      return $result;
		     }
		     else
		     {
		         $query = "select t.* from issueitemdetail t order by transactionnumber,serialnumber";
			       $result = oci_parse($this->connection, $query);
             $r = oci_execute($result);
			       return $result;
		     }
	  }
    public function update()
    {
        $this->dataoperationmode = operationmode::Update;
        if ($this->entryvalidation() <> 0)
        {
            return 0;
            exit;
        }
        elseif ($this->datavalidation() <> 0)
        {
            return 0;
            exit;
        }
        $query = "
        update issueitemdetail set 
        itemcode = ".$this->invl($this->itemcode,true,true)."
        ,quantity = ".$this->invl($this->quantity,true,true)."
        ,jobcode = ".$this->invl($this->jobcode,true,true)."
        where 
        transactionnumber = ".$this->invl($this->transactionnumber,true)."
         and serialnumber = ".$this->invl($this->serialnumber,true)."
        ";
        $result = oci_parse($this->connection, $query);
        if (oci_execute($result,OCI_NO_AUTO_COMMIT))
        {
            return 1;
            exit;
        }
            else
        {
            return 0;
            exit;
        }
    }
    public function delete()
    {
        $this->dataoperationmode = operationmode::Delete;
        if ($this->entryvalidation() <> 0)
        {
            return 0;
            exit;
        }
        elseif ($this->datavalidation() <> 0)
        {
            return 0;
            exit;
        }
        $query = "
        delete from issueitemdetail
        where 
        transactionnumber = ".$this->invl($this->transactionnumber,true)."
         and serialnumber = ".$this->invl($this->serialnumber,true)."
        ";
        $result = oci_parse($this->connection, $query);
        if (oci_execute($result,OCI_NO_AUTO_COMMIT))
        {
             return 1;
             exit;
        }
        else
        {
            return 0;
            exit;
        }
    }
    public function fetch()
    {
        $this->dataoperationmode = operationmode::Select;
        $query = "select 
        h.issuedate
        ,d.transactionnumber
        ,serialnumber
        ,itemcode
        ,quantity
        ,jobcode
        from issueitemdetail d,issueheader h 
        where d.transactionnumber=h.transactionnumber
        and d.transactionnumber = ".$this->invl($this->transactionnumber,true)."
         and d.serialnumber = ".$this->invl($this->serialnumber,true)."
        ";
        $result = oci_parse($this->connection, $query);
        $r = oci_execute($result);
        if ($row = oci_fetch_array($result,OCI_ASSOC+OCI_RETURN_NULLS))
        {
                $this->transactionnumber = $row['TRANSACTIONNUMBER'];
                $this->serialnumber = $row['SERIALNUMBER'];
                $this->itemcode = $row['ITEMCODE'];
                $this->quantity = $row['QUANTITY'];
                $this->jobcode = $row['JOBCODE'];
                $this->itemcodetextcombo = $this->textcomboname($connection=$this->connection,$table='ITEM',$datafield='ITEMCODE',$datafieldvalue=$row['ITEMCODE'],$engfield='ITEMNAMEENG',$unicodefield='ITEMNAMEENG');
                $this->jobcodetextcombo = $this->textcomboname($connection=$this->connection,$table='JOB',$datafield='JOBCODE',$datafieldvalue=$row['JOBCODE'],$engfield='JOBNAMEENG',$unicodefield='JOBNAMEUNI');
                $query0="select ITEMCODE,
                ITEMNAMEENG,substorenameeng,mainstorenameeng,itemstock(p_yearcode => ".$_SESSION['yearperiodcode'].",
                p_itemcode => i.itemcode,
                p_date => '".$row['ISSUEDATE']."') balance,u.unitnameeng
                from ITEM i,substore s,mainstore m,unit u 
                where i.substorecode=s.substorecode 
                and s.mainstorecode=m.mainstorecode
                and i.unitcode=u.unitcode
                and i.itemcode=".$row['ITEMCODE'];
                $result0 = oci_parse($this->connection, $query0);
                $r0 = oci_execute($result0);
                if ($row0 = oci_fetch_array($result0,OCI_ASSOC+OCI_RETURN_NULLS))
                {
                    $this->balance=$row0['BALANCE'];
                    $this->substore=$row0['SUBSTORENAMEENG'];
                    $this->mainstore=$row0['MAINSTORENAMEENG'];
                    $this->unit=$row0['UNITNAMEENG'];
                }
                $this->found=true;
                return true;
        }
        else
        {
        return false;
        }
    }
    public function fetchall()
    {
        $this->dataoperationmode = operationmode::Select;
        $query = "select 
        transactionnumber
        ,serialnumber
        ,d.itemcode
        ,quantity
        ,jobcode
        ,itemnameeng
        ,unitnameeng
        from issueitemdetail d,item i,unit u 
        where d.transactionnumber = ".$this->invl($this->transactionnumber,true)."
         and d.itemcode=i.itemcode
         and i.unitcode=u.unitcode(+)";
        $result = oci_parse($this->connection, $query);
        return $result;
        
    }
}
?>

