<?php
//This is generated by Nigade Software Technologies (opc) Private Limited 12/12/2020 10:11:52 am for PHP
require_once("../swappbase/formbase.php");
class quotationitemdetail extends swappform
{
    Public $transactionnumber;
    Public $serialnumber;
    Public $itemcode;
    Public $itemcodetextcombo;
    Public $quotationrate;
    public function __construct(&$connection)
    {
     		 parent::__construct($connection);
         $this->transactionnumber='';
         $this->transactionnumbertextcombo='';
         $this->serialnumber='';
         $this->serialnumbertextcombo='';
         $this->itemcode='';
         $this->itemcodetextcombo='';
         $this->quotationrate='';
         $this->quotationratetextcombo='';
	   }
    public function entryvalidation()
    {
    		$this->start_validation();
        $this->checkrequired($this->itemcode,'Item Code','आयटम कोड');
        $this->checkrequired($this->quotationrate,'Quotation Rate','कोटेशन रेट');
        $this->end_validation();
        return $this->invalidid;
	  }
    private function datavalidation()
    {
        $this->start_validation();
    		$this->invalidid=0;
    		$this->invalidmessagetext='Validated';
    		$this->end_validation();
    		return $this->invalidid;
    }
    public function insert()
    {
        $this->dataoperationmode = operationmode::Insert;
	    if ($this->entryvalidation() <> 0)
        {
            return 0;
            exit;
        }
        elseif ($this->datavalidation() <> 0)
        {
            return 0;
            exit;
        }
	    if ($this->transactionnumber == '')
        {
            $query = "select nvl(max(transactionnumber),0)+1 as transactionnumber from quotationitemdetail";
            $result = oci_parse($this->connection, $query);
            $r = oci_execute($result);
            $row = oci_fetch_array($result,OCI_ASSOC+OCI_RETURN_NULLS);
            $this->transactionnumber = $row["TRANSACTIONNUMBER"];
        }
	    if ($this->serialnumber == '')
        {
            $query = "select nvl(max(serialnumber),0)+1 as serialnumber from quotationitemdetail";
            $result = oci_parse($this->connection, $query);
            $r = oci_execute($result);
            $row = oci_fetch_array($result,OCI_ASSOC+OCI_RETURN_NULLS);
            $this->serialnumber = $row["SERIALNUMBER"];
        }
        $query = "
            insert into quotationitemdetail(
            transactionnumber
            ,serialnumber
            ,itemcode
            ,quotationrate
	        )
	        values (
            ".$this->invl($this->transactionnumber,true)."
            ,".$this->invl($this->serialnumber,true)."
            ,".$this->invl($this->itemcode,true,true)."
            ,".$this->invl($this->quotationrate,true)."
            )";
        $result = oci_parse($this->connection, $query);
        if (oci_execute($result,OCI_NO_AUTO_COMMIT))
        {
            return 1;
            exit;
        }
        else
        {
            return 0;
            exit;
        }
    }
    public function display()
	  {
		    $this->dataoperationmode = operationmode::Select;
		    $cond='';
		    if ($this->itemcode!='' and $this->itemcode!=0)
		    {
			      if ($cond=='')
			      {
				        $cond="t.itemcode = ".$this->itemcode;
			       }
			       else
			       {
				         $cond=$cond." and t.itemcode = ".$this->itemcode;
			       }
		    }
        if ($cond!='')
		    {
		        $query = "select t.* from quotationitemdetail t where ".$cond." order by transactionnumber,serialnumber";
			      $result = oci_parse($this->connection, $query);
            $r = oci_execute($result);
			      return $result;
		     }
		     else
		     {
		         $query = "select t.* from quotationitemdetail t order by transactionnumber,serialnumber";
			       $result = oci_parse($this->connection, $query);
             $r = oci_execute($result);
			       return $result;
		     }
	  }
    public function update()
    {
        $this->dataoperationmode = operationmode::Update;
        if ($this->entryvalidation() <> 0)
        {
            return 0;
            exit;
        }
        elseif ($this->datavalidation() <> 0)
        {
            return 0;
            exit;
        }
        $query = "
        update quotationitemdetail set 
        itemcode = ".$this->invl($this->itemcode,true,true)."
        ,quotationrate = ".$this->invl($this->quotationrate,true,true)."
        where 
        transactionnumber = ".$this->invl($this->transactionnumber,true)."
         and serialnumber = ".$this->invl($this->serialnumber,true)."
        ";
        $result = oci_parse($this->connection, $query);
        if (oci_execute($result,OCI_NO_AUTO_COMMIT))
        {
            return 1;
            exit;
        }
            else
        {
            return 0;
            exit;
        }
    }
    public function delete()
    {
        $this->dataoperationmode = operationmode::Delete;
        if ($this->entryvalidation() <> 0)
        {
            return 0;
            exit;
        }
        elseif ($this->datavalidation() <> 0)
        {
            return 0;
            exit;
        }
        $query = "
        delete from quotationitemdetail
        where 
        transactionnumber = ".$this->invl($this->transactionnumber,true)."
         and serialnumber = ".$this->invl($this->serialnumber,true)."
        ";
        $result = oci_parse($this->connection, $query);
        if (oci_execute($result,OCI_NO_AUTO_COMMIT))
        {
             return 1;
             exit;
        }
        else
        {
            return 0;
            exit;
        }
    }
    public function fetch()
    {
        $this->dataoperationmode = operationmode::Select;
        $query = "select 
        transactionnumber
        ,serialnumber
        ,itemcode
        ,quotationrate
        from quotationitemdetail where 
        transactionnumber = ".$this->invl($this->transactionnumber,true)."
         and serialnumber = ".$this->invl($this->serialnumber,true)."
        ";
        $result = oci_parse($this->connection, $query);
        $r = oci_execute($result);
        if ($row = oci_fetch_array($result,OCI_ASSOC+OCI_RETURN_NULLS))
        {
                $this->transactionnumber = $row['TRANSACTIONNUMBER'];
                $this->serialnumber = $row['SERIALNUMBER'];
                $this->itemcode = $row['ITEMCODE'];
                $this->quotationrate = $row['QUOTATIONRATE'];
                $this->itemcodetextcombo = $this->textcomboname($connection=$this->connection,$table='ITEM',$datafield='ITEMCODE',$datafieldvalue=$row['ITEMCODE'],$engfield='ITEMNAMEENG',$unicodefield='UNITCODE');
                $this->found=true;
                return true;
        }
        else
        {
        return false;
        }
    }
}
?>

<?php
//This is generated by Nigade Software Technologies (opc) Private Limited 12/12/2020 10:11:53 am for PHP
require_once("../swappbase/formbase.php");
class quotationitemdetail extends swappform
{
    Public $transactionnumber;
    Public $serialnumber;
    Public $itemcode;
    Public $itemcodetextcombo;
    Public $quotationrate;
    public function __construct(&$connection)
    {
     		 parent::__construct($connection);
         $this->transactionnumber='';
         $this->transactionnumbertextcombo='';
         $this->serialnumber='';
         $this->serialnumbertextcombo='';
         $this->itemcode='';
         $this->itemcodetextcombo='';
         $this->quotationrate='';
         $this->quotationratetextcombo='';
	   }
    public function entryvalidation()
    {
    		$this->start_validation();
        $this->checkrequired($this->itemcode,'Item Code','आयटम कोड');
        $this->checkrequired($this->quotationrate,'Quotation Rate','कोटेशन रेट');
        $this->end_validation();
        return $this->invalidid;
	  }
    private function datavalidation()
    {
        $this->start_validation();
    		$this->invalidid=0;
    		$this->invalidmessagetext='Validated';
    		$this->end_validation();
    		return $this->invalidid;
    }
    public function insert()
    {
        $this->dataoperationmode = operationmode::Insert;
	    if ($this->entryvalidation() <> 0)
        {
            return 0;
            exit;
        }
        elseif ($this->datavalidation() <> 0)
        {
            return 0;
            exit;
        }
	    if ($this->transactionnumber == '')
        {
            $query = "select nvl(max(transactionnumber),0)+1 as transactionnumber from quotationitemdetail";
            $result = oci_parse($this->connection, $query);
            $r = oci_execute($result);
            $row = oci_fetch_array($result,OCI_ASSOC+OCI_RETURN_NULLS);
            $this->transactionnumber = $row["TRANSACTIONNUMBER"];
        }
	    if ($this->serialnumber == '')
        {
            $query = "select nvl(max(serialnumber),0)+1 as serialnumber from quotationitemdetail";
            $result = oci_parse($this->connection, $query);
            $r = oci_execute($result);
            $row = oci_fetch_array($result,OCI_ASSOC+OCI_RETURN_NULLS);
            $this->serialnumber = $row["SERIALNUMBER"];
        }
        $query = "
            insert into quotationitemdetail(
            transactionnumber
            ,serialnumber
            ,itemcode
            ,quotationrate
	        )
	        values (
            ".$this->invl($this->transactionnumber,true)."
            ,".$this->invl($this->serialnumber,true)."
            ,".$this->invl($this->itemcode,true,true)."
            ,".$this->invl($this->quotationrate,true)."
            )";
        $result = oci_parse($this->connection, $query);
        if (oci_execute($result,OCI_NO_AUTO_COMMIT))
        {
            return 1;
            exit;
        }
        else
        {
            return 0;
            exit;
        }
    }
    public function display()
	  {
		    $this->dataoperationmode = operationmode::Select;
		    $cond='';
		    if ($this->itemcode!='' and $this->itemcode!=0)
		    {
			      if ($cond=='')
			      {
				        $cond="t.itemcode = ".$this->itemcode;
			       }
			       else
			       {
				         $cond=$cond." and t.itemcode = ".$this->itemcode;
			       }
		    }
        if ($cond!='')
		    {
		        $query = "select t.* from quotationitemdetail t where ".$cond." order by transactionnumber,serialnumber";
			      $result = oci_parse($this->connection, $query);
            $r = oci_execute($result);
			      return $result;
		     }
		     else
		     {
		         $query = "select t.* from quotationitemdetail t order by transactionnumber,serialnumber";
			       $result = oci_parse($this->connection, $query);
             $r = oci_execute($result);
			       return $result;
		     }
	  }
    public function update()
    {
        $this->dataoperationmode = operationmode::Update;
        if ($this->entryvalidation() <> 0)
        {
            return 0;
            exit;
        }
        elseif ($this->datavalidation() <> 0)
        {
            return 0;
            exit;
        }
        $query = "
        update quotationitemdetail set 
        itemcode = ".$this->invl($this->itemcode,true,true)."
        ,quotationrate = ".$this->invl($this->quotationrate,true,true)."
        where 
        transactionnumber = ".$this->invl($this->transactionnumber,true)."
         and serialnumber = ".$this->invl($this->serialnumber,true)."
        ";
        $result = oci_parse($this->connection, $query);
        if (oci_execute($result,OCI_NO_AUTO_COMMIT))
        {
            return 1;
            exit;
        }
            else
        {
            return 0;
            exit;
        }
    }
    public function delete()
    {
        $this->dataoperationmode = operationmode::Delete;
        if ($this->entryvalidation() <> 0)
        {
            return 0;
            exit;
        }
        elseif ($this->datavalidation() <> 0)
        {
            return 0;
            exit;
        }
        $query = "
        delete from quotationitemdetail
        where 
        transactionnumber = ".$this->invl($this->transactionnumber,true)."
         and serialnumber = ".$this->invl($this->serialnumber,true)."
        ";
        $result = oci_parse($this->connection, $query);
        if (oci_execute($result,OCI_NO_AUTO_COMMIT))
        {
             return 1;
             exit;
        }
        else
        {
            return 0;
            exit;
        }
    }
    public function fetch()
    {
        $this->dataoperationmode = operationmode::Select;
        $query = "select 
        transactionnumber
        ,serialnumber
        ,itemcode
        ,quotationrate
        from quotationitemdetail where 
        transactionnumber = ".$this->invl($this->transactionnumber,true)."
         and serialnumber = ".$this->invl($this->serialnumber,true)."
        ";
        $result = oci_parse($this->connection, $query);
        $r = oci_execute($result);
        if ($row = oci_fetch_array($result,OCI_ASSOC+OCI_RETURN_NULLS))
        {
                $this->transactionnumber = $row['TRANSACTIONNUMBER'];
                $this->serialnumber = $row['SERIALNUMBER'];
                $this->itemcode = $row['ITEMCODE'];
                $this->quotationrate = $row['QUOTATIONRATE'];
                $this->itemcodetextcombo = $this->textcomboname($connection=$this->connection,$table='ITEM',$datafield='ITEMCODE',$datafieldvalue=$row['ITEMCODE'],$engfield='ITEMNAMEENG',$unicodefield='UNITCODE');
                $this->found=true;
                return true;
        }
        else
        {
        return false;
        }
    }
}
?>

