<?php
    //This is generated by Nigade Software Technologies (opc) Private Limited on 01/02/2020 07:29:54 pm for PHP
    require("../info/phpgetloginview.php");
    include("../info/ncryptdcrypt.php");
    require("../info/routine.php");
    include("../ip_model/deduction_db_oracle.php");
    $connection=swapp_connection();
    $deduction1 = new deduction($connection);
    $deduction1->deductioncode = $_POST["deductioncode"];
    $deduction1->deductionnameeng = $_POST["deductionnameeng"];
    $deduction1->deductionnameuni = $_POST["deductionnameuni"];
    $deduction1->deductioncategorycode = $_POST["deductioncategorycode"];
    $deduction1->dedprioritycategorycode = $_POST["dedprioritycategorycode"];
    $deduction1->issubdeduction = $_POST["issubdeduction"];
    $deduction1->subdedprioritycategorycode = $_POST["subdedprioritycategorycode"];
    $deduction1->issubseasonyear = $_POST["issubseasonyear"];
    $deduction1->subseasonprioritycode = $_POST["subseasonprioritycode"];
    $deduction1->isinterestapplicable = $_POST["isinterestapplicable"];
    $deduction1->interestledgercode = $_POST["interestledgercode"];
    $deduction1->ledgercode = $_POST["ledgercode"];
    $deduction1->payeecategorycode = $_POST["payeecategorycode"];
    $deduction1->institutioncategorycode = $_POST["institutioncategorycode"];
    $deduction1->bankcategorycode = $_POST["bankcategorycode"];
    $deduction1->balancesourcecategorycode = $_POST["balancesourcecategorycode"];
    $deduction1->interestdeductioncode = $_POST["interestdeductioncode"];
    $flag_de = fnDecrypt($_GET['flag']);
if ((($_POST['btn']=='Add' or ($_POST['btn']=='Change')) and $_SESSION['errors']['error']!='submitted'))
    {
    $ret = $deduction1->entryvalidation();
    }
    else
    {
      $ret=0;
    }
    if ($ret!=0)
    {
      $_SESSION['errors']['error'] = $deduction1->invalidmessagetext;
      //This is for ajax requests:
      if(!empty($_SERVER['HTTP_X_REQUESTED_WITH']) &&  strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) == 'xmlhttprequest') 
      {
        echo json_encode($_SESSION['errors']);
        exit;
      }
      //This is when Javascript is turned off:
      echo '<ul>';
      foreach($_SESSION['errors'] as $key => $value)
      {
        echo '<li>' . $value . '</li>';
      }
      echo '</ul>';
      exit;
    }
    elseif ($_SESSION['errors']['error']!='submitted')
    {
      echo json_encode(true);
      unset($_SESSION['errors']['error']);
      $_SESSION['errors']['error'] ='submitted';
      $_SESSION['button'] =$_POST['btn'];
      exit;
    }
  unset($_SESSION['errors']['error']);  
  $payeecategorycode_en = fnEncrypt($deduction1->payeecategorycode);
  switch ($_SESSION['button'])
  {
    case 'Add':
      $ret = $deduction1->insert();
      if ($ret==1)
      {
        oci_commit($connection);
        echo '<span class="w3-container" style="background-color:#0a0;color:#ff8;text-align:left;">deduction is added successfully</span></br>';
        echo '<a href="../ip_view/deduction.php?payeecategorycode='.$payeecategorycode_en.'">New deduction</a></br>';
      }
      else
      {
        oci_rollback($connection);
        echo '<span style="background-color:#f44;color:#ff8;text-align:left;">'.$deduction1->Get_invalidmessagetext().'</span></br>';
        echo '<button onclick="history.go(-1);">Back </button>';
      }
      break;
    case 'Change':
      $deduction1->deductioncode = $_POST["deductioncode"];
      $ret = $deduction1->update();
      if ($ret==1)
      {
        oci_commit($connection);
        $flag_en = fnEncrypt('Query');
        echo '<span class="w3-container" style="background-color:#0a0;color:#ff8;text-align:left;">deduction is Updated successfully</span></br>';  
        echo '<a href="../ip_view/deduction.php?payeecategorycode='.$payeecategorycode_en.'&flag='.$flag_en.'">Find deduction</a></br>';
      }
      else
      {
        oci_rollback($connection);
        echo '<span style="background-color:#f44;color:#ff8;text-align:left;">'.$deduction1->Get_invalidmessagetext().'</span></br>';
        echo '<button onclick="history.go(-1);">Back </button>';
			}
			break;
		case 'Display':
      $deduction1->deductioncode = $_POST["deductioncode"];
      include("../mis/list.php");
      echo '<nav "w3-container">';
      echo '    <ul class="navbar">';
      echo '    <li><a class="navbar" href="../mis/entitymenu.php">Entity Menu</a><br/>';
      $flag_en = fnEncrypt('Query');
      echo '    <li><a class="navbar" href="../ip_view/deduction.php">New deduction</a>';
      echo '    <li><a class="navbar" href="../ip_view/deduction.php?flag='.$flag_en.'">Find deduction</a>';
      echo '<li><a  class="navbar" href="../../../../../sqlproc/logout.php">Log Out</a><br/>';
      echo '    </ul>';
      echo '  </nav>';
      echo '<section>';
      echo '<table border="0" >';
      echo '<tr>';
      echo '<td><label for="" class="thick">List of deduction</label></td>';
      echo '</tr>';
			$result1 = $deduction1->display();
			if ($deduction1->Get_invalidid()==0)
			{
        $flag_en = fnEncrypt('Display');
				while ($row1 = oci_fetch_array($result1,OCI_ASSOC+OCI_RETURN_NULLS))
				{
					if ($_SESSION['lng']=='English')
					{
            echo '<tr>';
						echo '<td><a href="../ip_view/deduction.php?payeecategorycode='.$payeecategorycode_en.'&deductioncode='.fnEncrypt($row1['DEDUCTIONCODE']).'&flag='.$flag_en.'">'.$row1['DEDUCTIONCODE'].' '.$row1['DEDUCTIONNAMEENG'].'</td>';
            echo '</tr>';
					}
					else
					{
            echo '<tr>';
						echo '<td><a href="../ip_view/deduction.php?payeecategorycode='.$payeecategorycode_en.'&deductioncode='.fnEncrypt($row1['DEDUCTIONCODE']).'&flag='.$flag_en.'">'.$row1['DEDUCTIONCODE'].' '.$row1['DEDUCTIONNAMEUNI'].'</td>';
            echo '</tr>';
					}
				}	
			}
			else
			{
				echo '<span style="background-color:#f44;color:#ff8;text-align:left;">'.$deduction1->Get_invalidmessagetext().'</span></br>';
        echo '<button onclick="history.go(-1);">Back </button>';
			}
			break;
		case 'Delete':
      $deduction1->deductioncode = $_POST["deductioncode"];
			$ret = $deduction1->delete();
			if ($ret == 1)
			{
				oci_commit($connection);
        $flag_en = fnEncrypt('Query');
				echo '<span class="w3-container" style="background-color:#0a0;color:#ff8;text-align:left;">deduction is Deleted Successfully</span></br>';
				echo '<a href="../ip_view/deduction.php?payeecategorycode='.$payeecategorycode_en.'&flag='.$flag_en.'">Find deduction</a></br>';
			}
			else
			{
				oci_rollback($connection);
				echo '<span style="background-color:#f44;color:#ff8;text-align:left;">'.$deduction1->Get_invalidmessagetext().'</span></br>';
				echo '<a href="../ip_view/deduction.php">Find deduction</a></br>';
        echo '<button onclick="history.go(-1);">Back </button>';
			}
			break;
		default:
			echo 'Communication Error';
      echo '<button onclick="history.go(-1);">Back </button>';
			break;
	}

