<?php
    //This is generated by Swapp Software Application on 28/05/2019 07:19:54 PM for PHP
    require("../info/phpgetloginview.php");
    include("../info/ncryptdcrypt.php");
    require("../info/routine.php");
    include("../ip_model/plantationheader_db_oracle.php");
    $connection=swapp_connection();
    $plantationheader1 = new plantationheader($connection);
    $plantationheader1->seasoncode = $_POST["seasoncode"];
    $plantationheader1->plotnumber = $_POST["plotnumber"];
    $plantationheader1->registrationcategorycode = $_POST["registrationcategorycode"];
    $plantationheader1->plotregistrationdate = $_POST["plotregistrationdate"];
    $plantationheader1->farmercode = $_POST["farmercode"];
    $plantationheader1->villagecode = $_POST["villagecode"];
    $plantationheader1->subvillagecode = $_POST["subvillagecode"];
    //$plantationheader1->refformnumber = $_POST["refformnumber"];
    $plantationheader1->gutnumber = $_POST["gutnumber"];
    $plantationheader1->varietycode = $_POST["varietycode"];
    $plantationheader1->plantationhangamcode = $_POST["plantationhangamcode"];
    $plantationheader1->plantationdate = $_POST["plantationdate"];
    $plantationheader1->area = $_POST["area"];
    $plantationheader1->irrigationsourcecode = $_POST["irrigationsourcecode"];
    $plantationheader1->irrigationmethodcode = $_POST["irrigationmethodcode"];
    $plantationheader1->plantationcategorycode = $_POST["plantationcategorycode"];
    $plantationheader1->caneseedcategorycode = $_POST["caneseedcategorycode"];
    $plantationheader1->watekaricode = $_POST["watekaricode"];
    $plantationheader1->watacode = $_POST["watacode"];
    $plantationheader1->flag = $_POST["flag"];
    $plantationheader1->plantationmethodcode=$_POST["plantationmethodcode"];
    $plantationheader1->caneseedsourcecode=$_POST["caneseedsourcecode"];
    $plantationheader1->refplotnumber=$_POST["refplotnumber"];
    $plantationheader1->fertilisercode=$_POST["fertilisercode"];
    $plantationheader1->slipboycode=$_POST["slipboycode"];
    $plantationheader1->mobilenumber=$_POST["mobilenumber"];
    $plantationheader1->adharnumber=$_POST["adharnumber"];
    $plantationheader1->allowedforharvesting=$_POST["allowedforharvesting"];
    $flag_de = fnDecrypt($_GET['flag']);
    /* if ((($_POST['btn']=='Add' or ($_POST['btn']=='Change')) and $_SESSION['errors']['error']!='submitted'))
    {
      $ret = $plantationheader1->entryvalidation();
    }
    else
    {
      $ret=0;
    }

    if ($ret!=0)
    {
      $_SESSION['errors']['error'] = $plantationheader1->invalidmessagetext;
      //This is for ajax requests:
      if(!empty($_SERVER['HTTP_X_REQUESTED_WITH']) &&  strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) == 'xmlhttprequest') 
      {
        echo json_encode($_SESSION['errors']);
        exit;
      }
      //This is when Javascript is turned off:
      echo '<ul>';
      foreach($_SESSION['errors'] as $key => $value)
      {
        echo '<li>' . $value . '</li>';
      }
      echo '</ul>';
      exit;
    }
    elseif ($_SESSION['errors']['error']!='submitted')
    {
      echo json_encode(true);
      unset($_SESSION['errors']['error']);
      $_SESSION['errors']['error'] ='submitted';
      $_SESSION['button'] =$_POST['btn'];
      /* if ($_POST['btn']=='Add' or $_POST['btn']=='Change')
      {
        exit;
      } */
      
    //}
  //unset($_SESSION['errors']['error']);   */
  //$_POST['btn']
  //$_POST['button']
  switch ($_POST['btn'])
  {
    case 'नविन साठवणे':
      $ret = $plantationheader1->insert();
      if ($ret==1)
      {
        oci_commit($connection);
        echo '<span class="w3-container" style="background-color:#0a0;color:#ff8;text-align:left;">Plantation Header is added successfully</span></br>';
        echo '<a href="../ip_view/plantationheader.php">New Plantation Header</a></br>';
        $seasoncode_en = fnEncrypt($plantationheader1->seasoncode);
        $plotnumber_en = fnEncrypt($plantationheader1->plotnumber);
        $flag_en=fnEncrypt('Saved');
        header("Location: ../ip_view/plantationheader.php?seasoncode='.$seasoncode_en.'&plotnumber='.$plotnumber_en.'&flag='.$flag_en.'");
      }
      else
      {
        oci_rollback($connection);
        echo '<span style="background-color:#f44;color:#ff8;text-align:left;">'.$plantationheader1->Get_invalidmessagetext().'</span></br>';
        echo '<button onclick="history.go(-1);">Back </button>';
      }
      break;
    case 'बदल साठवणे':
      $plantationheader1->seasoncode = $_POST["seasoncode"];
      $plantationheader1->plotnumber = $_POST["plotnumber"];
      $ret = $plantationheader1->update();
      if ($ret==1)
      {
        oci_commit($connection);
        $flag_en = fnEncrypt('Query');
        echo '<span class="w3-container" style="background-color:#0a0;color:#ff8;text-align:left;">Plantation Header is Updated successfully</span></br>';  
        echo '<a href="../ip_view/plantationheader.php?flag='.$flag_en.'">Find Plantation Header</a></br>';
        $seasoncode_en = fnEncrypt($plantationheader1->seasoncode);
        $plotnumber_en = fnEncrypt($plantationheader1->plotnumber);
        $flag_en=fnEncrypt('Saved');
        header("Location: ../ip_view/plantationheader.php?seasoncode='.$seasoncode_en.'&plotnumber='.$plotnumber_en.'&flag='.$flag_en.'");
      }
      else
      {
        oci_rollback($connection);
        echo '<span style="background-color:#f44;color:#ff8;text-align:left;">'.$plantationheader1->Get_invalidmessagetext().'</span></br>';
        echo '<button onclick="history.go(-1);">Back </button>';
			}
			break;
		case 'शोधून दाखवणे':
      $plantationheader1->seasoncode = $_POST["seasoncode"];
      $plantationheader1->plotnumber = $_POST["plotnumber"];
      include("../mis/list.php");
      echo '<nav "w3-container">';
      echo '    <ul class="navbar">';
      echo '    <li><a class="navbar" href="../mis/entitymenu.php">Entity Menu</a><br/>';
      $flag_en = fnEncrypt('Query');
      echo '    <li><a class="navbar" href="../ip_view/plantationheader.php">New Plantation Header</a>';
      echo '    <li><a class="navbar" href="../ip_view/plantationheader.php?flag='.$flag_en.'">Find Plantation Header</a>';
      echo '<li><a  class="navbar" href="../../../../../sqlproc/logout.php">Log Out</a><br/>';
      echo '    </ul>';
      echo '  </nav>';
      echo '<section>';
      echo '<table border="0" >';
      
      $result1 = $plantationheader1->display();
      $i=0;
			if ($plantationheader1->Get_invalidid()==0)
			{
        $flag_en = fnEncrypt('Display');
				while ($row1 = oci_fetch_array($result1,OCI_ASSOC+OCI_RETURN_NULLS))
				{
          if ($i==0)
          {
            echo '<tr>';
            echo '<td><label for="" class="thick">List of Plot of season '.$row1['SEASONCODE'].'</label></td>';
            echo '</tr>';
            if ($_SESSION['lng']=='English')
					  {
                echo '<tr>';
                echo '<td><label for="" class="thick">Plot-Code-Surve-Hangam-Variety-Area</label></td>';
                echo '</tr>';
            }
            else
            {
              echo '<tr>';
              echo '<td><label for="" class="thick">प्लॉट-कोड-सर्वे-हंगाम-जात-क्षेत्र</label></td>';
              echo '</tr>';
            }
         }
          $i++;
          
          if ($_SESSION['lng']=='English')
					{
            echo '<tr>';
						echo '<td><a href="../ip_view/plantationheader.php?seasoncode='.fnEncrypt($row1['SEASONCODE']).'&plotnumber='.fnEncrypt($row1['PLOTNUMBER']).'&flag='.$flag_en.'">'.$row1['PLOTNUMBER'].'-'.$row1['FARMERCODE'].'-'.$row1['GUTNUMBER'].'-'.$row1['PLANTATIONHANGAMNAMEENG'].'-'.$row1['VARIETYNAMEENG'].'-'.number_format($row1['AREA'],2,".",",").'</td>';
            echo '</tr>';
					}
					else
					{
            echo '<tr>';
						echo '<td><a href="../ip_view/plantationheader.php?seasoncode='.fnEncrypt($row1['SEASONCODE']).'&plotnumber='.fnEncrypt($row1['PLOTNUMBER']).'&flag='.$flag_en.'">'.$row1['PLOTNUMBER'].'-'.$row1['FARMERCODE'].'-'.$row1['GUTNUMBER'].'-'.$row1['PLANTATIONHANGAMNAMEUNI'].'-'.$row1['VARIETYNAMEUNI'].'-'.number_format($row1['AREA'],2,".",",").'</td>';
            echo '</tr>';
					}
				}	
			}
			else
			{
				echo '<span style="background-color:#f44;color:#ff8;text-align:left;">'.$plantationheader1->Get_invalidmessagetext().'</span></br>';
        echo '<button onclick="history.go(-1);">Back </button>';
			}
			break;
		case 'काढून टाकणे':
      $plantationheader1->seasoncode = $_POST["seasoncode"];
      $plantationheader1->plotnumber = $_POST["plotnumber"];
			$ret = $plantationheader1->delete();
			if ($ret == 1)
			{
				oci_commit($connection);
        $flag_en = fnEncrypt('Query');
				echo '<span class="w3-container" style="background-color:#0a0;color:#ff8;text-align:left;">Plantation Header is Deleted Successfully</span></br>';
				echo '<a href="../ip_view/plantationheader.php?flag='.$flag_en.'">Find Plantation Header</a></br>';
			}
			else
			{
				oci_rollback($connection);
				echo '<span style="background-color:#f44;color:#ff8;text-align:left;">'.$plantationheader1->Get_invalidmessagetext().'</span></br>';
				echo '<a href="../ip_view/plantationheader.php">Find plantationheader</a></br>';
        echo '<button onclick="history.go(-1);">Back </button>';
			}
      break;
    case 'निवड (क्षेत्र मोजणी)':
        include("../mis/list.php");
        echo '<nav "w3-container">';
        echo '    <ul class="navbar">';
        echo '    <li><a class="navbar" href="../mis/entitymenu.php">मेनू</a><br/>';
        $flag_en = fnEncrypt('Query');
        echo '    <li><a class="navbar" href="../ip_view/plantationheader.php">नविन ऊस नोंद</a>';
        echo '    <li><a class="navbar" href="../ip_view/plantationheader.php?flag='.$flag_en.'">शोधा ऊस नोंद</a>';
        echo '<li><a  class="navbar" href="../../../../../sqlproc/logout.php">बाहेर पडणे (Logout)</a><br/>';
        echo '    </ul>';
        echo '  </nav>';
        echo '<section>';
        echo '<form method="post" action="../ip_controller/plantationheader_action.php">';
        echo '<table border="0" width="500px">';
        echo '<tr>';
        //echo '<td><label for="" class="thick">List of Plot for Selection</label></td>';
        echo '<td><input class="button123" type="submit" name="btn" value="निवडा (टिक केलेले)" style="width:140px"></td>';
        echo '</tr>';
        echo '<tr>';
              //echo '<td><a href="../ip_view/plantationheader.php?seasoncode='.fnEncrypt($row1['SEASONCODE']).'&plotnumber='.fnEncrypt($row1['PLOTNUMBER']).'&flag='.$flag_en.'">'.$row1['SEASONCODE'].' '.$row1['PLOTNUMBER'].'</td>';
              echo '<th style="width: 20%;text-align:left">क्षेत्र क्रं</th>';
              echo '<th style="width: 20%;text-align:left">गाव</th>';
              echo '<th style="width: 50%;text-align:left">शेतकरी</th>';
              echo '<th style="width: 10%;text-align:left">गट सर्व्हे</th>';
              echo '</tr>';
        $result1 = $plantationheader1->select();
        if ($plantationheader1->Get_invalidid()==0)
        {
          $flag_en = fnEncrypt('Select');
          while ($row1 = oci_fetch_array($result1,OCI_ASSOC+OCI_RETURN_NULLS))
          {
            if ($_SESSION['lng']=='English')
            {
              echo '<tr>';
              //echo '<td><a href="../ip_view/plantationheader.php?seasoncode='.fnEncrypt($row1['SEASONCODE']).'&plotnumber='.fnEncrypt($row1['PLOTNUMBER']).'&flag='.$flag_en.'">'.$row1['SEASONCODE'].' '.$row1['PLOTNUMBER'].'</td>';
              echo '<td><input type="checkbox" name="plots[]" value="'.$row1["PLOTNUMBER"].'">'.$row1["PLOTNUMBER"].'</td>';
              echo '<td>'.$row1["VILLAGENAMEENG"].'</td>';
              echo '<td>'.$row1["FARMERNAMEENG"].'></td>';
              echo '<td>'. $row1["GUTNUMBER"].'></td>';
              echo '</tr>';
            }
            else
            {
              echo '<tr>';
              //echo '<td><a href="../ip_view/plantationheader.php?seasoncode='.fnEncrypt($row1['SEASONCODE']).'&plotnumber='.fnEncrypt($row1['PLOTNUMBER']).'&flag='.$flag_en.'">'.$row1['SEASONCODE'].' '.$row1['PLOTNUMBER'].'</td>';
              echo '<td><input type="checkbox" name="plots[]" value="'.$row1["PLOTNUMBER"].'">'.$row1["PLOTNUMBER"].'</td>';
              echo '<td align="left">'.$row1["VILLAGENAMEUNI"].'</td>';
              echo '<td>'.$row1["FARMERNAMEUNI"].'</td>';
              echo '<td>'.$row1["GUTNUMBER"].'</td>';
              echo '</tr>';
            }
          }
        }
        else
        {
          echo '<span style="background-color:#f44;color:#ff8;text-align:left;">'.$plantationheader1->Get_invalidmessagetext().'</span></br>';
          echo '<button onclick="history.go(-1);">Back </button>';
        }
        echo '</form>';	
        break;
    case 'निवडा (टिक केलेले)':  
        $plotCount = count($_POST["plots"]);
        for($i=0;$i<$plotCount;$i++) 
        {
          $ret=$plantationheader1->insertselected($_POST["plots"][$i]);
          if ($ret==0)
          {
            break;
          }
        }
        if ($ret == 1)
        {
          oci_commit($connection);
          $flag_en = fnEncrypt('Query');
          //echo '<span class="w3-container" style="background-color:#0a0;color:#ff8;text-align:left;">Plantation Header is Deleted Successfully</span></br>';
          //echo '<a href="../ip_view/plantationheader.php?flag='.$flag_en.'">Find Plantation Header</a></br>';
          header("Location: ../ip_view/measurementselected.php");
        }
        else
        {
          oci_rollback($connection);
          echo '<span style="background-color:#f44;color:#ff8;text-align:left;">'.$plantationheader1->Get_invalidmessagetext().'</span></br>';
          echo '<a href="../ip_view/plantationheader.php">Find plantationheader</a></br>';
          echo '<button onclick="history.go(-1);">Back </button>';
        }
      break;
    case 'तपासले':
      $plantationheader1->seasoncode = $_POST["seasoncode"];
      $plantationheader1->plotnumber = $_POST["plotnumber"];
      $ret = $plantationheader1->verified();
      if ($ret==1)
      {
        oci_commit($connection);
        //$flag_en = fnEncrypt('Query');
        echo '<span class="w3-container" style="background-color:#0a0;color:#ff8;text-align:left;">Plantation Header is Updated successfully</span></br>';  
        //echo '<a href="../ip_view/plantationheader.php">Find Plantation Header</a></br>';
        header("Location: ../ip_view/unverifiedplotlist.php");
      }
      else
      {
        oci_rollback($connection);
        echo '<span style="background-color:#f44;color:#ff8;text-align:left;">'.$plantationheader1->Get_invalidmessagetext().'</span></br>';
        echo '<button onclick="history.go(-1);">Back </button>';
      }
      break;
		default:
			echo 'Communication Error';
      echo '<button onclick="history.go(-1);">Back </button>';
			break;
	}

