<?php
    //This is generated by Nigade Software Technologies (opc) Private Limited on 08/02/2020 05:35:13 pm for PHP
    require("../info/phpgetloginview.php");
    include("../info/ncryptdcrypt.php");
    require("../info/routine.php");
    include("../ip_model/plantationplotareadetail_db_oracle.php");
    $connection=swapp_connection();
    $plantationplotareadetail1 = new plantationplotareadetail($connection);
    $plantationplotareadetail1->serialnumber = $_POST["serialnumber"];
    $plantationplotareadetail1->seasoncode = $_POST["seasoncode"];
    $plantationplotareadetail1->plotnumber = $_POST["plotnumber"];
    $plantationplotareadetail1->latitude = $_POST["latitude"];
    $plantationplotareadetail1->longitude = $_POST["longitude"];
    $flag_de = fnDecrypt($_GET['flag']);
if ((($_POST['btn']=='Add' or ($_POST['btn']=='Change')) and $_SESSION['errors']['error']!='submitted'))
    {
    $ret = $plantationplotareadetail1->entryvalidation();
    }
    else
    {
      $ret=0;
    }
    if ($ret!=0)
    {
      $_SESSION['errors']['error'] = $plantationplotareadetail1->invalidmessagetext;
      //This is for ajax requests:
      if(!empty($_SERVER['HTTP_X_REQUESTED_WITH']) &&  strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) == 'xmlhttprequest') 
      {
        echo json_encode($_SESSION['errors']);
        exit;
      }
      //This is when Javascript is turned off:
      echo '<ul>';
      foreach($_SESSION['errors'] as $key => $value)
      {
        echo '<li>' . $value . '</li>';
      }
      echo '</ul>';
      exit;
    }
    elseif ($_SESSION['errors']['error']!='submitted')
    {
      echo json_encode(true);
      unset($_SESSION['errors']['error']);
      $_SESSION['errors']['error'] ='submitted';
      $_SESSION['button'] =$_POST['btn'];
      exit;
    }
  unset($_SESSION['errors']['error']);  
  switch ($_SESSION['button'])
  {
    case 'Add':
      $ret = $plantationplotareadetail1->insert();
      if ($ret==1)
      {
        oci_commit($connection);
        echo '<span class="w3-container" style="background-color:#0a0;color:#ff8;text-align:left;">plantationplotareadetail is added successfully</span></br>';
        //echo '<a href="../ip_view/plantationplotareadetail.php">New plantationplotareadetail</a></br>';
        $seasoncode_en = fnEncrypt($plantationplotareadetail1->seasoncode);
        $plotnumber_en = fnEncrypt($plantationplotareadetail1->plotnumber);
        $flag_en=fnEncrypt('Display');
        header("Location: ../ip_view/plantationheader.php?seasoncode='.$seasoncode_en.'&plotnumber='.$plotnumber_en.'&flag='.$flag_en.'");
      }
      else
      {
        oci_rollback($connection);
        echo '<span style="background-color:#f44;color:#ff8;text-align:left;">'.$plantationplotareadetail1->Get_invalidmessagetext().'</span></br>';
        echo '<button onclick="history.go(-1);">Back </button>';
      }
      break;
    case 'Change':
      $plantationplotareadetail1->serialnumber = $_POST["serialnumber"];
      $plantationplotareadetail1->seasoncode = $_POST["seasoncode"];
      $plantationplotareadetail1->plotnumber = $_POST["plotnumber"];
      $ret = $plantationplotareadetail1->update();
      if ($ret==1)
      {
        oci_commit($connection);
        $flag_en = fnEncrypt('Query');
        echo '<span class="w3-container" style="background-color:#0a0;color:#ff8;text-align:left;">plantationplotareadetail is Updated successfully</span></br>';  
        //echo '<a href="../ip_view/plantationplotareadetail.php?flag='.$flag_en.'">Find plantationplotareadetail</a></br>';
        $seasoncode_en = fnEncrypt($plantationplotareadetail1->seasoncode);
        $plotnumber_en = fnEncrypt($plantationplotareadetail1->plotnumber);
        $flag_en=fnEncrypt('Display');
        header("Location: ../ip_view/plantationheader.php?seasoncode='.$seasoncode_en.'&plotnumber='.$plotnumber_en.'&flag='.$flag_en.'");
      }
      else
      {
        oci_rollback($connection);
        echo '<span style="background-color:#f44;color:#ff8;text-align:left;">'.$plantationplotareadetail1->Get_invalidmessagetext().'</span></br>';
        echo '<button onclick="history.go(-1);">Back </button>';
			}
			break;
		case 'Display':
      $plantationplotareadetail1->serialnumber = $_POST["serialnumber"];
      $plantationplotareadetail1->seasoncode = $_POST["seasoncode"];
      $plantationplotareadetail1->plotnumber = $_POST["plotnumber"];
      include("../mis/list.php");
      echo '<nav "w3-container">';
      echo '    <ul class="navbar">';
      echo '    <li><a class="navbar" href="../mis/entitymenu.php">Entity Menu</a><br/>';
      $flag_en = fnEncrypt('Query');
      echo '    <li><a class="navbar" href="../ip_view/plantationplotareadetail.php">New plantationplotareadetail</a>';
      echo '    <li><a class="navbar" href="../ip_view/plantationplotareadetail.php?flag='.$flag_en.'">Find plantationplotareadetail</a>';
      echo '<li><a  class="navbar" href="../../../../../sqlproc/logout.php">Log Out</a><br/>';
      echo '    </ul>';
      echo '  </nav>';
      echo '<section>';
      echo '<table border="0" >';
      echo '<tr>';
      echo '<td><label for="" class="thick">List of plantationplotareadetail</label></td>';
      echo '</tr>';
			$result1 = $plantationplotareadetail1->display();
			if ($plantationplotareadetail1->Get_invalidid()==0)
			{
        $flag_en = fnEncrypt('Display');
				while ($row1 = oci_fetch_array($result1,OCI_ASSOC+OCI_RETURN_NULLS))
				{
					if ($_SESSION['lng']=='English')
					{
            echo '<tr>';
						echo '<td><a href="../ip_view/plantationplotareadetail.php?serialnumber='.fnEncrypt($row1['SERIALNUMBER']).'&seasoncode='.fnEncrypt($row1['SEASONCODE']).'&plotnumber='.fnEncrypt($row1['PLOTNUMBER']).'&flag='.$flag_en.'">'.$row1['LATITUDE'].'</td>';
            echo '</tr>';
					}
					else
					{
            echo '<tr>';
						echo '<td><a href="../ip_view/plantationplotareadetail.php?serialnumber='.fnEncrypt($row1['SERIALNUMBER']).'&seasoncode='.fnEncrypt($row1['SEASONCODE']).'&plotnumber='.fnEncrypt($row1['PLOTNUMBER']).'&flag='.$flag_en.'">'.$row1['LATITUDE'].'</td>';
            echo '</tr>';
					}
				}	
			}
			else
			{
				echo '<span style="background-color:#f44;color:#ff8;text-align:left;">'.$plantationplotareadetail1->Get_invalidmessagetext().'</span></br>';
        echo '<button onclick="history.go(-1);">Back </button>';
			}
			break;
		case 'Delete':
      $plantationplotareadetail1->serialnumber = $_POST["serialnumber"];
      $plantationplotareadetail1->seasoncode = $_POST["seasoncode"];
      $plantationplotareadetail1->plotnumber = $_POST["plotnumber"];
			$ret = $plantationplotareadetail1->delete();
			if ($ret == 1)
			{
				oci_commit($connection);
        $flag_en = fnEncrypt('Query');
				echo '<span class="w3-container" style="background-color:#0a0;color:#ff8;text-align:left;">plantationplotareadetail is Deleted Successfully</span></br>';
        //echo '<a href="../ip_view/plantationplotareadetail.php?flag='.$flag_en.'">Find plantationplotareadetail</a></br>';
        $seasoncode_en = fnEncrypt($plantationplotareadetail1->seasoncode);
        $plotnumber_en = fnEncrypt($plantationplotareadetail1->plotnumber);
        $flag_en=fnEncrypt('Display');
        header("Location: ../ip_view/plantationheader.php?seasoncode='.$seasoncode_en.'&plotnumber='.$plotnumber_en.'&flag='.$flag_en.'");
			}
			else
			{
				oci_rollback($connection);
				echo '<span style="background-color:#f44;color:#ff8;text-align:left;">'.$plantationplotareadetail1->Get_invalidmessagetext().'</span></br>';
				echo '<a href="../ip_view/plantationplotareadetail.php">Find plantationplotareadetail</a></br>';
        echo '<button onclick="history.go(-1);">Back </button>';
			}
			break;
		default:
			echo 'Communication Error';
      echo '<button onclick="history.go(-1);">Back </button>';
			break;
	}

