<?php
    //This is generated by Swapp Software Application on 04/05/2019 06:23:04 PM for PHP
    require("../info/phpgetloginview.php");
    include("../info/ncryptdcrypt.php");
    require("../info/routine.php");
    include("../ip_model/tyregadi_db_oracle.php");
    $connection=swapp_connection();
    $tyregadi1 = new tyregadi($connection);
    $tyregadi1->seasoncode = $_POST["seasoncode"];
    $tyregadi1->subcontractorcode = $_POST["subcontractorcode"];
    $tyregadi1->tyregadicode = $_POST["tyregadicode"];
    $tyregadi1->tyregadinumber = $_POST["tyregadinumber"];
    $tyregadi1->gadiwannameeng = $_POST["gadiwannameeng"];
    $tyregadi1->gadiwannameuni = $_POST["gadiwannameuni"];
    $tyregadi1->tyregadiissuedate = $_POST["tyregadiissuedate"];
    $tyregadi1->tyregadireturndate = $_POST["tyregadireturndate"];
    $tyregadi1->servicetrhrcategorycode = $_POST["servicetrhrcategorycode"];
    $tyregadi1->epccode = $_POST["epccode"];
    $tyregadi1->epccode1 = $_POST["epccode1"];
    $tyregadi1->mobilenumber = $_POST["mobilenumber"];
    $tyregadi1->isownvehicle = $_POST["isownvehicle"];
    $tyregadi1->nooftyregadi = $_POST["nooftyregadi"];
    $flag_de = fnDecrypt($_GET['flag']);
    $flag_en = fnEncrypt('Display');
    $seasoncode_en = fnEncrypt($tyregadi1->seasoncode);
    $subcontractorcode_en = fnEncrypt($tyregadi1->subcontractorcode);
    $servicetrhrcategorycode_en = fnEncrypt($tyregadi1->servicetrhrcategorycode);
    $contractcode_en = fnEncrypt($_POST['contractcode']);
  switch ($_POST['btn'])
  {
    case 'Add':
      $ret = $tyregadi1->insert();
      if ($ret==1)
      {
        oci_commit($connection);
        $flag_en = fnEncrypt('Display');
        echo '<span class="w3-container" style="background-color:#0a0;color:#ff8;text-align:left;">Vehicle is added successfully</span></br>';
        echo '<a href="../ip_view/vehicle.php">New Vehicle</a></br>';
        header("Location: ../ip_view/subcontractor.php?contractcode='.$contractcode_en.'&subcontractorcode='.$subcontractorcode_en.'&flag='.$flag_en.'");
      }
      else
      {
        oci_rollback($connection);
        echo '<span style="background-color:#f44;color:#ff8;text-align:left;">'.$tyregadi1->Get_invalidmessagetext().'</span></br>';
        echo '<button onclick="history.go(-1);">Back </button>';
      }
      break;
    case 'Change':
      $tyregadi1->seasoncode = $_POST["seasoncode"];
      $tyregadi1->tyregadicode = $_POST["tyregadicode"];
      $ret = $tyregadi1->update();
      if ($ret==1)
      {
        oci_commit($connection);
        $flag_en = fnEncrypt('Display');
        echo '<span class="w3-container" style="background-color:#0a0;color:#ff8;text-align:left;">Vehicle is Updated successfully</span></br>';  
        echo '<a href="../ip_view/vehicle.php?flag='.$flag_en.'">Find Vehicle</a></br>';
        //echo '<li><a class="navbar" href="../ip_view/vehicle.php">New Vehicle   </a>';
        //echo '<li><a class="navbar" href="../ip_view/vehicle.php?flag='.$flag_en.'">Find Vehicle   </a>';
        //echo '<li><a class="navbar" href="../ip_view/subcontractor.php?contractcode='.$contractcode_en.'&subcontractorcode='.$subcontractorcode_en.'&flag='.$flag_en.'">Sub Contractor</a>';
        header("Location: ../ip_view/subcontractor.php?contractcode='.$contractcode_en.'&subcontractorcode='.$subcontractorcode_en.'&flag='.$flag_en.'");
      }
      else
      {
        oci_rollback($connection);
        echo '<span style="background-color:#f44;color:#ff8;text-align:left;">'.$tyregadi1->Get_invalidmessagetext().'</span></br>';
        echo '<button onclick="history.go(-1);">Back </button>';
			}
			break;
		case 'Display':
      $tyregadi1->seasoncode = $_POST["seasoncode"];
      $tyregadi1->tyregadicode = $_POST["tyregadicode"];
      include("../mis/list.php");
      echo '<nav "w3-container">';
      echo '    <ul class="navbar">';
      echo '    <li><a class="navbar" href="../mis/entitymenu.php">Entity Menu</a><br/>';
      $flag_en = fnEncrypt('Query');
      echo '    <li><a class="navbar" href="../ip_view/vehicle.php">New Vehicle</a>';
      echo '    <li><a class="navbar" href="../ip_view/vehicle.php?flag='.$flag_en.'">Find Vehicle</a>';
      echo '<li><a  class="navbar" href="../../../../../sqlproc/logout.php">Log Out</a><br/>';
      echo '    </ul>';
      echo '  </nav>';
      echo '<section>';
      echo '<table border="0" >';
      echo '<tr>';
      echo '<td><label for="" class="thick">List of Vehicle</label></td>';
      echo '</tr>';
			$result1 = $tyregadi1->display();
			if ($tyregadi1->Get_invalidid()==0)
			{
        $flag_en = fnEncrypt('Display');
				while ($row1 = oci_fetch_array($result1,OCI_ASSOC+OCI_RETURN_NULLS))
				{
					if ($_SESSION['lng']=='English')
					{
            echo '<tr>';
						echo '<td><a href="../ip_view/vehicle.php?seasoncode='.fnEncrypt($row1['SEASONCODE']).'&tyregadicode='.fnEncrypt($row1['tyregadicode']).'&flag='.$flag_en.'">'.$row1['VEHICLENUMBER'].'</td>';
            echo '</tr>';
					}
					else
					{
            echo '<tr>';
						echo '<td><a href="../ip_view/vehicle.php?seasoncode='.fnEncrypt($row1['SEASONCODE']).'&tyregadicode='.fnEncrypt($row1['tyregadicode']).'&flag='.$flag_en.'">'.$row1['VEHICLENUMBER'].'</td>';
            echo '</tr>';
					}
				}	
			}
			else
			{
				echo '<span style="background-color:#f44;color:#ff8;text-align:left;">'.$tyregadi1->Get_invalidmessagetext().'</span></br>';
        echo '<button onclick="history.go(-1);">Back </button>';
			}
			break;
		case 'Delete':
      $tyregadi1->seasoncode = $_POST["seasoncode"];
      $tyregadi1->tyregadicode = $_POST["tyregadicode"];
			$ret = $tyregadi1->delete();
			if ($ret == 1)
			{
				oci_commit($connection);
        $flag_en = fnEncrypt('Query');
				echo '<span class="w3-container" style="background-color:#0a0;color:#ff8;text-align:left;">Vehicle is Deleted Successfully</span></br>';
				echo '<a href="../ip_view/vehicle.php?flag='.$flag_en.'">Find Vehicle</a></br>';
        header("Location: ../ip_view/subcontractor.php?contractcode='.$contractcode_en.'&subcontractorcode='.$subcontractorcode_en.'&flag='.$flag_en.'");
			}
			else
			{
				oci_rollback($connection);
				echo '<span style="background-color:#f44;color:#ff8;text-align:left;">'.$tyregadi1->Get_invalidmessagetext().'</span></br>';
				echo '<a href="../ip_view/vehicle.php">Find vehicle</a></br>';
        echo '<button onclick="history.go(-1);">Back </button>';
			}
			break;
		default:
			echo 'Communication Error';
      echo '<button onclick="history.go(-1);">Back </button>';
			break;
	}

