<?php
    //This is generated by Nigade Software Technologies (opc) Private Limited on 12/12/2020 10:07:24 am for PHP
    require("../info/phpgetloginview.php");
    include("../info/ncryptdcrypt.php");
    require("../info/routine.php");
    include("../ip_model/supplier_db_oracle.php");
    $connection=swapp_connection();
    $supplier1 = new supplier($connection);
    $supplier1->suppliercode = $_POST["suppliercode"];
    $supplier1->suppliernameeng = $_POST["suppliernameeng"];
    $supplier1->suppliernameuni = $_POST["suppliernameuni"];
    $supplier1->address = $_POST["address"];
    $supplier1->contactpersion = $_POST["contactpersion"];
    $supplier1->mobilenumber = $_POST["mobilenumber"];
    $supplier1->gstin = $_POST["gstin"];
    $supplier1->pannumber = $_POST["pannumber"];
    $supplier1->statecode = $_POST["statecode"];
    $flag_de = fnDecrypt($_GET['flag']);
if ((($_POST['btn']=='Add' or ($_POST['btn']=='Change')) and $_SESSION['errors']['error']!='submitted'))
    {
    $ret = $supplier1->entryvalidation();
    }
    else
    {
      $ret=0;
    }
    if ($ret!=0)
    {
      $_SESSION['errors']['error'] = $supplier1->invalidmessagetext;
      //This is for ajax requests:
      if(!empty($_SERVER['HTTP_X_REQUESTED_WITH']) &&  strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) == 'xmlhttprequest') 
      {
        echo json_encode($_SESSION['errors']);
        exit;
      }
      //This is when Javascript is turned off:
      echo '<ul>';
      foreach($_SESSION['errors'] as $key => $value)
      {
        echo '<li>' . $value . '</li>';
      }
      echo '</ul>';
      exit;
    }
    elseif ($_SESSION['errors']['error']!='submitted')
    {
      echo json_encode(true);
      unset($_SESSION['errors']['error']);
      $_SESSION['errors']['error'] ='submitted';
      $_SESSION['button'] =$_POST['btn'];
      exit;
    }
  unset($_SESSION['errors']['error']);  
  switch ($_SESSION['button'])
  {
    case 'Add':
      $ret = $supplier1->insert();
      if ($ret==1)
      {
        oci_commit($connection);
        echo '<span class="w3-container" style="background-color:#0a0;color:#ff8;text-align:left;">supplier is added successfully</span></br>';
        echo '<a href="../ip_view/supplier.php">New supplier</a></br>';
      }
      else
      {
        oci_rollback($connection);
        echo '<span style="background-color:#f44;color:#ff8;text-align:left;">'.$supplier1->Get_invalidmessagetext().'</span></br>';
        echo '<button onclick="history.go(-1);">Back </button>';
      }
      break;
    case 'Change':
      $supplier1->suppliercode = $_POST["suppliercode"];
      $ret = $supplier1->update();
      if ($ret==1)
      {
        oci_commit($connection);
        $flag_en = fnEncrypt('Query');
        echo '<span class="w3-container" style="background-color:#0a0;color:#ff8;text-align:left;">supplier is Updated successfully</span></br>';  
        echo '<a href="../ip_view/supplier.php?flag='.$flag_en.'">Find supplier</a></br>';
      }
      else
      {
        oci_rollback($connection);
        echo '<span style="background-color:#f44;color:#ff8;text-align:left;">'.$supplier1->Get_invalidmessagetext().'</span></br>';
        echo '<button onclick="history.go(-1);">Back </button>';
			}
			break;
		case 'Display':
      $supplier1->suppliercode = $_POST["suppliercode"];
      include("../mis/list.php");
      echo '<nav "w3-container">';
      echo '    <ul class="navbar">';
      echo '    <li><a class="navbar" href="../mis/entitymenu.php">Entity Menu</a><br/>';
      $flag_en = fnEncrypt('Query');
      echo '    <li><a class="navbar" href="../ip_view/supplier.php">New supplier</a>';
      echo '    <li><a class="navbar" href="../ip_view/supplier.php?flag='.$flag_en.'">Find supplier</a>';
      echo '<li><a style="color:#f48" class="navbar" href="../../../../../sqlproc/logout.php">Log Out</a><br/>';
      echo '    </ul>';
      echo '  </nav>';
      echo '<section>';
      echo '<table border="0" >';
      echo '<tr>';
      echo '<td><label for="" class="thick">List of supplier</label></td>';
      echo '</tr>';
			$result1 = $supplier1->display();
			if ($supplier1->Get_invalidid()==0)
			{
        $flag_en = fnEncrypt('Display');
				while ($row1 = oci_fetch_array($result1,OCI_ASSOC+OCI_RETURN_NULLS))
				{
					if ($_SESSION['lng']=='English')
					{
            echo '<tr>';
						echo '<td><a href="../ip_view/supplier.php?suppliercode='.fnEncrypt($row1['SUPPLIERCODE']).'&flag='.$flag_en.'">'.$row1['SUPPLIERCODE'].' '.$row1['SUPPLIERNAMEENG'].'</td>';
            echo '</tr>';
					}
					else
					{
            echo '<tr>';
						echo '<td><a href="../ip_view/supplier.php?suppliercode='.fnEncrypt($row1['SUPPLIERCODE']).'&flag='.$flag_en.'">'.$row1['SUPPLIERCODE'].' '.$row1['SUPPLIERNAMEUNI'].'</td>';
            echo '</tr>';
					}
				}	
			}
			else
			{
				echo '<span style="background-color:#f44;color:#ff8;text-align:left;">'.$supplier1->Get_invalidmessagetext().'</span></br>';
        echo '<button onclick="history.go(-1);">Back </button>';
			}
			break;
		case 'Delete':
      $supplier1->suppliercode = $_POST["suppliercode"];
			$ret = $supplier1->delete();
			if ($ret == 1)
			{
				oci_commit($connection);
        $flag_en = fnEncrypt('Query');
				echo '<span class="w3-container" style="background-color:#0a0;color:#ff8;text-align:left;">supplier is Deleted Successfully</span></br>';
				echo '<a href="../ip_view/supplier.php?flag='.$flag_en.'">Find supplier</a></br>';
			}
			else
			{
				oci_rollback($connection);
				echo '<span style="background-color:#f44;color:#ff8;text-align:left;">'.$supplier1->Get_invalidmessagetext().'</span></br>';
				echo '<a href="../ip_view/supplier.php">Find supplier</a></br>';
        echo '<button onclick="history.go(-1);">Back </button>';
			}
			break;
		default:
			echo 'Communication Error';
      echo '<button onclick="history.go(-1);">Back </button>';
			break;
	}
