<?php
    //This is generated by Swapp Software Application on 06/06/2019 12:48:22 PM for PHP
    $connection=swapp_connection();
    function swapp_database_settings(&$dbuser,&$host,&$dbname,&$pwd)
    {
        require("../info/phpsqlajax_dbinfo.php");
        // Opens a connection to a MySQL server
        $connection=mysqli_connect($hostname, $username, $password, $database);
        // Check connection
        if (mysqli_connect_errno())
        {
            echo "Communication Error";
        }
        mysqli_query($connection,'SET NAMES UTF8');
        $connection ->autocommit(FALSE);
        $query = "select * from databaseserver d,miscustomermodules c where d.miscustomerid=c.miscustomerid and d.miscustomerid=51170 and dbuser='nst_nasaka_agriculture'";
        $result = mysqli_query($connection,$query);
        if ($row = @mysqli_fetch_assoc($result))
        {
            $host = $row["host"];
            $dbname = $row["dbname"];
            $pwd = $row["dbpassword"];
        }
        $connection->close();
    }
    function swapp_connection()
    {
        require("../info/phpsqlajax_dbinfo.php");
        // Opens a connection to a MySQL server
        //$dbname = "scdbsnew";
        //$host = "192.168.1.254";
        //$dbname = "shivorclweb";
        //$dbname = "shivorcl";
        //$host = "localhost";
        //$host = "localhost";
        //$pwd="swapp123";
        //$pwd="swapp123";
        //$dbuser = "nst_agriculture";
        $dbuser = "nst_nasaka_agriculture";
        $host="NSSK_SERVER";
        //$host=gethostbyname(gethostname()).'';
        //$host = "192.168.1.100";
        $dbname="orcl";
        //$dbname="shivorcl";
        $pwd="swapp123";
        swapp_database_settings($dbuser,$host,$dbname,$pwd);
        $db= "(DESCRIPTION =
              (ADDRESS = (PROTOCOL = TCP)(HOST = ".$host.")(PORT = 1521))
              (CONNECT_DATA =
              (SERVER = DEDICATED)
                (SERVICE_NAME = ".$dbname.")
              )
           )";
        $conn = oci_connect($dbuser, $pwd, $db,"AL32UTF8");
        //$connection=mysqli_connect($hostname_rawmaterial, $username_rawmaterial, $password_rawmaterial, $database_rawmaterial);
        // Check connection
        if (!$conn)
        {
            $m = oci_error();
            echo $m['message'], "\n";
            exit;
        }
        else
        {
            //print "Connected to Oracle!";
        }
        return $conn;
    }
    function currentdate()
    {
        date_default_timezone_set("Asia/Kolkata");
        $dt = time();
        $dt = date('d/m/Y',$dt);
        date_default_timezone_set("UTC");
        return $dt;
    }

?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"></meta>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="../css/w3.css">
        <title>Contract</title>
        <link rel="stylesheet" href="../css/swapp123.css">
        <script src="../js/1.11.0/jquery.min.js">
         </script>
         <script>
            $(document).ready(function(){
             setInterval(function(){cache_clear()},3600000);
             });
             function cache_clear()
            {
             window.location.reload(true);
            }
        </script>
        <script>
                window.setTimeout(function () {
                window.location.reload();
        }, 30000);
        </script>
        <link rel="stylesheet" href="../css/ui/1.11.4/themes/smoothness/jquery-ui.css">
        <script src="../js/jquery-1.10.2.js"></script>
        <script src="../js/ui/1.11.4/jquery-ui.js"></script>
    </head>
    <body>
        <nav "w3-container">
            <ul class="navbar">
                <li><a class="navbar" href="/index.php">Home</a><br/>
                <li><a class="navbar" href="../mis/entitymenu.php">Entity Menu</a><br/>
                <li><a class="navbar" href="/agriculture/1.0/customer/nasaka/op_view/shiftwisetonnage.php">Shiftwise Tonnage</a><br/>
                <li><a class="navbar" href="/agriculture/1.0/customer/nasaka/op_view/circletonnage.php">Circlewise Tonnage</a><br/>
            </ul>
        </nav>
        <article class="w3-container">
    <?php
        echo '<section>';
        echo '<div style="width:1000px;float:left">';
        echo '<table border="0">';
        echo '<tr>';
        echo '<td></td>';
            $date=currentdate();
            //$date='02/03/2021';
            $dt=DateTime::createFromFormat('d/m/Y',$date)->format('d-M-Y');
            echo '<div style="width:800px;float:left">';
            echo '<tr>';
            echo '<td><label class="thick">दिनांक : '.$date.' तासनिहाय गळीत</label></td>';
            echo '</tr>';
            echo '<table border="0">';

            echo '<tr>';
            echo '<th width="10%" style="text-align:left;background:#FEC994;">शिफ्ट</th>';
            echo '<th width="10%" style="text-align:right;background:#FEC994;">तास</th>';
            echo '<th width="15%" style="text-align:right;background:#FEC994;">ट्रक संख्या</th>';
            echo '<th width="15%" style="text-align:right;background:#FEC994;">ट्रक टनेज</th>';
            echo '<th width="15%" style="text-align:right;background:#FEC994;">ट्रॅक्टर संख्या</th>';
            echo '<th width="15%" style="text-align:right;background:#FEC994;">ट्रॅक्टर टनेज</th>';
            echo '<th width="15%" style="text-align:right;background:#FEC994;">ट्रॅक्टर टायर संख्या</th>';
            echo '<th width="15%" style="text-align:right;background:#FEC994;">ट्रॅक्टर टायर टनेज</th>';
            echo '<th width="15%" style="text-align:right;background:#FEC994;">बैलगाडी संख्या</th>';
            echo '<th width="15%" style="text-align:right;background:#FEC994;">बैलगाडी टनेज</th>';
            echo '<th width="15%" style="text-align:right;background:#FEC994;">हार्वेस्टर संख्या</th>';
            echo '<th width="15%" style="text-align:right;background:#FEC994;">हार्वेस्टर टनेज</th>';
            echo '<th width="20%" style="text-align:right;background:#FEC994;">‌एकूण संख्या</th>';
            echo '<th width="20%" style="text-align:right;background:#FEC994;">‌एकूण टनेज</th>';
            echo '</tr>';
            
            $query0 ="select nvl(shiftcode,0) shiftcode
            ,sum(t.truck_tonnage) truck_tonnage
            ,sum(t.tractor_tonnage) tractor_tonnage
            ,sum(t.mini_tonnage) mini_tonnage
            ,sum(t.bulluckcart_tonnage) bulluckcart_tonnage
            ,sum(t.harvester_tonnage) harvester_tonnage
            ,sum(t.truck_tonnage)+sum(t.tractor_tonnage)+sum(t.mini_tonnage)+sum(t.bulluckcart_tonnage)+sum(t.harvester_tonnage) total_tonnage
            ,sum(t.truck_cnt) truck_cnt
            ,sum(t.tractor_cnt) tractor_cnt
            ,sum(t.mini_cnt) mini_cnt
            ,sum(t.bulluckcart_cnt) bulluckcart_cnt
            ,sum(t.harvester_cnt) harvester_cnt
            ,sum(t.truck_cnt)+sum(t.tractor_cnt)+sum(t.mini_cnt)+sum(t.bulluckcart_cnt)+sum(t.harvester_cnt) total_cnt
            from HOURLYTONNAGE t 
            where t.weighmentdate='{$dt}' 
            group by nvl(shiftcode,0)
            order by nvl(shiftcode,0)";
            $trucktonnage=0;
            $tractortonnage=0;
            $minitonnage=0;
            $harvestertonnage=0;
            $bulluckcarttonnage=0;

            $truckcnt=0;
            $tractorcnt=0;
            $minicnt=0;
            $harvestercnt=0;
            $bulluckcartcnt=0;
            $cnt=0;
            
            $tonnage=0;
            $result0 = oci_parse($connection, $query0);
            $r0 = oci_execute($result0);
            while ($row0 = oci_fetch_array($result0,OCI_ASSOC+OCI_RETURN_NULLS))
            {
                $query ="select *
                from HOURLYTONNAGE t 
                where t.weighmentdate='{$dt}'
                and shiftcode=".$row0['SHIFTCODE'].
                " order by shiftcode,hours";
                $result = oci_parse($connection, $query);
                $r = oci_execute($result);
                
                while ($row = oci_fetch_array($result,OCI_ASSOC+OCI_RETURN_NULLS))
                {
                    echo '<tr>';
                    if ($row['HOURS']>24) 
                        $hr=$row['HOURS']-24;
                    elseif ($row['HOURS']>12) 
                        $hr=$row['HOURS']-12;
                    else
                        $hr=$row['HOURS']; 

                    if ($row['SHIFTCODE']==1)
                    {
                        $backgroundcolor='#ECAFB4';
                    }
                    elseif ($row['SHIFTCODE']==2)
                    {
                        $backgroundcolor='#E1F8DC';
                    }    
                    elseif ($row['SHIFTCODE']==3)
                    {
                        $backgroundcolor='#ACDDDE';
                    }   
                    echo '<td style="text-align:left;font-size:16px;background:'.$backgroundcolor.';"><a >'.$row['SHIFTCODE'].'</a></td>';
                    echo '<td style="text-align:right;font-size:16px;background:'.$backgroundcolor.';"><a >'.$hr.'</a></td>';
                    echo '<td style="text-align:right;font-size:16px"><a >'.$row['TRUCK_CNT'].'</a></td>';
                    echo '<td style="text-align:right;font-size:16px"><a >'.$row['TRUCK_TONNAGE'].'</a></td>';
                    echo '<td style="text-align:right;font-size:16px;background:'.$backgroundcolor.'"><a >'.$row['TRACTOR_CNT'].'</a></td>';
                    echo '<td style="text-align:right;font-size:16px;background:'.$backgroundcolor.'"><a >'.$row['TRACTOR_TONNAGE'].'</a></td>';
                    echo '<td style="text-align:right;font-size:16px"><a >'.$row['MINI_CNT'].'</a></td>';
                    echo '<td style="text-align:right;font-size:16px"><a >'.$row['MINI_TONNAGE'].'</a></td>';
                    echo '<td style="text-align:right;font-size:16px"><a >'.$row['BULLUCKCART_CNT'].'</a></td>';
                    echo '<td style="text-align:right;font-size:16px"><a >'.$row['BULLUCKCART_TONNAGE'].'</a></td>';
                    echo '<td style="text-align:right;font-size:16px;background:'.$backgroundcolor.'"><a >'.$row['HARVESTER_CNT'].'</a></td>';
                    echo '<td style="text-align:right;font-size:16px;background:'.$backgroundcolor.'"><a >'.$row['HARVESTER_TONNAGE'].'</a></td>';
                    echo '<td style="text-align:right;font-size:16px"><a >'.($row['TRUCK_CNT']+$row['TRACTOR_CNT']+$row['MINI_CNT']+$row['BULLUCKCART_CNT']+$row['HARVESTER_CNT']).'</a></td>';
                    echo '<td style="text-align:right;font-size:16px"><a >'.($row['TRUCK_TONNAGE']+$row['TRACTOR_TONNAGE']+$row['MINI_TONNAGE']+$row['BULLUCKCART_TONNAGE']+$row['HARVESTER_TONNAGE']).'</a></td>';
                    echo '</tr>';
                    
                }
                $trucktonnage=$trucktonnage+$row0['TRUCK_TONNAGE'];
                $tractortonnage=$tractortonnage+$row0['TRACTOR_TONNAGE'];
                $minitonnage=$minitonnage+$row0['MINI_TONNAGE'];
                $bulluckcarttonnage=$bulluckcarttonnage+$row0['BULLUCKCART_TONNAGE'];

                $truckcnt=$truckcnt+$row0['TRUCK_CNT'];
                $tractorcnt=$tractorcnt+$row0['TRACTOR_CNT'];
                $minicnt=$minicnt+$row0['MINI_CNT'];
                $bulluckcartcnt=$bulluckcartcnt+$row0['BULLUCKCART_CNT'];
                $harvestercnt=$harvestercnt+$row0['HARVESTER_CNT'];

                $harvestertonnage=$harvestertonnage+$row0['HARVESTER_TONNAGE'];
                $tonnage=$tonnage+$row0['TOTAL_TONNAGE'];
                $cnt=$cnt+$row0['TOTAL_CNT'];
                echo '<tr>';
                /* if ($row['HOURS']>24) 
                    $hr=$row['HOURS']-24;
                elseif ($row['HOURS']>12) 
                    $hr=$row['HOURS']-12;
                else
                    $hr=$row['HOURS'];  */

                $backgroundcolor='#FEC994';
                echo '<td style="text-align:left;font-size:16px;background:'.$backgroundcolor.';"><a >'.$row0['SHIFTCODE'].'</a></td>';
                echo '<td style="text-align:right;font-size:16px;background:'.$backgroundcolor.';"><a >एकूण</a></td>';
                echo '<td style="text-align:right;font-size:16px;background:'.$backgroundcolor.';"><a >'.$row0['TRUCK_CNT'].'</a></td>';
                echo '<td style="text-align:right;font-size:16px;background:'.$backgroundcolor.';"><a >'.$row0['TRUCK_TONNAGE'].'</a></td>';
                echo '<td style="text-align:right;font-size:16px;background:'.$backgroundcolor.'"><a >'.$row0['TRACTOR_CNT'].'</a></td>';
                echo '<td style="text-align:right;font-size:16px;background:'.$backgroundcolor.'"><a >'.$row0['TRACTOR_TONNAGE'].'</a></td>';
                echo '<td style="text-align:right;font-size:16px;background:'.$backgroundcolor.';"><a >'.$row0['MINI_CNT'].'</a></td>';
                echo '<td style="text-align:right;font-size:16px;background:'.$backgroundcolor.';"><a >'.$row0['MINI_TONNAGE'].'</a></td>';
                echo '<td style="text-align:right;font-size:16px;background:'.$backgroundcolor.';"><a >'.$row0['BULLUCKCART_CNT'].'</a></td>';
                echo '<td style="text-align:right;font-size:16px;background:'.$backgroundcolor.';"><a >'.$row0['BULLUCKCART_TONNAGE'].'</a></td>';
                echo '<td style="text-align:right;font-size:16px;background:'.$backgroundcolor.'"><a >'.$row0['HARVESTER_CNT'].'</a></td>';
                echo '<td style="text-align:right;font-size:16px;background:'.$backgroundcolor.'"><a >'.$row0['HARVESTER_TONNAGE'].'</a></td>';
                echo '<td style="text-align:right;font-size:16px;background:'.$backgroundcolor.';"><a >'.$row0['TOTAL_CNT'].'</a></td>';
                echo '<td style="text-align:right;font-size:16px;background:'.$backgroundcolor.';"><a >'.$row0['TOTAL_TONNAGE'].'</a></td>';
                echo '</tr>';
            }
                echo '<tr>';
                echo '<td style="text-align:left;font-size:16px;background:#A9BA9D;"><a >'.$date.'</a></td>';
                echo '<td style="text-align:right;font-size:16px;background:#A9BA9D;"><a >एकूण</a></td>';
                echo '<td style="text-align:right;font-size:16px;background:#A9BA9D;"><a >'.$truckcnt.'</a></td>';
                echo '<td style="text-align:right;font-size:16px;background:#A9BA9D;"><a >'.$trucktonnage.'</a></td>';
                echo '<td style="text-align:right;font-size:16px;background:#A9BA9D;"><a >'.$tractorcnt.'</a></td>';
                echo '<td style="text-align:right;font-size:16px;background:#A9BA9D;"><a >'.$tractortonnage.'</a></td>';
                echo '<td style="text-align:right;font-size:16px;background:#A9BA9D;"><a >'.$minicnt.'</a></td>';
                echo '<td style="text-align:right;font-size:16px;background:#A9BA9D;"><a >'.$minitonnage.'</a></td>';
                echo '<td style="text-align:right;font-size:16px;background:#A9BA9D;"><a >'.$bulluckcartcnt.'</a></td>';
                echo '<td style="text-align:right;font-size:16px;background:#A9BA9D;"><a >'.$bulluckcarttonnage.'</a></td>';
                echo '<td style="text-align:right;font-size:16px;background:#A9BA9D;"><a >'.$harvestercnt.'</a></td>';
                echo '<td style="text-align:right;font-size:16px;background:#A9BA9D;"><a >'.$harvestertonnage.'</a></td>';
                echo '<td style="text-align:right;font-size:16px;background:#A9BA9D;"><a >'.$cnt.'</a></td>';
                echo '<td style="text-align:right;font-size:16px;background:#A9BA9D;"><a >'.$tonnage.'</a></td>';
                echo '</tr>';
            echo '</table>';
            echo '</div>';
            date_default_timezone_set('Asia/Kolkata');
                $date = date('d-m-Y h:i:s a');
                echo 'Report Date Time:'.$date;
            echo '<div style="width:800px;float:left">';
            echo '<table border="0">';
        echo '</section>';
    ?>
    </article>
    <footer>
    </footer>
    </body>
</html>

