    <!--$addresponsibilityid=123457306;
    $alterresponsibilityid=123457406;-->
<?php
    //This is generated by Swapp Software Application on 23/10/2018 04:55:49 PM for PHP
    require("../info/phpsqlajax_dbinfo.php");
    require("../info/phpgetlogin.php");
    include("../info/ncryptdcrypt.php");
    require("../info/routine.php");
    require("../ip_model/saledetail_db_oracle.php");
    //Addition or Alteration
    $addresponsibilityid=123457306;
    $alterresponsibilityid=123457406;
    if (isaccessible($addresponsibilityid)==0 and isaccessible($alterresponsibilityid)==0)
    {
        echo'Communication Error';
        exit;
    }
    $shiftcode_de = fnDecrypt($_GET['shiftcode']);
    $transactioncategoryid_de = fnDecrypt($_GET['transactioncategoryid']);
    $reftransactionid_de = fnDecrypt($_GET['reftransactionid']);
    $transactionid_de = fnDecrypt($_GET['transactionid']);
    $flag_de = fnDecrypt($_GET['flag']);
    $connection = petrolpump_connection();
    $petrolpumpcode = petrolpumpcode($connection,$reftransactionid_de);
    $customertypecode = customertypecode($connection,$reftransactionid_de);
    $entryspecial = entryspecial($connection,$reftransactionid_de);
    function entryspecial(&$connection,$transactionid)
    {
        $query = "select s.entryspecial from saleheader s 
            where s.transactionid=".$transactionid;
        $result = oci_parse($connection, $query);
        $r = oci_execute($result);
        if ($row = oci_fetch_array($result,OCI_ASSOC+OCI_RETURN_NULLS))
        {
            $trnid = $row['ENTRYSPECIAL']; 
        } 
        else 
        {
            $trnid = 0;
        }   
        return $trnid;
    }
    function customertypecode(&$connection,$transactionid)
    {
        $query = "select s.customertypecode from saleheader s 
            where s.transactionid=".$transactionid;
        $result = oci_parse($connection, $query);
        $r = oci_execute($result);
        if ($row = oci_fetch_array($result,OCI_ASSOC+OCI_RETURN_NULLS))
        {
            $trnid = $row['CUSTOMERTYPECODE']; 
        } 
        else 
        {
            $trnid = 0;
        }   
        return $trnid;
    }
    function petrolpumpcode(&$connection,$transactionid)
    {
        $query = "select p.petrolpumpcode from saleheader s,pump p 
            where s.pumpcode=p.pumpcode and s.transactionid=".$transactionid;
        $result = oci_parse($connection, $query);
        $r = oci_execute($result);
        if ($row = oci_fetch_array($result,OCI_ASSOC+OCI_RETURN_NULLS))
        {
            $trnid = $row['PETROLPUMPCODE']; 
        } 
        else 
        {
            $trnid = 0;
        }   
        return $trnid;
    }
    function pumpitem(&$connection,$transactionid)
    {
        $query = "select p.itemcode 
        from saleheader s,pump p 
        where s.pumpcode=p.pumpcode and transactionid=".$transactionid;
        $result = oci_parse($connection, $query);
        $r = oci_execute($result);
        if ($row = oci_fetch_array($result,OCI_ASSOC+OCI_RETURN_NULLS))
        {
            $trnid = $row['ITEMCODE']; 
        } 
        else 
        {
            $trnid = 0;
        }   
        return $trnid;
    }
    function qtyslip(&$connection,$transactionid,&$qty,&$slipno)
    {
        $query = "select c.refcode
        from saleheader s,customer c
        where s.customercode=c.customercode and transactionid=".$transactionid;
        $result = oci_parse($connection, $query);
        $r = oci_execute($result);
        if ($row = oci_fetch_array($result,OCI_ASSOC+OCI_RETURN_NULLS))
        {
            $query1 = "select 
            weigh_qty(".$row['REFCODE'].") as qty,
            weigh_slipno(".$row['REFCODE'].") as slipno
            from dual";
            $result1 = oci_parse($connection, $query1);
            $r1 = oci_execute($result1);
            if ($row1 = oci_fetch_array($result1,OCI_ASSOC+OCI_RETURN_NULLS))
            {
                $qty = $row1['QTY']; 
                $slipno = $row1['SLIPNO'];
            }
            else 
            {
                $qty = 0; 
                $slipno = 0;
            }  
        } 
        else 
        {
            $qty = 0; 
            $slipno = 0;
        } 
    }
    function qtyslipjugad(&$connection,$transactionid,&$qty,&$slipno)
    {
        $query = "select c.refcode
        from saleheader s,customer c
        where s.customercode=c.customercode and transactionid=".$transactionid;
        $result = oci_parse($connection, $query);
        $r = oci_execute($result);
        if ($row = oci_fetch_array($result,OCI_ASSOC+OCI_RETURN_NULLS))
        {
            $query1 = "select 
            weigh_qty(".$row['REFCODE'].") as qty,
            weigh_slipno(".$row['REFCODE'].") as slipno
            from dual";
            $result1 = oci_parse($connection, $query1);
            $r1 = oci_execute($result1);
            if ($row1 = oci_fetch_array($result1,OCI_ASSOC+OCI_RETURN_NULLS))
            {
                $qty = $row1['QTY']; 
                $slipno = $row1['SLIPNO'];
            }
            else 
            {
                $qty = 0; 
                $slipno = 0;
            }  
        } 
        else 
        {
            $qty = 0; 
            $slipno = 0;
        }   
    }
    function qtyslip_new(&$connection,$transactionid,&$qty,&$slipno,&$distance)
    {
        $query = "select c.refcode
        from saleheader s,customer c
        where s.customercode=c.customercode and transactionid=".$transactionid;
        $result = oci_parse($connection, $query);
        $r = oci_execute($result);
        $p_qty = 0; 
        $p_slip_no = 0;
        $p_distance = 0;
        if ($row = oci_fetch_array($result,OCI_ASSOC+OCI_RETURN_NULLS))
        {
            $p_transporter_code = $row['REFCODE'];
            $query1 = "BEGIN;weigh_qty_proc(:p_transporter_code,:p_slip_no,
            :p_qty,:p_distance);END;";
            $result1 = oci_parse($connection,$query1);
            oci_bind_by_name($result1,':p_transporter_code',$p_transporter_code,20);
            oci_bind_by_name($result1,':p_slip_no',$p_slip_no,20);
            oci_bind_by_name($result1,':p_qty',$p_qty,20);
            oci_bind_by_name($result1,':p_distance',$p_distance,20);
            /*$query1 = "select 
            weigh_qty(".$row['CUSTOMERCODE'].") as qty,
            weigh_slipno(".$row['CUSTOMERCODE'].") as slipno
            from dual";*/
            $r1 = oci_execute($result1);
            if (oci_execute($result1))
            {
                $qty = $p_qty; 
                $slipno = $p_slip_no;
                $distance = $p_distance;
            }
            else 
            {
                $e = oci_error();   // For oci_connect errors do not pass a handle
                trigger_error(htmlentities($e['message']), E_USER_ERROR);
                $qty = 0; 
                $slipno = 0;
                $distance = 0;
            }
        } 
        else 
        {
            $qty = 0; 
            $slipno = 0;
            $distance = 0;
        }   
    }
?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"></meta>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="../css/w3.css">
        <title>Sale Detail</title>
<style type="text/css">
            body
            {
                background-color: #fff;
            }
            header
            {
                background-color: #fff;
                min-height: 38px;
                color: #070;
                font-family: Arial;
                font-size: 19px;
            }
            nav
            {
                width: 300px;
                float: left;
                list-style-type: none;
                font-family: verdana;
                font-size: 15px;
                color: #f48;
                line-height: 30px;
            }
            a
            {
                color: #f48;
            }
            article
            {
                background-color: #fff;
                display: table;
                margin-left: 0px;
                padding-left: 10px;
                font-family: Verdana;
                font-size: 15px;
            }
            section
            {
                margin-left: 0px;
                margin-right: 15px;
                float: left;
                text-align: justify;
                color: #000;
                line-height: 23px;
            }
            footer
            {
                float: bottom;
                color: #000;
                font-family: verdana;
                font-size: 12px;
            }
            div
            {
                float:left;
            }
            input, textarea
            {
                outline: none;
                background-color: #fff
            }
            button
            {
                width:200px;
                height:35px;
                color:#000;
                border-radius: 5px;
            }
            input:focus, textarea:focus
            {
                border-radius: 5px;
                outline: none;
                background-color: #fef
            }
            input[readonly],select:disabled
            {
                border-radius: 10px;
                outline: none;
                background-color:lightblue;
                color:black;
            }
            label
            {
                color: #000;
            }
            .rightJustified 
            {
                text-align: right;
            }
        </style>
        <script src="../js/1.11.0/jquery.min.js">
         </script>
         <script>
            $(document).ready(function(){
             setInterval(function(){cache_clear()},3600000);
             });
             function cache_clear()
            {
             window.location.reload(true);
            }
        </script>
        <link rel="stylesheet" href="../css/ui/1.11.4/themes/smoothness/jquery-ui.css">
        <script src="..//js/jquery-1.10.2.js"></script>
        <script src="..//js/ui/1.11.4/jquery-ui.js"></script>
        <script>
            $(function()
            {
                $("#item").autocomplete({
                source: 'item_search.php?invoicedate='+$("#invoicedate").val()+'&customertypecode='+$("#customertypecode").val(),
                minLength:1,
                delay:200,
                select:function(event,ui)
                {var v = ui.item.value;
                 var i = ui.item.id;
                 var r = ui.item.rate;
                $('#itemcode').val(i);
                this.value = v;
                $('#rate').val(r);
                return false;}
                });
            });
        </script>
        <script type="text/javascript">
            function qtycal()
            {
                
                var qty = Number(document.getElementById("qty").value);
                var rate = Number(document.getElementById("rate").value);
                
                if (qty === "")
                    qty = 0;
                if (rate === "")
                    rate = 0; 
                var amount=0;
                amount = Number((rate*qty).toFixed(2));
                if (!isNaN(amount)) 
                { 
                    document.getElementById('amount').value = amount;
                } 
            }
        </script>
    </head>
    <body>
        <nav "w3-container">
            <ul class="navbar">
                <li><a class="navbar" href="../ip_view/entitymenu.php">Entity Menu</a><br/>
                <?php
                    //customization starts
                    $shiftcode_en = fnEncrypt($shiftcode_de);
                    $transactioncategoryid_en = fnEncrypt($transactioncategoryid_de);
                    $transactionid_en = fnEncrypt($reftransactionid_de);
                    $flag_en = fnEncrypt('Display');
                    echo '<li><a class="servicebar" href="../ip_view/saleheader.php?shiftcode='.$shiftcode_en.'&transactioncategoryid='.$transactioncategoryid_en.'&transactionid='.$transactionid_en.'&flag='.$flag_en.'">Saleheader</a>';
                    echo '<li><a style="color:#f48" class="navbar" href="../../../../../sqlproc/logout.php">Log Out</a><br/>';
                ?>
            </ul>
        </nav>
        <article class="w3-container">
        <div><img src="../img/saledetail.png" width="201" height="41px"></div>
 
 
<?php
    $saledetail1 = new saledetail($connection);
    $saledetail1->transactionid=$transactionid_de;
    $saledetail1->fetch();
    echo '<section>';
    echo '<form method="post" action="../ip_controller/saledetail_action.php" autocomplete="off">';
    echo '<div style="width:300px;float:left;">';
    echo '<table border="0" >';
        if (isset($reftransactionid_de))
        {
            $invoicedate=invoicedate($connection,$reftransactionid_de);
            echo '<tr>';
            echo '<input type="hidden" style="font-size:12pt;height:30px" name="invoicedate" id="invoicedate" value="'.$invoicedate.'" style="width:300px">';
            echo '<input type="hidden" style="font-size:12pt;height:30px" name="$customertypecode" id="$customertypecode" value="'.$customertypecode.'" style="width:300px">';
            echo '</tr>';
        }
        echo '<tr>';
        echo '<td></td>';
        echo '</tr>';
        /*if ($saledetail1->found == false or $saledetail1->found == true or $flag_de == 'Query')
        {
            if ($_SESSION['lng']=="English")
            {
                echo '<tr>';
                echo '<td><label for="itemcode">Item</label></td>';
                echo '</tr>';
            }
            else
            {
                echo '<tr>';
                echo '<td><label for="itemcode">माल</label></td>';
                echo '</tr>';
            }
            echo '<tr>';
            if ($_SESSION['lng']=="English")
            {
                echo '<td><input autofocus type="text" style="font-size:12pt;height:30px" name="item" id="item" value="'.$saledetail1->itemnameeng.'" style="width:300px"></td>';
            }
            else
            {
                echo '<td><input autofocus type="text" style="font-size:12pt;height:30px" name="item" id="item" value="'.$saledetail1->itemnameuni.'" style="width:300px"></td>';
            }
            echo '<td><label for="item">*</label></td>';
             echo '</tr>';
             echo '<tr>';
            echo '<td><input type="text" readonly="readonly" tabindex="-1" class="rightJustified" style="font-size:12pt;height:30px" name="itemcode" id="itemcode" value="'.$saledetail1->itemcode.'" style="width:300px"></td>';
             echo '</tr>';
        }*/
        if ($saledetail1->found == false or $saledetail1->found == true or $flag_de == 'Query')
        {
            if ($_SESSION['lng']=="English")
            {
                echo '<tr>';
                echo '<td><label for="itemcode">Item</label></td>';
                echo '</tr>';
            }
            else
            {
                echo '<tr>';
                echo '<td><label for="itemcode">माल</label></td>';
                echo '</tr>';
            }
            echo '<tr>';
            $itemcode = pumpitem($connection,$reftransactionid_de);
            if ($saledetail1->found == false)
            {
                $saledetail1->itemcode = $itemcode;
            }
            $query1 = "select itemcode as code,itemnameeng as name_eng,itemnameuni as name_unicode from item";
            $result1 = oci_parse($connection, $query1);
            $r = oci_execute($result1);
            echo '<tr>';
            echo '<td><select autofocus name="itemcode" style="height:35px;font-size:14px;">';
            if ($_SESSION['lng']=="English")
            {
                echo '<option value="0">[No]</option>';
            }
            else
            {
                echo '<option value="0">[नाही]</option>';
            }
            while ($row1 = oci_fetch_array($result1,OCI_ASSOC+OCI_RETURN_NULLS))
            {
                if ($_SESSION['lng']=="English")
                {
                    if ($row1['CODE']==$saledetail1->itemcode)
                    {
                        echo '<option value="'.$row1['CODE'].'" Selected>'.$row1['NAME_ENG'].'</option>';
                    }
                    else
                    {
                        echo '<option value="'.$row1['CODE'].'">'.$row1['NAME_ENG'].'</option>';
                    }
                 }
                 else
                 {
                     if ($row1['CODE']==$saledetail1->itemcode)
                     {
                         echo'<option value="'.$row1['CODE'].'" Selected>'.$row1['NAME_UNICODE'].'</option>';
                     }
                     else
                     {
                         echo '<option value="'.$row1['CODE'].'">'.$row1['NAME_UNICODE'].'</option>';
                     }
                 }
             }
             echo '</select>';
             echo '<td><label for="itemcode">*</label></td>';
             echo '</tr>';
        }
        if ($customertypecode==248767479 or $customertypecode==248804823)
        {
            $qty=0;
            $slipno=0;
            $distance=0;
            if ($entryspecial==0)
            {
                if ($customertypecode==248767479)
                {
                    qtyslip($connection,$reftransactionid_de,$qty,$slipno);
                }
                elseif ($customertypecode==248804823)
                {
                    qtyslipjugad($connection,$reftransactionid_de,$qty,$slipno);
                }
            }
            if ($saledetail1->found == false or $saledetail1->found == true or $flag_de == 'Query')
            {
                if ($_SESSION['lng']=="English")
                {
                    echo '<tr>';
                    echo '<td><label for="wbslipnumber">Weigh Slip No</label></td>';
                    echo '</tr>';
                }
                else
                {
                    echo '<tr>';
                    echo '<td><label for="wbslipnumber">वजन स्लीप नंबर</label></td>';
                    echo '</tr>';
                }
                echo '<tr>';
                if ($saledetail1->found == false and $entryspecial==0)
                {
                    $saledetail1->wbslipnumber = $slipno;
                    echo '<td><input tabindex="-1" autofocus type="text" style="font-size:12pt;height:30px" name="wbslipnumber" id="wbslipnumber" value="'.$saledetail1->wbslipnumber.'" style="width:300px"></td>';
                }
                else
                {
                    echo '<td><input type="text" style="font-size:12pt;height:30px" name="wbslipnumber" id="wbslipnumber" value="'.$saledetail1->wbslipnumber.'" style="width:300px"></td>';
                }
                echo '</tr>';
            }
        }

        if ($saledetail1->found == false or $saledetail1->found == true or $flag_de == 'Query')
        {
            if ($_SESSION['lng']=="English")
            {
                echo '<tr>';
                echo '<td><label for="qty">Quantity</label></td>';
                echo '</tr>';
            }
            else
            {
                echo '<tr>';
                echo '<td><label for="qty">प्रमाण(लि)</label></td>';
                echo '</tr>';
            }
            echo '<tr>';
            if ($saledetail1->found == false and $entryspecial==0)
            {
                $saledetail1->qty = $qty;
                $saledetail1->maxqty = $qty;
            }
            echo '<td><input autofocus type="text" style="font-size:12pt;height:30px" name="qty" id="qty" value="'.$saledetail1->qty.'" style="width:300px" onkeyup="qtycal()"></td>';
            echo '<td><label for="qty">*</label></td>';
            echo '</tr>';
        }
        if ($saledetail1->found == false or $saledetail1->found == true or $flag_de == 'Query')
        {
            if ($_SESSION['lng']=="English")
            {
                echo '<tr>';
                echo '<td><label for="rate">Rate</label></td>';
                echo '</tr>';
            }
            else
            {
                echo '<tr>';
                echo '<td><label for="rate">दर</label></td>';
                echo '</tr>';
            }
            if ($saledetail1->found == false)
            {
                $saledetail1->rate = itemrate($connection,$saledetail1->itemcode,$invoicedate,$petrolpumpcode);
                $rate=$saledetail1->rate;
            }
            echo '<tr>';
            echo '<td><input readonly="readonly" tabindex="-1" type="text" style="font-size:12pt;height:30px" name="rate" id="rate" value="'.$saledetail1->rate.'" style="width:300px" onkeyup="qtycal()"></td>';
            echo '<td><label for="rate">*</label></td>';
            echo '</tr>';
        }
        if ($flag_de != 'Query')
        {
            if ($_SESSION['lng']=="English")
            {
                echo '<tr>';
                echo '<td><label for="amount">Amount</label></td>';
                echo '</tr>';
            }
            else
            {
                echo '<tr>';
                echo '<td><label for="amount">रक्कम</label></td>';
                echo '</tr>';
            }
            echo '<tr>';
            if ($saledetail1->found==false)
            echo '<td><input type="text" readonly="readonly" tabindex="-1" class="rightJustified" style="font-size:12pt;height:30px" name="amount" id="amount" value="'.($qty*$rate).'" style="width:300px"></td>';
            else
            echo '<td><input type="text" readonly="readonly" tabindex="-1" class="rightJustified" style="font-size:12pt;height:30px" name="amount" id="amount" value="'.$saledetail1->amount.'" style="width:300px"></td>';
            echo '</tr>';
        }
        echo '<tr>';
        echo '<td><input type="hidden" style="font-size:12pt;height:30px" name="entityglobalgroupid" id="entityglobalgroupid" value="'.$entityglobalgroupid_de.'" style="width:300px"></td>';
        echo '<td><input type="hidden" style="font-size:12pt;height:30px" name="yearperiodcode" id="yearperiodcode" value="'.$yearperiodcode_de.'" style="width:300px"></td>';
        echo '<td><input type="hidden" style="font-size:12pt;height:30px" name="shiftcode" id="shiftcode" value="'.$shiftcode_de.'" style="width:300px"></td>';
        echo '<td><input type="hidden" style="font-size:12pt;height:30px" name="transactioncategoryid" id="transactioncategoryid" value="'.$transactioncategoryid_de.'" style="width:300px"></td>';
        echo '<td><input type="hidden" style="font-size:12pt;height:30px" name="reftransactionid" id="reftransactionid" value="'.$reftransactionid_de.'" style="width:300px"></td>';
        echo '<td><input type="hidden" style="font-size:12pt;height:30px" name="transactionid" id="transactionid" value="'.$transactionid_de.'" style="width:300px"></td>';
        echo '<td><input type="hidden" style="font-size:12pt;height:30px" name="maxqty" id="maxqty" value="'.$saledetail1->maxqty.'" style="width:300px"></td>';
        echo '</tr>';
        if (($_SESSION['responsibilitycode']==$addresponsibilityid or $_SESSION['responsibilitycode']==$alterresponsibilityid) and $flag_de=='Query')
        {
            echo '<tr>';
            echo '<td><input type="submit" name="btn" value="Display" style="width:100px"></td>';
            echo '</tr>';
        }
        elseif ($_SESSION['responsibilitycode']==$alterresponsibilityid and $saledetail1->found==true)
        {
            echo '<tr>';
            echo '<td><input type="submit" name="btn" value="Change" style="width:100px"></td>';
            echo '</tr>';
            echo '<tr>';
            echo '<td><input type="submit" name="btn" value="Delete" style="width:100px"></td>';
            echo '</tr>';
        }
        elseif (($_SESSION['responsibilitycode']==$addresponsibilityid or $_SESSION['responsibilitycode']==$alterresponsibilityid) and $saledetail1->found==false)
        {
            echo '<tr>';
            echo '<td><input type="submit" name="btn" value="Add" style="width:100px"></td>';
            echo '</tr>';
        }
        echo '</table>';
        echo '</form>';
        echo '</section>';
    ?>
    </article>
    <footer>
    </footer>
    </body>
</html>
