<?php
//This is generated by Nigade Software Technologies (opc) Private Limited 13/10/2020 06:43:28 pm for PHP
require_once("../base/formbase.php");
class tripdetail extends swappform
{
    Public $seasoncode;
    Public $tripnumber;
    Public $fieldslipnumber;
    public function __construct(&$connection)
    {
     		 parent::__construct($connection);
         $this->seasoncode='';
         $this->seasoncodetextcombo='';
         $this->tripnumber='';
         $this->tripnumbertextcombo='';
         $this->fieldslipnumber='';
         $this->fieldslipnumbertextcombo='';
	   }
    public function entryvalidation()
    {
    		$this->start_validation();
    		$this->invalidid=0;
    		$this->invalidmessagetext='Validated';
            $this->end_validation();
            return $this->invalidid;
    }
    private function datavalidation()
    {
            $this->start_validation();
    		$this->invalidid=0;
    		$this->invalidmessagetext='Validated';
    		$this->end_validation();
    		return $this->invalidid;
    }
    public function insert()
    {
        $query = "
            insert into tripdetail(
            seasoncode
            ,tripnumber
            ,fieldslipnumber
	        )
	        values (
            ".$this->invl($this->seasoncode,true)."
            ,".$this->invl($this->tripnumber,true)."
            ,".$this->invl($this->fieldslipnumber,true)."
            )";
        $result = oci_parse($this->connection, $query);
        if (oci_execute($result,OCI_NO_AUTO_COMMIT))
        {
            return 1;
            exit;
        }
        else
        {
            return 0;
            exit;
        }
    }
    public function update()
    {
        $query = "
        update tripdetail set 
        fieldslipnumber = ".$this->invl($this->fieldslipnumber,true,true)."
        where 
        seasoncode = ".$this->invl($this->seasoncode,true)."
         and tripnumber = ".$this->invl($this->tripnumber,true)."
        ";
        $result = oci_parse($this->connection, $query);
        if (oci_execute($result,OCI_NO_AUTO_COMMIT))
        {
            return 1;
            exit;
        }
            else
        {
            return 0;
            exit;
        }
    }
    public function delete()
    {
        $query = "
        delete from tripdetail
        where 
        seasoncode = ".$this->invl($this->seasoncode,true)."
         and tripnumber = ".$this->invl($this->tripnumber,true)."
        ";
        $result = oci_parse($this->connection, $query);
        if (oci_execute($result,OCI_NO_AUTO_COMMIT))
        {
             return 1;
             exit;
        }
        else
        {
            return 0;
            exit;
        }
    }
}
?>

