<?php
//This is generated by Swapp Software Application on 19/03/2019 06:42:17 PM for PHP
require_once("../swappbase/formbase.php");
require_once("../ip_model/saletenderheader_db_oracle.php");
class salememodetail extends swappform
{
    Public $transactionnumber;
    Public $serialnumber;
    Public $finishedgoodscode;
    Public $productionyearcode;
    Public $salequantity;
    Public $salerate;
    Public $transportationrate;
    Public $transportationamount;
    Public $amount;
    Public $cgstrate;
    Public $sgstrate;
    Public $igstrate;
    Public $ugstrate;
    Public $cgstamount;
    Public $sgstamount;
    Public $igstamount;
    Public $ugstamount;
    Public $totaltaxamount;
    Public $grossamount;
    Public $tendertransactionnumber;
    Public $ordertransactionnumber;
    public $balancequantity;
    //for information
    Public $finishedgoodsnameeng;
    Public $finishedgoodsnameuni;
    Public $tendernumberpresuf;
    public function __construct(&$connection)
    {
        parent::__construct($connection);
        $this->transactionnumber='';
        $this->serialnumber='';
        $this->finishedgoodscode='';
        $this->productionyearcode='';
        $this->salequantity='';
        $this->salerate='';
        $this->amount='';
        $this->cgstrate='';
        $this->sgstrate='';
        $this->igstrate='';
        $this->ugstrate='';
        $this->cgstamount='';
        $this->sgstamount='';
        $this->igstamount='';
        $this->ugstamount='';
        $this->grossamount='';
        $this->tendertransactionnumber='';
        $this->ordertransactionnumber='';
	}
    private function entryvalidation()
    {
   		$this->start_validation();
        $this->checkrequired($this->finishedgoodscode,'Goods Name');
        $this->checkrequired($this->salequantity,'Quantity');
        if ($this->salequantity>$this->balancequantity)
        {
            $this->invalidid=-250;
    		$this->invalidmessagetext='Quntity greater than Order';
        }
        if ($this->dataoperationmode == operationmode::Insert)
        {
            if ($this->balance($this->transactionnumber)<$this->grossamount)
            {
                $this->invalidid=-250;
    		    $this->invalidmessagetext='Insufficient Balance';
            }
        }
        elseif ($this->dataoperationmode == operationmode::Update)
        {
            if (($this->balance($this->transactionnumber)+$this->storeddetailamount())<$this->grossamount)
            {
                $this->invalidid=-250;
    		    $this->invalidmessagetext='Insufficient Balance';
            }
        }
        $this->end_validation();
        return $this->invalidid;
	}
    private function datavalidation()
    {
        $this->start_validation();
    		$this->invalidid=0;
    		$this->invalidmessagetext='Validated';
    		$this->end_validation();
    		return $this->invalidid;
    }
    public function insert()
    {
        $this->dataoperationmode = operationmode::Insert;
	    if ($this->entryvalidation() <> 0)
        {
            return 0;
            exit;
        }
        elseif ($this->datavalidation() <> 0)
        {
            return 0;
            exit;
        }
	    if ($this->serialnumber == '')
        {
            $query = "select nvl(max(serialnumber),0)+1 as serialnumber 
            from salememodetail 
            where transactionnumber=".$this->transactionnumber;
            $result = oci_parse($this->connection, $query);
            $r = oci_execute($result,OCI_NO_AUTO_COMMIT);
            $row = oci_fetch_array($result,OCI_ASSOC+OCI_RETURN_NULLS);
            $this->serialnumber = $row["SERIALNUMBER"];
        }
        $query = "
            insert into salememodetail(
            transactionnumber
            ,serialnumber
            ,finishedgoodscode
            ,productionyearcode
            ,salequantity
            ,salerate
            ,transportationrate
            ,amount
            ,transportationamount
            ,cgstrate
            ,sgstrate
            ,igstrate
            ,ugstrate
            ,cgstamount
            ,sgstamount
            ,igstamount
            ,ugstamount
            ,totaltaxamount
            ,grossamount
            ,tendertransactionnumber
            ,ordertransactionnumber
	        )
	        values (
            ".$this->invl($this->transactionnumber,true)."
            ,".$this->invl($this->serialnumber,true)."
            ,".$this->invl($this->finishedgoodscode,true,true)."
            ,".$this->invl($this->productionyearcode,true)."
            ,".$this->invl($this->salequantity,true)."
            ,".$this->invl($this->salerate,true)."
            ,".$this->invl($this->transportationrate,true)."
            ,".$this->invl($this->amount,true)."
            ,".$this->invl($this->transportationamount,true)."
            ,".$this->invl($this->cgstrate,true)."
            ,".$this->invl($this->sgstrate,true)."
            ,".$this->invl($this->igstrate,true)."
            ,".$this->invl($this->ugstrate,true)."
            ,".$this->invl($this->cgstamount,true)."
            ,".$this->invl($this->sgstamount,true)."
            ,".$this->invl($this->igstamount,true)."
            ,".$this->invl($this->ugstamount,true)."
            ,".$this->invl($this->totaltaxamount,true)."
            ,".$this->invl($this->grossamount,true)."
            ,".$this->invl($this->tendertransactionnumber,true)."
            ,".$this->invl($this->ordertransactionnumber,true)."
            )";
        $result = oci_parse($this->connection, $query);
        if (oci_execute($result,OCI_NO_AUTO_COMMIT))
        {
            $sql = 'BEGIN salememoheader_update(:p_transactionnumber); END;';
            $result = oci_parse($this->connection,$sql);
            oci_bind_by_name($result,':p_transactionnumber',$transactionnumber,20);
            $transactionnumber=$this->transactionnumber;
            $r=oci_execute($result);
            return 1;
            exit;
        }
        else
        {
            return 0;
            exit;
        }
    }
    public function display()
	  {
		    $this->dataoperationmode = operationmode::Select;
		    $cond='';
		    if ($this->finishedgoodscode!='' and $this->finishedgoodscode!=0)
		    {
			      if ($cond=='')
			      {
				        $cond="t.finishedgoodscode = ".$this->finishedgoodscode;
			       }
			       else
			       {
				         $cond=$cond." and t.finishedgoodscode = ".$this->finishedgoodscode;
			       }
		    }
		    if ($this->productionyearcode!='' and $this->productionyearcode!=0)
		    {
			      if ($cond=='')
			      {
				        $cond="t.productionyearcode = ".$this->productionyearcode;
			       }
			       else
			       {
				         $cond=$cond." and t.productionyearcode = ".$this->productionyearcode;
			       }
		    }
        if ($cond!='')
		    {
		        $query = "select t.* from salememodetail t where ".$cond." order by transactionnumber,serialnumber";
			      $result = oci_parse($this->connection, $query);
            $r = oci_execute($result,OCI_NO_AUTO_COMMIT);
			      return $result;
		     }
		     else
		     {
		         $query = "select t.* from salememodetail t order by transactionnumber,serialnumber";
			       $result = oci_parse($this->connection, $query);
             $r = oci_execute($result,OCI_NO_AUTO_COMMIT);
			       return $result;
		     }
	  }
    public function update()
    {
        $this->dataoperationmode = operationmode::Update;
        if ($this->entryvalidation() <> 0)
        {
            return 0;
            exit;
        }
        elseif ($this->datavalidation() <> 0)
        {
            return 0;
            exit;
        }
        $query = "
        update salememodetail set 
        finishedgoodscode = ".$this->invl($this->finishedgoodscode,true)."
        ,productionyearcode = ".$this->invl($this->productionyearcode,true)."
        ,salequantity = ".$this->invl($this->salequantity,true)."
        ,salerate = ".$this->invl($this->salerate,true)."
        ,transportationrate = ".$this->invl($this->transportationrate,true)."
        ,amount = ".$this->invl($this->amount,true)."
        ,transportationamount = ".$this->invl($this->transportationamount,true)."
        ,cgstrate = ".$this->invl($this->cgstrate,true)."
        ,sgstrate = ".$this->invl($this->sgstrate,true)."
        ,igstrate = ".$this->invl($this->igstrate,true)."
        ,ugstrate = ".$this->invl($this->ugstrate,true)."
        ,vatrate = ".$this->invl($this->vatrate,true)."
        ,cgstamount = ".$this->invl($this->cgstamount,true)."
        ,sgstamount = ".$this->invl($this->sgstamount,true)."
        ,igstamount = ".$this->invl($this->igstamount,true)."
        ,ugstamount = ".$this->invl($this->ugstamount,true)."
        ,vatamount = ".$this->invl($this->vatamount,true)."
        ,totaltaxamount = ".$this->invl($this->totaltaxamount,true)."
        ,grossamount = ".$this->invl($this->grossamount,true)."
        ,tendertransactionnumber = ".$this->invl($this->tendertransactionnumber,true)."
        ,ordertransactionnumber = ".$this->invl($this->ordertransactionnumber,true)."
        where 
        transactionnumber = ".$this->invl($this->transactionnumber,true)."
        and serialnumber = ".$this->invl($this->serialnumber,true)."
        ";
        $result = oci_parse($this->connection, $query);
        if (oci_execute($result,OCI_NO_AUTO_COMMIT))
        {
            $sql = 'BEGIN salememoheader_update(:p_transactionnumber); END;';
            $result = oci_parse($this->connection,$sql);
            oci_bind_by_name($result,':p_transactionnumber',$transactionnumber,20);
            $transactionnumber=$this->transactionnumber;
            $r=oci_execute($result);
            return 1;
            exit;
        }
            else
        {
            return 0;
            exit;
        }

    }
    public function delete()
    {
        $this->dataoperationmode = operationmode::Delete;
        if ($this->entryvalidation() <> 0)
        {
            return 0;
            exit;
        }
        elseif ($this->datavalidation() <> 0)
        {
            return 0;
            exit;
        }
        $query = "
        delete from salememodetail
        where 
        transactionnumber = ".$this->invl($this->transactionnumber,true)."
        and serialnumber = ".$this->invl($this->serialnumber,true)."
        ";
        $result = oci_parse($this->connection, $query);
        if (oci_execute($result,OCI_NO_AUTO_COMMIT))
        {
            $sql = 'BEGIN salememoheader_update(:p_transactionnumber); END;';
            $result = oci_parse($this->connection,$sql);
            oci_bind_by_name($result,':p_transactionnumber',$transactionnumber,20);
            $transactionnumber=$this->transactionnumber;
            $r=oci_execute($result);
             return 1;
             exit;
        }
        else
        {
            return 0;
            exit;
        }
    }
    public function fetch()
    {
        $this->dataoperationmode = operationmode::Select;
        $query = "select 
        h.transactionnumber
        ,serialnumber
        ,s.finishedgoodscode
        ,productionyearcode
        ,salequantity
        ,salerate
        ,transportationrate
        ,amount
        ,transportationamount
        ,s.cgstrate
        ,s.sgstrate
        ,s.igstrate
        ,s.ugstrate
        ,s.cgstamount
        ,s.sgstamount
        ,s.igstamount
        ,s.ugstamount
        ,s.totaltaxamount
        ,s.grossamount
        ,tendertransactionnumber
        ,ordertransactionnumber
        ,f.finishedgoodsnameeng
        ,f.finishedgoodsnameuni
        ,h.goodscategorycode
        from salememoheader h,salememodetail s,finishedgoods f 
        where h.transactionnumber=s.transactionnumber
        and s.finishedgoodscode=f.finishedgoodscode 
        and s.transactionnumber = ".$this->invl($this->transactionnumber,true)."
        and s.serialnumber = ".$this->invl($this->serialnumber,true);
        $result = oci_parse($this->connection, $query);
        $r = oci_execute($result,OCI_NO_AUTO_COMMIT);
        if ($row = oci_fetch_array($result,OCI_ASSOC+OCI_RETURN_NULLS))
        {
            $this->transactionnumber = $row['TRANSACTIONNUMBER'];
            $this->serialnumber = $row['SERIALNUMBER'];
            $this->finishedgoodscode = $row['FINISHEDGOODSCODE'];
            $this->productionyearcode = $row['PRODUCTIONYEARCODE'];
            $this->salequantity = $row['SALEQUANTITY'];
            $this->salerate = $row['SALERATE'];
            $this->transportationrate = $row['TRANSPORTATIONRATE'];
            $this->amount = $row['AMOUNT'];
            $this->transportationrate = $row['TRANSPORTATIONAMOUNT'];
            $this->cgstrate = $row['CGSTRATE'];
            $this->sgstrate = $row['SGSTRATE'];
            $this->igstrate = $row['IGSTRATE'];
            $this->ugstrate = $row['UGSTRATE'];
            $this->vatrate = $row['VATRATE'];
            $this->cgstamount = $row['CGSTAMOUNT'];
            $this->sgstamount = $row['SGSTAMOUNT'];
            $this->igstamount = $row['IGSTAMOUNT'];
            $this->ugstamount = $row['UGSTAMOUNT'];
            $this->vatamount = $row['VATAMOUNT'];
            $this->totaltaxamount = $row['TOTALTAXAMOUNT'];
            $this->grossamount = $row['GROSSAMOUNT'];
            $this->tendertransactionnumber = $row['TENDERTRANSACTIONNUMBER'];
            $this->ordertransactionnumber = $row['ORDERTRANSACTIONNUMBER'];
            $this->finishedgoodsnameeng = $row['FINISHEDGOODSNAMEENG'];
            $this->finishedgoodsnameuni = $row['FINISHEDGOODSNAMEUNI'];
            $saletenderheader1 = new saletenderheader($this->connection);
            $saletenderheader1->transactionnumber = $this->tendertransactionnumber;
            $saletenderheader1->goodscategorycode = $row['GOODSCATEGORYCODE'];
            $saletenderheader1->fetch();
            $this->tendernumberpresuf = $saletenderheader1->tendernumberpresuf;
            $this->found=true;
            return true;
        }
        else
        {
        return false;
        }
    }
    public function fetchall()
    {
        $this->dataoperationmode = operationmode::Select;
        $query = "select 
        transactionnumber
        ,serialnumber
        ,d.finishedgoodscode
        ,salequantity
        ,transportationrate
        ,productionyearcode
        ,transportationamount
        ,finishedgoodsnameeng
        ,finishedgoodsnameuni
        ,salerate
        from salememodetail d,finishedgoods m where
         d.finishedgoodscode=m.finishedgoodscode 
        and d.transactionnumber = ".$this->invl($this->transactionnumber,true)."
        ";
        $result = oci_parse($this->connection, $query);
        return $result;
    }
    public function isinvoiceexist()
    {
        $this->dataoperationmode = operationmode::Select;
        $query = "select count(*) as cnt 
        from saleinvoiceheader h
        where h.salememotransactionnumber = ".$this->transactionnumber;
        $result = oci_parse($this->connection, $query);
        $r = oci_execute($result,OCI_NO_AUTO_COMMIT);
        if ($row = oci_fetch_array($result,OCI_ASSOC+OCI_RETURN_NULLS))
        {
            if ($row['CNT']==0)
            {
                return false;
            }
            else
            {
                return true;
            }
        }
        else
        {
            return false;
        }
    }
    public function balance($transactionnumber)
    {
        $this->dataoperationmode = operationmode::Select;
        $query1 = "select * from salememoheader where transactionnumber=".$transactionnumber;
        $result1 = oci_parse($this->connection, $query1);
        $r1 = oci_execute($result1,OCI_NO_AUTO_COMMIT);
        if ($row1 = oci_fetch_array($result1,OCI_ASSOC+OCI_RETURN_NULLS))
        {
            $query = "select subledger,sum(clearbalance+uncleardebit) as balance 
            from (
            select subledgercode as subledger,nst_nasaka_finance.subaccountclosingbalance(p_yearcode => ".$_SESSION['yearperiodcode'].",p_accountcode => 1100099,p_subledgercode => p.subledgercode) as clearbalance,0 as uncleardebit
            from (select t.subledgercode 
            from nst_nasaka_finance.accountsubledger t
            where t.accountcode=1100099 and t.referencecode='P'||".$row1['PURCHASERCODE'].")p
            union all
            select g.subledgercode,0 as clearbalance,nvl(sum(h.grossamount),0) as uncleardebit 
            from nst_nasaka_sale.salememoheader h
            ,nst_nasaka_sale.goodspurchaser p
            ,nst_nasaka_finance.accountsubledger g 
            where h.purchasercode=p.purchasercode
            and g.accountcode=1100099 
            and to_number(substr(g.referencecode,2,10))=p.purchasercode
            and p.purchasercode=".$row1['PURCHASERCODE']."
            and h.transactionnumber not in (select s.salememotransactionnumber 
            from nst_nasaka_sale.saleinvoiceheader s where nvl(s.grossamount,0)>0
            and s.purchasercode=p.purchasercode and s.invoicenumber is not null)
            group by g.subledgercode) t
            group by subledger";
            $result = oci_parse($this->connection, $query);
            $r = oci_execute($result,OCI_NO_AUTO_COMMIT);
            if ($row = oci_fetch_array($result,OCI_ASSOC+OCI_RETURN_NULLS))
            {
                return $row['BALANCE']*-1;
            }
            else
            {
                return 0;
            }
        }
        else
        {
            return 0;
        }
    }

    public function storeddetailamount()
    {
        $this->dataoperationmode = operationmode::Select;
        $query1 = "select grossamount from salememodetail 
        where transactionnumber=".$this->transactionnumber.
        " and serialnumber=".$this->serialnumber;
        $result1 = oci_parse($this->connection, $query1);
        $r1 = oci_execute($result1,OCI_NO_AUTO_COMMIT);
        if ($row1 = oci_fetch_array($result1,OCI_ASSOC+OCI_RETURN_NULLS))
        {
            return $row1['GROSSAMOUNT'];
        }
        else
        {
            return 0;
        }
    }
}
?>