<?php
    //This is generated by Nigade Software Technologies (opc) Private Limited on 12/12/2020 10:11:01 am for PHP
    require_once("../info/phpsqlajax_dbinfo.php");
    require_once("../info/phpgetloginform.php");
    require_once("../info/ncryptdcrypt.php");
    require_once("../info/routine.php");
    require_once("../ip_model/enquiryrequisitiondetail_db_oracle.php");
    $connection=swapp_connection();
    //Addition or Alteration
    $addresponsibilityid=getresponsibilityid($connection,1);
    $alterresponsibilityid=getresponsibilityid($connection,2);
    if (isaccessible($addresponsibilityid)==0 and isaccessible($alterresponsibilityid)==0)
    {
        echo'Communication Error';
        exit;
    }
    $transactionnumber_de = fnDecrypt($_GET['transactionnumber']);
    $serialnumber_de  = fnDecrypt($_GET['serialnumber']);
    $flag_de = fnDecrypt($_GET['flag']);
    $enquiryrequisitiondetail1 = new enquiryrequisitiondetail($connection);
    $enquiryrequisitiondetail1->transactionnumber=$transactionnumber_de;
    $enquiryrequisitiondetail1->serialnumber=$serialnumber_de;
    $enquiryrequisitiondetail1->fetch();
?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"></meta>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="../css/w3.css">
        <title>enquiryrequisitiondetail</title>
        <link rel="stylesheet" href="../css/swapp123.css">
        <script src="../js/1.11.0/jquery.min.js">
         </script>
         <script>
            $(document).ready(function(){
             setInterval(function(){cache_clear()},3600000);
             });
             function cache_clear()
            {
             window.location.reload(true);
            }
        </script>
        <script>
            var data = {};
            $(document).ready(function() {
            $('input[type="submit"]').on('click', function() {
            resetErrors();
            var url = '../ip_controller/enquiryrequisitiondetail_action.php';
            $.each($('form input, form select'), function(i, v) {
            if (v.type !== 'submit') {
            data[v.name] = v.value;
            //data['btn']=$('input[type="submit"]').val();
            data['btn']=document.activeElement.getAttribute('value');
            }
            }); //end each
            $.ajax({
            dataType: 'json',
            type: 'POST',
            url: url,
            data: data,
            success: function(resp) {
            if (resp === true) {
            //successful validation
            data['btn']=$('input[type="submit"]').val();
            $('form').submit();
            console.log('submitted');
            return false;
            } else {
            $.each(resp, function(i, v) {
            console.log(i + " => " + v); // view in console for error messages
            var msg = '<label class="error" for="'+i+'">'+v+'</label>';
            $('input[name="' + i + '"], select[name="' + i + '"]').addClass('').after(msg);
            });
            var keys = Object.keys(resp);
            $('input[name="'+keys[0]+'"]').focus();
            }
            return false;
            },
            error: function() {
            console.log('there was a problem checking the fields');
            }
            });
            return false;
            });
            });
            function resetErrors() {
            $('form input, form select').removeClass('inputTxtError');
            $('label.error').remove();
            }
        </script>
        <link rel="stylesheet" href="../css/ui/1.11.4/themes/smoothness/jquery-ui.css">
        <script src="..//js/jquery-1.10.2.js"></script>
        <script src="..//js/ui/1.11.4/jquery-ui.js"></script>
        <script>
            $(function()
            {
                $("#sectioncodetextcombo").autocomplete({
                source: 'sectionmaster_search.php',
                minLength:1,
                delay:200,
                delay:200,
                autoFocus:true,
                autoselect:true,
                select:function(event,ui)
                {var v = ui.item.value;
                 var i = ui.item.id;
                $('#sectioncode').val(i);
                this.value = v;
                return false;},
                change:function (event, ui) {
                if (ui.item === null) {
                $('#sectioncodetextcombo').val('');
                }
           }
                });
            });
        </script>
        <script>
            $(function()
            {
                $("#requisitiontransactiontextcombo").autocomplete({
                source: function(request, response) {
                    $.getJSON("enquiryrequisition_search.php", 
                    { term: request.term,sectioncode:$('#sectioncode').val()}, 
                            response);
                },
                minLength:1,
                delay:200,
                delay:200,
                autoFocus:true,
                autoselect:true,
                select:function(event,ui)
                {var v = ui.item.value;
                 var i = ui.item.id;
                $('#requisitiontransaction').val(i);
                this.value = v;
                return false;},
                change:function (event, ui) {
                if (ui.item === null) {
                $('#requisitiontransaction').val('');
                }
           }
                });
            });
        </script>
    </head>
    <body>
        <nav "w3-container">
            <ul class="navbar">
                <li><a class="navbar" href="../mis/entitymenu.php">Entity Menu</a><br/>
                <?php
                    $transactionnumber_en = fnEncrypt($transactionnumber_de);
                    echo '<li><a class="navbar" href="../ip_view/enquiryheader.php?transactionnumber='.fnEncrypt($transactionnumber_de).'">Enquiry</a>';
                    echo '<li><a style="color:#f48" class="navbar" href="../../../../../sqlproc/logout.php">Log Out</a><br/>';
                ?>
            </ul>
        </nav>
        <article class="w3-container">


<?php
    echo '<section>';
    echo '<form method="post" action="../ip_controller/enquiryrequisitiondetail_action.php">';
    echo '<div style="width:250px;float:left">';
    echo '<table border="0" >';
    echo '<tr>';
    echo '<td></td>';
    echo '</tr>';
    echo '<img src="../img/createimage.php?name=enquiryrequisitiondetail&width=251&size=14&r=150&g=0&b=0&r1=255&g1=230&b1=0"></br></br>';
    if ($flag_de == 'Query')
    {
        echo '<img src="../img/createimage.php?name=Find Records&width=201&size=12&r=255&g=255&b=255&r1=0&g1=150&b1=0">';
    }
    elseif ($flag_de == 'Display' and $_SESSION['responsibilitycode']==$alterresponsibilityid )
    {
       echo '<img src="../img/createimage.php?name=Change/Delete Record&width=201&size=12&r=255&g=255&b=255&r1=0&g1=150&b1=0">';
    }
    elseif ($enquiryrequisitiondetail1->found == false)
    {
       echo '<img src="../img/createimage.php?name=New Record Entry&width=201&size=12&r=255&g=255&b=255&r1=0&g1=150&b1=0">';
    }
        //record query parameter
        if ($flag_de == 'Query')
        {
            $enquiryrequisitiondetail1->textcombobox($fieldname='requisitiontransaction',$combosearchfield='requisitionheader',$combocodefield='requisitiontransaction',$englishlabel='Requisition',$unicodelabel='मागणी',$value=$enquiryrequisitiondetail1->requisitiontransactiontextcombo,$codevalue=$enquiryrequisitiondetail1->requisitiontransaction,$width=200,$height=30
            ,$iscompulsory=True,$isreadonly=False,$found=$enquiryrequisitiondetail1->found,$flag=$flag_de,$js='',$isautofocus=false,$searchtextbox='requisitiontransactiontextcombo');
        }
        //new record
        elseif ($enquiryrequisitiondetail1->found == false)
        {
            //$enquiryrequisitiondetail1->textbox($fieldname='transactionnumber',$englishlabel='Transaction Number',$unicodelabel='व्यवहार क्रमांक',$value=$enquiryrequisitiondetail1->transactionnumber,$width=200,$height=30,$align='right',$iscompulsory=True,$isreadonly=False,$found=$enquiryrequisitiondetail1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $enquiryrequisitiondetail1->textcombobox($fieldname='sectioncode',$combosearchfield='section',$combocodefield='sectioncode',$englishlabel='Section',$unicodelabel='उप विभाग',$value=$enquiryrequisitiondetail1->sectioncodetextcombo,$codevalue=$enquiryrequisitiondetail1->sectioncode,$width=200,$height=30
            ,$iscompulsory=True,$isreadonly=False,$found=$enquiryrequisitiondetail1->found,$flag=$flag_de,$js='',$isautofocus=false,$searchtextbox='sectioncodetextcombo');
            $enquiryrequisitiondetail1->textcombobox($fieldname='requisitiontransaction',$combosearchfield='requisitionheader',$combocodefield='requisitiontransaction',$englishlabel='Requisition',$unicodelabel='मागणी',$value=$enquiryrequisitiondetail1->requisitiontransactiontextcombo,$codevalue=$enquiryrequisitiondetail1->requisitiontransaction,$width=200,$height=30
            ,$iscompulsory=True,$isreadonly=False,$found=$enquiryrequisitiondetail1->found,$flag=$flag_de,$js='',$isautofocus=false,$searchtextbox='requisitiontransactiontextcombo');
        }
        //record found
        elseif ($enquiryrequisitiondetail1->found == true)
        {
            //$enquiryrequisitiondetail1->textbox($fieldname='transactionnumber',$englishlabel='Transaction Number',$unicodelabel='व्यवहार क्रमांक',$value=$enquiryrequisitiondetail1->transactionnumber,$width=200,$height=30,$align='right',$iscompulsory=True,$isreadonly=False,$found=$enquiryrequisitiondetail1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $enquiryrequisitiondetail1->textcombobox($fieldname='sectioncode',$combosearchfield='section',$combocodefield='sectioncode',$englishlabel='Section',$unicodelabel='उप विभाग',$value=$enquiryrequisitiondetail1->sectioncodetextcombo,$codevalue=$enquiryrequisitiondetail1->sectioncode,$width=200,$height=30
            ,$iscompulsory=True,$isreadonly=False,$found=$enquiryrequisitiondetail1->found,$flag=$flag_de,$js='',$isautofocus=false,$searchtextbox='sectioncodetextcombo');
            $enquiryrequisitiondetail1->textcombobox($fieldname='requisitiontransaction',$combosearchfield='requisitionheader',$combocodefield='requisitiontransaction',$englishlabel='Requisition',$unicodelabel='मागणी',$value=$enquiryrequisitiondetail1->requisitiontransactiontextcombo,$codevalue=$enquiryrequisitiondetail1->requisitiontransaction,$width=200,$height=30
            ,$iscompulsory=True,$isreadonly=False,$found=$enquiryrequisitiondetail1->found,$flag=$flag_de,$js='',$isautofocus=false,$searchtextbox='requisitiontransactiontextcombo');
        }
        echo '<tr>';
        echo '<td><input class="button123" type="hidden" style="font-size:12pt;height:30px" name="transactionnumber" id="transactionnumber" value="'.$transactionnumber_de.'" style="width:300px"></td>';
        echo '<td><input class="button123" type="hidden" style="font-size:12pt;height:30px" name="serialnumber" id="serialnumber" value="'.$serialnumber_de.'" style="width:300px"></td>';
echo '<tr>';
echo '<td><input class="error" type="hidden" style="font-size:12pt;height:30px" name="error" id="error" value="error" style="width:300px"></td>';
echo '</tr>';
        echo '</tr>';
        if (($_SESSION['responsibilitycode']==$addresponsibilityid or $_SESSION['responsibilitycode']==$alterresponsibilityid) and $flag_de=='Query')
        {
            echo '<tr>';
            echo '<td><input class="button123" type="submit" name="btn" value="Display" style="width:100px"></td>';
            echo '</tr>';
        }
        elseif ($_SESSION['responsibilitycode']==$alterresponsibilityid and $enquiryrequisitiondetail1->found==true)
        {
            echo '<tr>';
            echo '<td><input class="button123" type="submit" name="btn" value="Change" style="width:100px"></td>';
            echo '</tr>';
            echo '<tr>';
            echo '<td><input class="button123" type="submit" name="btn" value="Delete" style="width:100px"></td>';
            echo '</tr>';
        }
        elseif (($_SESSION['responsibilitycode']==$addresponsibilityid or $_SESSION['responsibilitycode']==$alterresponsibilityid) and $enquiryrequisitiondetail1->found==false)
        {
            echo '<tr>';
            echo '<td><input class="button123" type="submit" name="btn" value="Add" style="width:100px"></td>';
            echo '</tr>';
        }
        echo '</table>';
        echo '</div>';
        echo '</form>';
        echo '</section>';
    ?>
    </article>
    <footer>
    </footer>
    </body>
</html>

