<?php
    //This is generated by Nigade Software Technologies (opc) Private Limited on 12/12/2020 10:34:53 am for PHP
    require_once("../info/phpsqlajax_dbinfo.php");
    require_once("../info/phpgetloginform.php");
    require_once("../info/ncryptdcrypt.php");
    require_once("../info/routine.php");
    require_once("../ip_model/invoiceitemdetail_db_oracle.php");
    $connection=swapp_connection();
    //Addition or Alteration
    $addresponsibilityid=getresponsibilityid($connection,1);
    $alterresponsibilityid=getresponsibilityid($connection,2);
    if (isaccessible($addresponsibilityid)==0 and isaccessible($alterresponsibilityid)==0)
    {
        echo'Communication Error';
        exit;
    }
    $transactionnumber_de = fnDecrypt($_GET['transactionnumber']);
    $serialnumber_de = fnDecrypt($_GET['serialnumber']);
    $flag_de = fnDecrypt($_GET['flag']);
    $invoiceitemdetail1 = new invoiceitemdetail($connection);
    $invoiceitemdetail1->transactionnumber=$transactionnumber_de;
    $invoiceitemdetail1->serialnumber=$serialnumber_de;
    $invoiceitemdetail1->fetch();
?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"></meta>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="../css/w3.css">
        <title>invoiceitemdetail</title>
        <link rel="stylesheet" href="../css/swapp123.css">
        <script src="../js/1.11.0/jquery.min.js">
         </script>
         <script>
            $(document).ready(function(){
             setInterval(function(){cache_clear()},3600000);
             });
             function cache_clear()
            {
             window.location.reload(true);
            }
        </script>
        <script>
            var data = {};
            $(document).ready(function() {
            $('input[type="submit"]').on('click', function() {
            resetErrors();
            var url = '../ip_controller/invoiceitemdetail_action.php';
            $.each($('form input, form select'), function(i, v) {
            if (v.type !== 'submit') {
            data[v.name] = v.value;
            //data['btn']=$('input[type="submit"]').val();
            data['btn']=document.activeElement.getAttribute('value');
            }
            }); //end each
            $.ajax({
            dataType: 'json',
            type: 'POST',
            url: url,
            data: data,
            success: function(resp) {
            if (resp === true) {
            //successful validation
            data['btn']=$('input[type="submit"]').val();
            $('form').submit();
            console.log('submitted');
            return false;
            } else {
            $.each(resp, function(i, v) {
            console.log(i + " => " + v); // view in console for error messages
            var msg = '<label class="error" for="'+i+'">'+v+'</label>';
            $('input[name="' + i + '"], select[name="' + i + '"]').addClass('').after(msg);
            });
            var keys = Object.keys(resp);
            $('input[name="'+keys[0]+'"]').focus();
            }
            return false;
            },
            error: function() {
            console.log('there was a problem checking the fields');
            }
            });
            return false;
            });
            });
            function resetErrors() {
            $('form input, form select').removeClass('inputTxtError');
            $('label.error').remove();
            }
        </script>
        <link rel="stylesheet" href="../css/ui/1.11.4/themes/smoothness/jquery-ui.css">
        <script src="..//js/jquery-1.10.2.js"></script>
        <script src="..//js/ui/1.11.4/jquery-ui.js"></script>
        <script>
            $(function()
            {
                $("#itemcodetextcombo").autocomplete({
                source: 'item_search.php',
                minLength:1,
                delay:200,
                delay:200,
                autoFocus:true,
                autoselect:true,
                select:function(event,ui)
                {var v = ui.item.value;
                 var i = ui.item.id;
                $('#itemcode').val(i);
                this.value = v;
                return false;},
                change:function (event, ui) {
                if (ui.item === null) {
                $('#itemcode').val('');
                }
           }
                });
            });
        </script>
        <script>
<script>
            function qtycal()
            {
                var quantity = Number(document.getElementById("quantity").value);
                var rate = Number(document.getElementById("rate").value);
                var gstrate = Number(document.getElementById("gstrate").value);
                if (salequantity == "")
                    salequantity = 0;
                if (salerate == "")
                    salerate = 0; 
                if (gstrate == "")
                    sgstrate = 0;
                if (gstrate == "")
                    cgstrate = 0;            
                
                var amount=0;
                var taxableamount=0;
                var sgstamount=0;
                var cgstamount=0;
                var totaltaxamount=0;
                var grossamount=0;
                totaltaxrate = gstrate;
                if (totaltaxrate>0)
                {
                    sgstrate=totaltaxrate/2;
                    cgstrate=totaltaxrate/2;
                }
                taxableamount = Number((salerate*salequantity).toFixed(2));
                
                sgstamount = Number((taxableamount*sgstrate/100).toFixed(2));
                cgstamount = Number((taxableamount*cgstrate/100).toFixed(2));
                totaltaxamount = sgstamount+cgstamount;
                grossamount = taxableamount+totaltaxamount;
                if (!isNaN(amount)) 
                { 
                    document.getElementById('amount').value = taxableamount;
                }
                if (!isNaN(sgstamount)) 
                { 
                    document.getElementById('sgstamount').value = sgstamount;
                } 
                if (!isNaN(cgstamount)) 
                { 
                    document.getElementById('cgstamount').value = cgstamount;
                } 
                if (!isNaN(totaltaxamount)) 
                { 
                    document.getElementById('totaltaxamount').value = totaltaxamount;
                } 
                if (!isNaN(grossamount)) 
                { 
                    document.getElementById('amount').value = grossamount;
                } 
            }
        </script>
        </script>
    </head>
    <body>
        <nav "w3-container">
            <ul class="navbar">
                <li><a class="navbar" href="../mis/entitymenu.php">Entity Menu</a><br/>
                <?php
                    $flag_en = fnEncrypt('Query');
                    echo '<li><a class="navbar" href="../ip_view/invoiceitemdetail.php">New invoiceitemdetail   </a>';
                    echo '<li><a class="navbar" href="../ip_view/invoiceitemdetail.php?flag='.$flag_en.'">Find invoiceitemdetail   </a>';
                    echo '<li><a style="color:#f48" class="navbar" href="../../../../../sqlproc/logout.php">Log Out</a><br/>';
                ?>
            </ul>
        </nav>
        <article class="w3-container">


<?php
    echo '<section>';
    echo '<form method="post" action="../ip_controller/invoiceitemdetail_action.php">';
    echo '<div style="width:250px;float:left">';
    echo '<table border="0" >';
    echo '<tr>';
    echo '<td></td>';
    echo '</tr>';
    echo '<img src="../img/createimage.php?name=invoiceitemdetail&width=251&size=14&r=150&g=0&b=0&r1=255&g1=230&b1=0"></br></br>';
    if ($flag_de == 'Query')
    {
        echo '<img src="../img/createimage.php?name=Find Records&width=201&size=12&r=255&g=255&b=255&r1=0&g1=150&b1=0">';
    }
    elseif ($flag_de == 'Display' and $_SESSION['responsibilitycode']==$alterresponsibilityid )
    {
       echo '<img src="../img/createimage.php?name=Change/Delete Record&width=201&size=12&r=255&g=255&b=255&r1=0&g1=150&b1=0">';
    }
    elseif ($invoiceitemdetail1->found == false)
    {
       echo '<img src="../img/createimage.php?name=New Record Entry&width=201&size=12&r=255&g=255&b=255&r1=0&g1=150&b1=0">';
    }
        //record query parameter
        if ($flag_de == 'Query')
        {
            $invoiceitemdetail1->textbox($fieldname='transactionnumber',$englishlabel='Transaction Number ',$unicodelabel='व्यवहार क्रमांक',$value=$invoiceitemdetail1->transactionnumber,$width=200,$height=30,$align='right',$iscompulsory=True,$isreadonly=False,$found=$invoiceitemdetail1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $invoiceitemdetail1->textcombobox($fieldname='itemcode',$combosearchfield='item',$combocodefield='itemcode',$englishlabel='item Code ',$unicodelabel='आयटम कोड',$value=$invoiceitemdetail1->itemcodetextcombo,$codevalue=$invoiceitemdetail1->itemcode,$width=200,$height=30
            ,$iscompulsory=True,$isreadonly=False,$found=$invoiceitemdetail1->found,$flag=$flag_de,$js='',$isautofocus=false,$searchtextbox='itemcodetextcombo');
        }
        //new record
        elseif ($invoiceitemdetail1->found == false)
        {
            $invoiceitemdetail1->textbox($fieldname='transactionnumber',$englishlabel='Transaction Number ',$unicodelabel='व्यवहार क्रमांक',$value=$invoiceitemdetail1->transactionnumber,$width=200,$height=30,$align='right',$iscompulsory=True,$isreadonly=False,$found=$invoiceitemdetail1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $invoiceitemdetail1->textbox($fieldname='serialnumber',$englishlabel='Serial Number ',$unicodelabel='अनु क्रमांक',$value=$invoiceitemdetail1->serialnumber,$width=200,$height=30,$align='right',$iscompulsory=True,$isreadonly=False,$found=$invoiceitemdetail1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $invoiceitemdetail1->textcombobox($fieldname='itemcode',$combosearchfield='item',$combocodefield='itemcode',$englishlabel='item Code ',$unicodelabel='आयटम कोड',$value=$invoiceitemdetail1->itemcodetextcombo,$codevalue=$invoiceitemdetail1->itemcode,$width=200,$height=30
            ,$iscompulsory=True,$isreadonly=False,$found=$invoiceitemdetail1->found,$flag=$flag_de,$js='',$isautofocus=false,$searchtextbox='itemcodetextcombo');
            $invoiceitemdetail1->textbox($fieldname='quantity',$englishlabel='Quantity ',$unicodelabel='संख्या',$value=$invoiceitemdetail1->quantity,$width=200,$height=30,$align='right',$iscompulsory=True,$isreadonly=False,$found=$invoiceitemdetail1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $invoiceitemdetail1->textbox($fieldname='rate',$englishlabel='Rate ',$unicodelabel='दर',$value=$invoiceitemdetail1->rate,$width=200,$height=30,$align='right',$iscompulsory=True,$isreadonly=False,$found=$invoiceitemdetail1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $invoiceitemdetail1->textbox($fieldname='amount',$englishlabel='Amount ',$unicodelabel='रक्कम',$value=$invoiceitemdetail1->amount,$width=200,$height=30,$align='right',$iscompulsory=True,$isreadonly=False,$found=$invoiceitemdetail1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $invoiceitemdetail1->textbox($fieldname='gstrate',$englishlabel='GST Rate ',$unicodelabel='जी एस टी दर',$value=$invoiceitemdetail1->gstrate,$width=200,$height=30,$align='right',$iscompulsory=True,$isreadonly=False,$found=$invoiceitemdetail1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $invoiceitemdetail1->textbox($fieldname='cgstamount',$englishlabel='CGST Amount',$unicodelabel='सी जी एस टी रक्कम',$value=$invoiceitemdetail1->cgstamount,$width=200,$height=30,$align='right',$iscompulsory=True,$isreadonly=False,$found=$invoiceitemdetail1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $invoiceitemdetail1->textbox($fieldname='sgstamount',$englishlabel='SGST Amount ',$unicodelabel='एस जी एस टी रक्कम',$value=$invoiceitemdetail1->sgstamount,$width=200,$height=30,$align='right',$iscompulsory=True,$isreadonly=False,$found=$invoiceitemdetail1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $invoiceitemdetail1->textbox($fieldname='igstamount',$englishlabel='IGST Amount ',$unicodelabel='आय जी एस टी रक्कम',$value=$invoiceitemdetail1->igstamount,$width=200,$height=30,$align='right',$iscompulsory=True,$isreadonly=False,$found=$invoiceitemdetail1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $invoiceitemdetail1->textbox($fieldname='ugstamount',$englishlabel='UGST Amount ',$unicodelabel='यु जी एस टी रक्कम',$value=$invoiceitemdetail1->ugstamount,$width=200,$height=30,$align='right',$iscompulsory=True,$isreadonly=False,$found=$invoiceitemdetail1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $invoiceitemdetail1->textbox($fieldname='totalgstamount',$englishlabel='Total GST Amount ',$unicodelabel='एकूण जी एस टी रक्कम',$value=$invoiceitemdetail1->totalgstamount,$width=200,$height=30,$align='right',$iscompulsory=True,$isreadonly=False,$found=$invoiceitemdetail1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $invoiceitemdetail1->textbox($fieldname='itemtotal',$englishlabel='Item Total ',$unicodelabel='एकूण वस्तू',$value=$invoiceitemdetail1->itemtotal,$width=200,$height=30,$align='right',$iscompulsory=True,$isreadonly=False,$found=$invoiceitemdetail1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $invoiceitemdetail1->textbox($fieldname='efectiveitemcost',$englishlabel='Effective Item Cost ',$unicodelabel='प्रभावी आयटम किंमत',$value=$invoiceitemdetail1->efectiveitemcost,$width=200,$height=30,$align='right',$iscompulsory=True,$isreadonly=False,$found=$invoiceitemdetail1->found,$flag=$flag_de,$js='',$isautofocus=false);
        }
        //record found
        elseif ($invoiceitemdetail1->found == true)
        {
            $invoiceitemdetail1->textbox($fieldname='transactionnumber',$englishlabel='Transaction Number ',$unicodelabel='व्यवहार क्रमांक',$value=$invoiceitemdetail1->transactionnumber,$width=200,$height=30,$align='right',$iscompulsory=True,$isreadonly=False,$found=$invoiceitemdetail1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $invoiceitemdetail1->textbox($fieldname='serialnumber',$englishlabel='Serial Number ',$unicodelabel='अनु क्रमांक',$value=$invoiceitemdetail1->serialnumber,$width=200,$height=30,$align='right',$iscompulsory=True,$isreadonly=False,$found=$invoiceitemdetail1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $invoiceitemdetail1->textcombobox($fieldname='itemcode',$combosearchfield='item',$combocodefield='itemcode',$englishlabel='item Code ',$unicodelabel='आयटम कोड',$value=$invoiceitemdetail1->itemcodetextcombo,$codevalue=$invoiceitemdetail1->itemcode,$width=200,$height=30
            ,$iscompulsory=True,$isreadonly=False,$found=$invoiceitemdetail1->found,$flag=$flag_de,$js='',$isautofocus=false,$searchtextbox='itemcodetextcombo');
            $invoiceitemdetail1->textbox($fieldname='quantity',$englishlabel='Quantity ',$unicodelabel='संख्या',$value=$invoiceitemdetail1->quantity,$width=200,$height=30,$align='right',$iscompulsory=True,$isreadonly=False,$found=$invoiceitemdetail1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $invoiceitemdetail1->textbox($fieldname='rate',$englishlabel='Rate ',$unicodelabel='दर',$value=$invoiceitemdetail1->rate,$width=200,$height=30,$align='right',$iscompulsory=True,$isreadonly=False,$found=$invoiceitemdetail1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $invoiceitemdetail1->textbox($fieldname='amount',$englishlabel='Amount ',$unicodelabel='रक्कम',$value=$invoiceitemdetail1->amount,$width=200,$height=30,$align='right',$iscompulsory=True,$isreadonly=False,$found=$invoiceitemdetail1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $invoiceitemdetail1->textbox($fieldname='gstrate',$englishlabel='GST Rate ',$unicodelabel='जी एस टी दर',$value=$invoiceitemdetail1->gstrate,$width=200,$height=30,$align='right',$iscompulsory=True,$isreadonly=False,$found=$invoiceitemdetail1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $invoiceitemdetail1->textbox($fieldname='cgstamount',$englishlabel='CGST Amount',$unicodelabel='सी जी एस टी रक्कम',$value=$invoiceitemdetail1->cgstamount,$width=200,$height=30,$align='right',$iscompulsory=True,$isreadonly=False,$found=$invoiceitemdetail1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $invoiceitemdetail1->textbox($fieldname='sgstamount',$englishlabel='SGST Amount ',$unicodelabel='एस जी एस टी रक्कम',$value=$invoiceitemdetail1->sgstamount,$width=200,$height=30,$align='right',$iscompulsory=True,$isreadonly=False,$found=$invoiceitemdetail1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $invoiceitemdetail1->textbox($fieldname='igstamount',$englishlabel='IGST Amount ',$unicodelabel='आय जी एस टी रक्कम',$value=$invoiceitemdetail1->igstamount,$width=200,$height=30,$align='right',$iscompulsory=True,$isreadonly=False,$found=$invoiceitemdetail1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $invoiceitemdetail1->textbox($fieldname='ugstamount',$englishlabel='UGST Amount ',$unicodelabel='यु जी एस टी रक्कम',$value=$invoiceitemdetail1->ugstamount,$width=200,$height=30,$align='right',$iscompulsory=True,$isreadonly=False,$found=$invoiceitemdetail1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $invoiceitemdetail1->textbox($fieldname='totalgstamount',$englishlabel='Total GST Amount ',$unicodelabel='एकूण जी एस टी रक्कम',$value=$invoiceitemdetail1->totalgstamount,$width=200,$height=30,$align='right',$iscompulsory=True,$isreadonly=False,$found=$invoiceitemdetail1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $invoiceitemdetail1->textbox($fieldname='itemtotal',$englishlabel='Item Total ',$unicodelabel='एकूण वस्तू',$value=$invoiceitemdetail1->itemtotal,$width=200,$height=30,$align='right',$iscompulsory=True,$isreadonly=False,$found=$invoiceitemdetail1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $invoiceitemdetail1->textbox($fieldname='efectiveitemcost',$englishlabel='Effective Item Cost ',$unicodelabel='प्रभावी आयटम किंमत',$value=$invoiceitemdetail1->efectiveitemcost,$width=200,$height=30,$align='right',$iscompulsory=True,$isreadonly=False,$found=$invoiceitemdetail1->found,$flag=$flag_de,$js='',$isautofocus=false);
        }
        echo '<tr>';
        echo '<td><input class="button123" type="hidden" style="font-size:12pt;height:30px" name="transactionnumber" id="transactionnumber" value="'.$transactionnumber_de.'" style="width:300px"></td>';
        echo '<td><input class="button123" type="hidden" style="font-size:12pt;height:30px" name="serialnumber" id="serialnumber" value="'.$serialnumber_de.'" style="width:300px"></td>';
echo '<tr>';
echo '<td><input class="error" type="hidden" style="font-size:12pt;height:30px" name="error" id="error" value="error" style="width:300px"></td>';
echo '</tr>';
        echo '</tr>';
        if (($_SESSION['responsibilitycode']==$addresponsibilityid or $_SESSION['responsibilitycode']==$alterresponsibilityid) and $flag_de=='Query')
        {
            echo '<tr>';
            echo '<td><input class="button123" type="submit" name="btn" value="Display" style="width:100px"></td>';
            echo '</tr>';
        }
        elseif ($_SESSION['responsibilitycode']==$alterresponsibilityid and $invoiceitemdetail1->found==true)
        {
            echo '<tr>';
            echo '<td><input class="button123" type="submit" name="btn" value="Change" style="width:100px"></td>';
            echo '</tr>';
            echo '<tr>';
            echo '<td><input class="button123" type="submit" name="btn" value="Delete" style="width:100px"></td>';
            echo '</tr>';
        }
        elseif (($_SESSION['responsibilitycode']==$addresponsibilityid or $_SESSION['responsibilitycode']==$alterresponsibilityid) and $invoiceitemdetail1->found==false)
        {
            echo '<tr>';
            echo '<td><input class="button123" type="submit" name="btn" value="Add" style="width:100px"></td>';
            echo '</tr>';
        }
        
        echo '</table>';
        echo '</div>';
        echo '</form>';
        echo '</section>';
    ?>
    </article>
    <footer>
    </footer>
    </body>
</html>

