<?php
    //This is generated by Nigade Software Technologies (opc) Private Limited on 12/12/2020 10:34:19 am for PHP
    require_once("../info/phpsqlajax_dbinfo.php");
    require_once("../info/phpgetloginform.php");
    require_once("../info/ncryptdcrypt.php");
    require_once("../info/routine.php");
    require_once("../ip_model/invoiceheader_db_oracle.php");
    $connection=swapp_connection();
    //Addition or Alteration
    $addresponsibilityid=getresponsibilityid($connection,1);
    $alterresponsibilityid=getresponsibilityid($connection,2);
    if (isaccessible($addresponsibilityid)==0 and isaccessible($alterresponsibilityid)==0)
    {
        echo'Communication Error';
        exit;
    }
    $transactionnumber_de = fnDecrypt($_GET['transactionnumber']);
    $flag_de = fnDecrypt($_GET['flag']);
    $invoiceheader1 = new invoiceheader($connection);
    $invoiceheader1->transactionnumber=$transactionnumber_de;
    $invoiceheader1->fetch();
?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"></meta>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="../css/w3.css">
        <title>invoiceheader</title>
        <link rel="stylesheet" href="../css/swapp123.css">
        <script src="../js/1.11.0/jquery.min.js">
         </script>
         <script>
            $(document).ready(function(){
             setInterval(function(){cache_clear()},3600000);
             });
             function cache_clear()
            {
             window.location.reload(true);
            }
        </script>
        <script>
            var data = {};
            $(document).ready(function() {
            $('input[type="submit"]').on('click', function() {
            resetErrors();
            var url = '../ip_controller/invoiceheader_action.php';
            $.each($('form input, form select'), function(i, v) {
            if (v.type !== 'submit') {
            data[v.name] = v.value;
            //data['btn']=$('input[type="submit"]').val();
            data['btn']=document.activeElement.getAttribute('value');
            }
            }); //end each
            $.ajax({
            dataType: 'json',
            type: 'POST',
            url: url,
            data: data,
            success: function(resp) {
            if (resp === true) {
            //successful validation
            data['btn']=$('input[type="submit"]').val();
            $('form').submit();
            console.log('submitted');
            return false;
            } else {
            $.each(resp, function(i, v) {
            console.log(i + " => " + v); // view in console for error messages
            var msg = '<label class="error" for="'+i+'">'+v+'</label>';
            $('input[name="' + i + '"], select[name="' + i + '"]').addClass('').after(msg);
            });
            var keys = Object.keys(resp);
            $('input[name="'+keys[0]+'"]').focus();
            }
            return false;
            },
            error: function() {
            console.log('there was a problem checking the fields');
            }
            });
            return false;
            });
            });
            function resetErrors() {
            $('form input, form select').removeClass('inputTxtError');
            $('label.error').remove();
            }
        </script>
        <link rel="stylesheet" href="../css/ui/1.11.4/themes/smoothness/jquery-ui.css">
        <script src="..//js/jquery-1.10.2.js"></script>
        <script src="..//js/ui/1.11.4/jquery-ui.js"></script>
        <script>
            $(function()
            {
                $("#suppliercodetextcombo").autocomplete({
                source: 'supplier_search.php',
                minLength:1,
                delay:200,
                delay:200,
                autoFocus:true,
                autoselect:true,
                select:function(event,ui)
                {var v = ui.item.value;
                 var i = ui.item.id;
                $('#suppliercode').val(i);
                this.value = v;
                return false;},
                change:function (event, ui) {
                if (ui.item === null) {
                $('#suppliercode').val('');
                }
           }
                });
            });
        </script>
    </head>
    <body>
        <nav "w3-container">
            <ul class="navbar">
                <li><a class="navbar" href="../mis/entitymenu.php">Entity Menu</a><br/>
                <?php
                    $flag_en = fnEncrypt('Query');
                    echo '<li><a class="navbar" href="../ip_view/invoiceheader.php">New invoiceheader   </a>';
                    echo '<li><a class="navbar" href="../ip_view/invoiceheader.php?flag='.$flag_en.'">Find invoiceheader   </a>';
                    echo '<li><a style="color:#f48" class="navbar" href="../../../../../sqlproc/logout.php">Log Out</a><br/>';
                ?>
            </ul>
        </nav>
        <article class="w3-container">


<?php
    echo '<section>';
    echo '<form method="post" action="../ip_controller/invoiceheader_action.php">';
    echo '<div style="width:250px;float:left">';
    echo '<table border="0" >';
    echo '<tr>';
    echo '<td></td>';
    echo '</tr>';
    echo '<img src="../img/createimage.php?name=invoiceheader&width=251&size=14&r=150&g=0&b=0&r1=255&g1=230&b1=0"></br></br>';
    if ($flag_de == 'Query')
    {
        echo '<img src="../img/createimage.php?name=Find Records&width=201&size=12&r=255&g=255&b=255&r1=0&g1=150&b1=0">';
    }
    elseif ($flag_de == 'Display' and $_SESSION['responsibilitycode']==$alterresponsibilityid )
    {
       echo '<img src="../img/createimage.php?name=Change/Delete Record&width=201&size=12&r=255&g=255&b=255&r1=0&g1=150&b1=0">';
    }
    elseif ($invoiceheader1->found == false)
    {
       echo '<img src="../img/createimage.php?name=New Record Entry&width=201&size=12&r=255&g=255&b=255&r1=0&g1=150&b1=0">';
    }
        //record query parameter
        if ($flag_de == 'Query')
        {
            $invoiceheader1->textbox($fieldname='transactionnumber',$englishlabel='Transaction Number ',$unicodelabel='व्यवहार क्रमांक',$value=$invoiceheader1->transactionnumber,$width=200,$height=30,$align='right',$iscompulsory=True,$isreadonly=False,$found=$invoiceheader1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $invoiceheader1->textcombobox($fieldname='suppliercode',$combosearchfield='supplier',$combocodefield='suppliercode',$englishlabel='Supplier Code ',$unicodelabel='पुरवठाकर्ता कोड',$value=$invoiceheader1->suppliercodetextcombo,$codevalue=$invoiceheader1->suppliercode,$width=200,$height=30
            ,$iscompulsory=True,$isreadonly=False,$found=$invoiceheader1->found,$flag=$flag_de,$js='',$isautofocus=false,$searchtextbox='suppliercodetextcombo');
        }
        //new record
        elseif ($invoiceheader1->found == false)
        {
            $invoiceheader1->textbox($fieldname='transactionnumber',$englishlabel='Transaction Number ',$unicodelabel='व्यवहार क्रमांक',$value=$invoiceheader1->transactionnumber,$width=200,$height=30,$align='right',$iscompulsory=True,$isreadonly=False,$found=$invoiceheader1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $invoiceheader1->textbox($fieldname='financialyear',$englishlabel='Financial Year ',$unicodelabel='आर्थिक वर्ष',$value=$invoiceheader1->financialyear,$width=200,$height=30,$align='right',$iscompulsory=True,$isreadonly=False,$found=$invoiceheader1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $invoiceheader1->textbox($fieldname='invoicenumber',$englishlabel='Invoice Number ',$unicodelabel='बील क्रमांक',$value=$invoiceheader1->invoicenumber,$width=200,$height=30,$align='right',$iscompulsory=True,$isreadonly=False,$found=$invoiceheader1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $invoiceheader1->textbox($fieldname='invoicefrefixnumber',$englishlabel='Invoice Prefix Number ',$unicodelabel='बील उपसर्ग क्रमांक',$value=$invoiceheader1->invoicefrefixnumber,$width=200,$height=30,$align='right',$iscompulsory=True,$isreadonly=False,$found=$invoiceheader1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $invoiceheader1->textcombobox($fieldname='suppliercode',$combosearchfield='supplier',$combocodefield='suppliercode',$englishlabel='Supplier Code ',$unicodelabel='पुरवठाकर्ता कोड',$value=$invoiceheader1->suppliercodetextcombo,$codevalue=$invoiceheader1->suppliercode,$width=200,$height=30
            ,$iscompulsory=True,$isreadonly=False,$found=$invoiceheader1->found,$flag=$flag_de,$js='',$isautofocus=false,$searchtextbox='suppliercodetextcombo');
            $invoiceheader1->textbox($fieldname='supplierinvoicenumber',$englishlabel='Supplier Invoice Number ',$unicodelabel='पुरवठादार बील क्रमांक',$value=$invoiceheader1->supplierinvoicenumber,$width=200,$height=30,$align='right',$iscompulsory=True,$isreadonly=False,$found=$invoiceheader1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $invoiceheader1->textbox($fieldname='supplierinvoicedate',$englishlabel='Supplier Invoice date ',$unicodelabel='पुरवठादार बील तारीख',$value=$invoiceheader1->supplierinvoicedate,$width=200,$height=30,$align='left',$iscompulsory=True,$isreadonly=False,$found=$invoiceheader1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $invoiceheader1->textbox($fieldname='supplierinvoicetotal',$englishlabel='Supplier Invoice Total ',$unicodelabel='पुरवठादार बील रक्कम',$value=$invoiceheader1->supplierinvoicetotal,$width=200,$height=30,$align='right',$iscompulsory=True,$isreadonly=False,$found=$invoiceheader1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $invoiceheader1->textbox($fieldname='grossitemtotal',$englishlabel='Gross Item Total ',$unicodelabel='एकूण आयटम',$value=$invoiceheader1->grossitemtotal,$width=200,$height=30,$align='right',$iscompulsory=True,$isreadonly=False,$found=$invoiceheader1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $invoiceheader1->textbox($fieldname='transportation',$englishlabel='Transportation ',$unicodelabel='वाहतूक',$value=$invoiceheader1->transportation,$width=200,$height=30,$align='right',$iscompulsory=True,$isreadonly=False,$found=$invoiceheader1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $invoiceheader1->textbox($fieldname='netinvesment',$englishlabel='Net Investment ',$unicodelabel='निव्वळ गुंतवणूक',$value=$invoiceheader1->netinvesment,$width=200,$height=30,$align='right',$iscompulsory=True,$isreadonly=False,$found=$invoiceheader1->found,$flag=$flag_de,$js='',$isautofocus=false);
        }
        //record found
        elseif ($invoiceheader1->found == true)
        {
            $invoiceheader1->textbox($fieldname='transactionnumber',$englishlabel='Transaction Number ',$unicodelabel='व्यवहार क्रमांक',$value=$invoiceheader1->transactionnumber,$width=200,$height=30,$align='right',$iscompulsory=True,$isreadonly=False,$found=$invoiceheader1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $invoiceheader1->textbox($fieldname='financialyear',$englishlabel='Financial Year ',$unicodelabel='आर्थिक वर्ष',$value=$invoiceheader1->financialyear,$width=200,$height=30,$align='right',$iscompulsory=True,$isreadonly=False,$found=$invoiceheader1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $invoiceheader1->textbox($fieldname='invoicenumber',$englishlabel='Invoice Number ',$unicodelabel='बील क्रमांक',$value=$invoiceheader1->invoicenumber,$width=200,$height=30,$align='right',$iscompulsory=True,$isreadonly=False,$found=$invoiceheader1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $invoiceheader1->textbox($fieldname='invoicefrefixnumber',$englishlabel='Invoice Prefix Number ',$unicodelabel='बील उपसर्ग क्रमांक',$value=$invoiceheader1->invoicefrefixnumber,$width=200,$height=30,$align='right',$iscompulsory=True,$isreadonly=False,$found=$invoiceheader1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $invoiceheader1->textcombobox($fieldname='suppliercode',$combosearchfield='supplier',$combocodefield='suppliercode',$englishlabel='Supplier Code ',$unicodelabel='पुरवठाकर्ता कोड',$value=$invoiceheader1->suppliercodetextcombo,$codevalue=$invoiceheader1->suppliercode,$width=200,$height=30
            ,$iscompulsory=True,$isreadonly=False,$found=$invoiceheader1->found,$flag=$flag_de,$js='',$isautofocus=false,$searchtextbox='suppliercodetextcombo');
            $invoiceheader1->textbox($fieldname='supplierinvoicenumber',$englishlabel='Supplier Invoice Number ',$unicodelabel='पुरवठादार बील क्रमांक',$value=$invoiceheader1->supplierinvoicenumber,$width=200,$height=30,$align='right',$iscompulsory=True,$isreadonly=False,$found=$invoiceheader1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $invoiceheader1->textbox($fieldname='supplierinvoicedate',$englishlabel='Supplier Invoice date ',$unicodelabel='पुरवठादार बील तारीख',$value=$invoiceheader1->supplierinvoicedate,$width=200,$height=30,$align='left',$iscompulsory=True,$isreadonly=False,$found=$invoiceheader1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $invoiceheader1->textbox($fieldname='supplierinvoicetotal',$englishlabel='Supplier Invoice Total ',$unicodelabel='पुरवठादार बील रक्कम',$value=$invoiceheader1->supplierinvoicetotal,$width=200,$height=30,$align='right',$iscompulsory=True,$isreadonly=False,$found=$invoiceheader1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $invoiceheader1->textbox($fieldname='grossitemtotal',$englishlabel='Gross Item Total ',$unicodelabel='एकूण आयटम',$value=$invoiceheader1->grossitemtotal,$width=200,$height=30,$align='right',$iscompulsory=True,$isreadonly=False,$found=$invoiceheader1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $invoiceheader1->textbox($fieldname='transportation',$englishlabel='Transportation ',$unicodelabel='वाहतूक',$value=$invoiceheader1->transportation,$width=200,$height=30,$align='right',$iscompulsory=True,$isreadonly=False,$found=$invoiceheader1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $invoiceheader1->textbox($fieldname='netinvesment',$englishlabel='Net Investment ',$unicodelabel='निव्वळ गुंतवणूक',$value=$invoiceheader1->netinvesment,$width=200,$height=30,$align='right',$iscompulsory=True,$isreadonly=False,$found=$invoiceheader1->found,$flag=$flag_de,$js='',$isautofocus=false);
        }
        echo '<tr>';
        echo '<td><input class="button123" type="hidden" style="font-size:12pt;height:30px" name="transactionnumber" id="transactionnumber" value="'.$transactionnumber_de.'" style="width:300px"></td>';
echo '<tr>';
echo '<td><input class="error" type="hidden" style="font-size:12pt;height:30px" name="error" id="error" value="error" style="width:300px"></td>';
echo '</tr>';
        echo '</tr>';
        if (($_SESSION['responsibilitycode']==$addresponsibilityid or $_SESSION['responsibilitycode']==$alterresponsibilityid) and $flag_de=='Query')
        {
            echo '<tr>';
            echo '<td><input class="button123" type="submit" name="btn" value="Display" style="width:100px"></td>';
            echo '</tr>';
        }
        elseif ($_SESSION['responsibilitycode']==$alterresponsibilityid and $invoiceheader1->found==true)
        {
            echo '<tr>';
            echo '<td><input class="button123" type="submit" name="btn" value="Change" style="width:100px"></td>';
            echo '</tr>';
            echo '<tr>';
            echo '<td><input class="button123" type="submit" name="btn" value="Delete" style="width:100px"></td>';
            echo '</tr>';
        }
        elseif (($_SESSION['responsibilitycode']==$addresponsibilityid or $_SESSION['responsibilitycode']==$alterresponsibilityid) and $invoiceheader1->found==false)
        {
            echo '<tr>';
            echo '<td><input class="button123" type="submit" name="btn" value="Add" style="width:100px"></td>';
            echo '</tr>';
        }

        echo '</table>';
        echo '</div>';
        echo '</form>';
              
        echo '</section>';
    ?>
    </article>
    <footer>
    </footer>
    </body>
</html>

