<?php
    //This is generated by Nigade Software Technologies (opc) Private Limited on 19/05/2021 06:01:48 pm for PHP
    require("../info/phpgetloginview.php");
    include("../info/ncryptdcrypt.php");
    require("../info/routine.php");
    include("../ip_model/concessioncategory_db_oracle.php");
    $connection=swapp_connection();
    $concessioncategory1 = new concessioncategory($connection);
    $concessioncategory1->concessioncategorycode = $_POST["concessioncategorycode"];
    $concessioncategory1->concessioncategorynameeng = $_POST["concessioncategorynameeng"];
    $concessioncategory1->concessioncategorynameuni = $_POST["concessioncategorynameuni"];
    $flag_de = fnDecrypt($_GET['flag']);
if ((($_POST['btn']=='Add' or ($_POST['btn']=='Change')) and $_SESSION['errors']['error']!='submitted'))
    {
    $ret = $concessioncategory1->entryvalidation();
    }
    else
    {
      $ret=0;
    }
    if ($ret!=0)
    {
      $_SESSION['errors']['error'] = $concessioncategory1->invalidmessagetext;
      //This is for ajax requests:
      if(!empty($_SERVER['HTTP_X_REQUESTED_WITH']) &&  strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) == 'xmlhttprequest') 
      {
        echo json_encode($_SESSION['errors']);
        exit;
      }
      //This is when Javascript is turned off:
      echo '<ul>';
      foreach($_SESSION['errors'] as $key => $value)
      {
        echo '<li>' . $value . '</li>';
      }
      echo '</ul>';
      exit;
    }
    elseif ($_SESSION['errors']['error']!='submitted')
    {
      echo json_encode(true);
      unset($_SESSION['errors']['error']);
      $_SESSION['errors']['error'] ='submitted';
      $_SESSION['button'] =$_POST['btn'];
      exit;
    }
  unset($_SESSION['errors']['error']);  
  switch ($_SESSION['button'])
  {
    case 'Add':
      $ret = $concessioncategory1->insert();
      if ($ret==1)
      {
        oci_commit($connection);
        echo '<span class="w3-container" style="background-color:#0a0;color:#ff8;text-align:left;">concessioncategory is added successfully</span></br>';
        echo '<a href="../ip_view/concessioncategory.php">New concessioncategory</a></br>';
      }
      else
      {
        oci_rollback($connection);
        echo '<span style="background-color:#f44;color:#ff8;text-align:left;">'.$concessioncategory1->Get_invalidmessagetext().'</span></br>';
        echo '<button onclick="history.go(-1);">Back </button>';
      }
      break;
    case 'Change':
      $concessioncategory1->concessioncategorycode = $_POST["concessioncategorycode"];
      $ret = $concessioncategory1->update();
      if ($ret==1)
      {
        oci_commit($connection);
        $flag_en = fnEncrypt('Query');
        echo '<span class="w3-container" style="background-color:#0a0;color:#ff8;text-align:left;">concessioncategory is Updated successfully</span></br>';  
        echo '<a href="../ip_view/concessioncategory.php?flag='.$flag_en.'">Find concessioncategory</a></br>';
      }
      else
      {
        oci_rollback($connection);
        echo '<span style="background-color:#f44;color:#ff8;text-align:left;">'.$concessioncategory1->Get_invalidmessagetext().'</span></br>';
        echo '<button onclick="history.go(-1);">Back </button>';
			}
			break;
		case 'Display':
      $concessioncategory1->concessioncategorycode = $_POST["concessioncategorycode"];
      include("../mis/list.php");
      echo '<nav "w3-container">';
      echo '    <ul class="navbar">';
      echo '    <li><a class="navbar" href="../mis/entitymenu.php">Entity Menu</a><br/>';
      $flag_en = fnEncrypt('Query');
      echo '    <li><a class="navbar" href="../ip_view/concessioncategory.php">New concessioncategory</a>';
      echo '    <li><a class="navbar" href="../ip_view/concessioncategory.php?flag='.$flag_en.'">Find concessioncategory</a>';
      echo '<li><a style="color:#f48" class="navbar" href="../../../../../sqlproc/logout.php">Log Out</a><br/>';
      echo '    </ul>';
      echo '  </nav>';
      echo '<section>';
      echo '<table border="0" >';
      echo '<tr>';
      echo '<td><label for="" class="thick">List of concessioncategory</label></td>';
      echo '</tr>';
			$result1 = $concessioncategory1->display();
			if ($concessioncategory1->Get_invalidid()==0)
			{
        $flag_en = fnEncrypt('Display');
				while ($row1 = oci_fetch_array($result1,OCI_ASSOC+OCI_RETURN_NULLS))
				{
					if ($_SESSION['lng']=='English')
					{
            echo '<tr>';
						echo '<td><a href="../ip_view/concessioncategory.php?concessioncategorycode='.fnEncrypt($row1['CONCESSIONCATEGORYCODE']).'&flag='.$flag_en.'">'.$row1['CONCESSIONCATEGORYCODE'].' '.$row1['CONCESSIONCATEGORYNAMEENG'].'</td>';
            echo '</tr>';
					}
					else
					{
            echo '<tr>';
						echo '<td><a href="../ip_view/concessioncategory.php?concessioncategorycode='.fnEncrypt($row1['CONCESSIONCATEGORYCODE']).'&flag='.$flag_en.'">'.$row1['CONCESSIONCATEGORYCODE'].' '.$row1['CONCESSIONCATEGORYNAMEUNI'].'</td>';
            echo '</tr>';
					}
				}	
			}
			else
			{
				echo '<span style="background-color:#f44;color:#ff8;text-align:left;">'.$concessioncategory1->Get_invalidmessagetext().'</span></br>';
        echo '<button onclick="history.go(-1);">Back </button>';
			}
			break;
		case 'Delete':
      $concessioncategory1->concessioncategorycode = $_POST["concessioncategorycode"];
			$ret = $concessioncategory1->delete();
			if ($ret == 1)
			{
				oci_commit($connection);
        $flag_en = fnEncrypt('Query');
				echo '<span class="w3-container" style="background-color:#0a0;color:#ff8;text-align:left;">concessioncategory is Deleted Successfully</span></br>';
				echo '<a href="../ip_view/concessioncategory.php?flag='.$flag_en.'">Find concessioncategory</a></br>';
			}
			else
			{
				oci_rollback($connection);
				echo '<span style="background-color:#f44;color:#ff8;text-align:left;">'.$concessioncategory1->Get_invalidmessagetext().'</span></br>';
				echo '<a href="../ip_view/concessioncategory.php">Find concessioncategory</a></br>';
        echo '<button onclick="history.go(-1);">Back </button>';
			}
			break;
		default:
			echo 'Communication Error';
      echo '<button onclick="history.go(-1);">Back </button>';
			break;
	}

