<?php
    //This is generated by Swapp Software Application on 01/02/2020 07:29:54 pm for PHP
    require_once("../info/phpsqlajax_dbinfo.php");
    require_once("../info/phpgetloginview.php");
    require_once("../info/routine.php");
    $connection =swapp_connection();
    $searchTerm = $_GET['term'];
    if (preg_match('/^[0-9]*$/', $searchTerm))
    {
    }
    elseif (strlen($searchTerm)<3 and $searchTerm != '**')
    {
        exit;
    }
   if ($searchTerm == '**')
   {
       $query = "select ACCOUNTCODE,
       ACCOUNTNAMEUNI,
       ACCOUNTNAMEENG
       from nst_nasaka_FINANCE.ACCOUNTHEAD where rownum <= 10";
   }
   else
   {
       $query = "select ACCOUNTCODE,
       ACCOUNTNAMEUNI,
       ACCOUNTNAMEENG
       from nst_nasaka_FINANCE.ACCOUNTHEAD where (upper(ACCOUNTNAMEENG) like upper('%".$searchTerm."%')
       or ACCOUNTNAMEUNI like '%".$searchTerm."%'
       or to_char(ACCOUNTCODE) like '".$searchTerm."') and rownum <= 10";
   }
   $result = oci_parse($connection, $query); $r = oci_execute($result);
   $r = oci_execute($result);
   while ($row = oci_fetch_array($result,OCI_ASSOC+OCI_RETURN_NULLS))
   {
       $id = $row['ACCOUNTCODE'];
       if ($_SESSION['lng'] == "English")
       {
           $name = $row['ACCOUNTNAMEENG'];
       }
       else
       {
           $name = $row['ACCOUNTNAMEUNI'];
       }
       $data[] = array( 
           'id' => $id
           ,'label' => $name
           ,'value' => $name
           );
   }
   //return json data
   echo json_encode($data);
?>