<?php
    //This is generated by Swapp Software Application on 25/05/2019 06:16:44 PM for PHP
    require_once("../info/phpsqlajax_dbinfo.php");
    require_once("../info/phpgetloginform.php");
    require_once("../info/ncryptdcrypt.php");
    require_once("../info/routine.php");
    require_once("../ip_model/caneseedcategory_db_oracle.php");
    //Addition or Alteration
    $addresponsibilityid=123457423;
    $alterresponsibilityid=123457740;
    if (isaccessible($addresponsibilityid)==0 and isaccessible($alterresponsibilityid)==0)
    {
        echo'Communication Error';
        exit;
    }
    $caneseedcategorycode_de = fnDecrypt($_GET['caneseedcategorycode']);
    $flag_de = fnDecrypt($_GET['flag']);
    $connection=swapp_connection();
?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"></meta>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="../css/w3.css">
        <title>Contract</title>
        <link rel="stylesheet" href="../css/swapp123.css">
        <script src="../js/1.11.0/jquery.min.js">
         </script>
         <script>
            $(document).ready(function(){
             setInterval(function(){cache_clear()},3600000);
             });
             function cache_clear()
            {
             window.location.reload(true);
            }
        </script>
        <link rel="stylesheet" href="../css/ui/1.11.4/themes/smoothness/jquery-ui.css">
        <script src="..//js/jquery-1.10.2.js"></script>
        <script src="..//js/ui/1.11.4/jquery-ui.js"></script>
    </head>
    <body>
        <nav "w3-container">
            <ul class="navbar">
                <li><a class="navbar" href="../mis/entitymenu.php">Entity Menu</a><br/>
                <?php
                    $flag_en = fnEncrypt('Query');
                    echo '<li><a class="navbar" href="../ip_view/caneseedcategory.php">New Caneseedcategory   </a>';
                    echo '<li><a class="navbar" href="../ip_view/caneseedcategory.php?flag='.$flag_en.'">Find Caneseedcategory   </a>';
                    echo '<li><a  class="navbar" href="../../../../../sqlproc/logout.php">Log Out</a><br/>';
                ?>
            </ul>
        </nav>
        <article class="w3-container">


<?php
    $caneseedcategory1 = new caneseedcategory($connection);
    $caneseedcategory1->caneseedcategorycode=$caneseedcategorycode_de;
    $caneseedcategory1->fetch();
    echo '<section>';
    echo '<form method="post" action="../ip_controller/caneseedcategory_action.php">';
    echo '<table border="0" >';
    echo '<tr>';
    echo '<td></td>';
    echo '</tr>';
    echo '<img src="../img/createimage.php?name=Caneseedcategory&width=251&size=14&r=150&g=0&b=0&r1=255&g1=230&b1=0"></br></br>';
    if ($flag_de == 'Query')
    {
        echo '<img src="../img/createimage.php?name=Find Records&width=201&size=12&r=255&g=255&b=255&r1=0&g1=150&b1=0">';
    }
    elseif ($flag_de == 'Display' and $_SESSION['responsibilitycode']==$alterresponsibilityid )
    {
       echo '<img src="../img/createimage.php?name=Change/Delete Record&width=201&size=12&r=255&g=255&b=255&r1=0&g1=150&b1=0">';
    }
    elseif ($caneseedcategory1->found == false)
    {
       echo '<img src="../img/createimage.php?name=New Record Entry&width=201&size=12&r=255&g=255&b=255&r1=0&g1=150&b1=0">';
    }
        if ($caneseedcategory1->found == true or $flag_de == 'Query')
        {
            if ($_SESSION['lng']=="English")
            {
                echo '<tr>';
                echo '<td><label for="caneseedcategorycode" class="thick">Caneseed Category Code</label></td>';
                echo '</tr>';
            }
            else
            {
                echo '<tr>';
                echo '<td><label for="caneseedcategorycode" class="thick">ऊस बेणे कोड</label></td>';
                echo '</tr>';
            }
            echo '<tr>';
            echo '<td><input type="text" readonly="readonly" tabindex="-1" style="font-size:12pt;height:30px" name="caneseedcategorycode" id="caneseedcategorycode" value="'.$caneseedcategory1->caneseedcategorycode.'" style="width:300px"></td>';
            echo '</tr>';
        }
        if ($caneseedcategory1->found == false or $caneseedcategory1->found == true or $flag_de == 'Query')
        {
            if ($_SESSION['lng']=="English")
            {
                echo '<tr>';
                echo '<td><label for="caneseedcategorynameeng" class="thick">Caneseed Category Name (English)</label></td>';
                echo '</tr>';
            }
            else
            {
                echo '<tr>';
                echo '<td><label for="caneseedcategorynameeng" class="thick">ऊस बेणे नाव (इंग्रजी)</label></td>';
                echo '</tr>';
            }
            echo '<tr>';
            echo '<td><input type="text" style="font-size:12pt;height:30px" name="caneseedcategorynameeng" id="caneseedcategorynameeng" value="'.$caneseedcategory1->caneseedcategorynameeng.'" style="width:300px"></td>';
            echo '<td><label for="caneseedcategorynameeng">*</label></td>';
            echo '</tr>';
        }
        if ($caneseedcategory1->found == false or $caneseedcategory1->found == true or $flag_de == 'Query')
        {
            if ($_SESSION['lng']=="English")
            {
                echo '<tr>';
                echo '<td><label for="caneseedcategorynameuni" class="thick">Caneseed Category Name (Unicode)</label></td>';
                echo '</tr>';
            }
            else
            {
                echo '<tr>';
                echo '<td><label for="caneseedcategorynameuni" class="thick">ऊस बेणे (मराठी)</label></td>';
                echo '</tr>';
            }
            echo '<tr>';
            echo '<td><input type="text" style="font-size:12pt;height:30px" name="caneseedcategorynameuni" id="caneseedcategorynameuni" value="'.$caneseedcategory1->caneseedcategorynameuni.'" style="width:300px"></td>';
            echo '<td><label for="caneseedcategorynameuni">*</label></td>';
            echo '</tr>';
        }
        echo '<tr>';
        echo '<td><input class="button123" type="hidden" style="font-size:12pt;height:30px" name="caneseedcategorycode" id="caneseedcategorycode" value="'.$caneseedcategorycode_de.'" style="width:300px"></td>';
        echo '</tr>';
        if (($_SESSION['responsibilitycode']==$addresponsibilityid or $_SESSION['responsibilitycode']==$alterresponsibilityid) and $flag_de=='Query')
        {
            echo '<tr>';
            echo '<td><input class="button123" type="submit" name="btn" value="Display" style="width:100px"></td>';
            echo '</tr>';
        }
        elseif ($_SESSION['responsibilitycode']==$alterresponsibilityid and $caneseedcategory1->found==true)
        {
            echo '<tr>';
            echo '<td><input class="button123" type="submit" name="btn" value="Change" style="width:100px"></td>';
            echo '</tr>';
            echo '<tr>';
            echo '<td><input class="button123" type="submit" name="btn" value="Delete" style="width:100px"></td>';
            echo '</tr>';
        }
        elseif (($_SESSION['responsibilitycode']==$addresponsibilityid or $_SESSION['responsibilitycode']==$alterresponsibilityid) and $caneseedcategory1->found==false)
        {
            echo '<tr>';
            echo '<td><input class="button123" type="submit" name="btn" value="Add" style="width:100px"></td>';
            echo '</tr>';
        }
        echo '</table>';
        echo '</form>';
        echo '</section>';
    ?>
    </article>
    <footer>
    </footer>
    </body>
</html>

