<?php
    //This is generated by Swapp Software Application on 06/06/2019 11:50:16 AM for PHP
    require_once("../info/phpsqlajax_dbinfo.php");
    require_once("../info/phpgetloginview.php");
    require_once("../info/routine.php");
    $connection =swapp_connection();
    $searchTerm = $_GET['term'];
    $owner = $_GET['owner'];
    $tablename = $_GET['tablename'];
    $combotableowner = $_GET['combotableowner'];
    if ($combotableowner == '')
    {
        $combotableowner = $owner;
    }
    if (preg_match('/^[0-9]*$/', $searchTerm))
    {
    }
    elseif ((strlen($searchTerm)<3) and $searchTerm != '**')
    {
        exit;
    }
   if ($searchTerm == '**')
   {
       $query = "SELECT owner, table_name FROM all_tables where upper(owner)=upper('".$combotableowner."') and rownum <= 10";
   }
   else
   {
       $query = "SELECT owner, table_name FROM all_tables where upper(owner)=upper('".$combotableowner."')
       and upper(table_name) like upper('%".$searchTerm."%') and rownum <= 10";
   }
   $result = oci_parse($connection, $query); $r = oci_execute($result);
   $r = oci_execute($result);
   while ($row = oci_fetch_array($result,OCI_ASSOC+OCI_RETURN_NULLS))
   {
        $query1 = "select max(pkcol) as pkcol,max(coleng) as coleng,max(coluni) as coluni
        from (
        select case when col.column_id=1 then col.column_name else null end as pkcol
        ,case when col.column_name like '%ENG%' then col.column_name else null end as coleng
        ,case when col.column_name like '%UNI%' then col.column_name else null end as coluni
        from sys.dba_tab_columns col
        inner join sys.dba_tables t on col.owner = t.owner 
                                    and col.table_name = t.table_name
        where col.owner = upper('".$row['OWNER']."')
        and col.table_name = upper('".$row['TABLE_NAME']."')
        and (col.column_id=1 or col.column_name like '%ENG%' or col.column_name like '%UNI%')
        order by col.column_id)";
        $id = $row['TABLE_NAME'];
        $name = $row['TABLE_NAME'];
        $result1 = oci_parse($connection, $query1); $r = oci_execute($result1);
        $r1 = oci_execute($result1);
        if ($row1 = oci_fetch_array($result1,OCI_ASSOC+OCI_RETURN_NULLS))
        {
            $pkcol=$row1['PKCOL'];
            $coleng=$row1['COLENG'];
            $coluni=$row1['COLUNI'];
        }
        else
        {
            $pkcol='';
            $coleng='';
            $coluni='';
        }
        $data[] = array( 
           'id' => $id
           ,'label' => $name
           ,'value' => $name
           ,'pkcol' => $pkcol
           ,'coleng' => $coleng
           ,'coluni' => $coluni
           ,'comowner' => strtoupper($combotableowner)
           );
   }
   //return json data
   echo json_encode($data);
?>

