<?php
    //This is generated by Swapp Software Application on 29/09/2019 04:09:05 PM for PHP
    require_once("../info/phpsqlajax_dbinfo.php");
    require_once("../info/phpgetloginform.php");
    require_once("../info/ncryptdcrypt.php");
    require_once("../info/routine.php");
    require_once("../ip_model/farmer_db_oracle.php");
    require_once("../ip_model/farmeradhikarpatra_db_oracle.php");
    //Agriculute Addition or Alteration
    if ($_SESSION['responsibilitycode']==123457423 or $_SESSION['responsibilitycode']==123457740)
    {
        $addresponsibilityid=123457423;
        $alterresponsibilityid=123457740;
    }
    elseif ($_SESSION['responsibilitycode']==123457740 or $_SESSION["responsibilitycode"] == 123980930 or $_SESSION["responsibilitycode"] == 123981247 or $_SESSION["responsibilitycode"] == 123981564)
    {
        $addresponsibilityid=$_SESSION['responsibilitycode'];
        if ($_SESSION["responsibilitycode"] == 123980930)
        {
            $alterresponsibilityid=0;
        }
        else
        {
            $alterresponsibilityid=$_SESSION['responsibilitycode'];
        }
    }
    //Farmer Billing Addition or Alteration
    elseif ($_SESSION['responsibilitycode']==123476175 or $_SESSION['responsibilitycode']==123476492)
    {
        $addresponsibilityid=123476175;
        $alterresponsibilityid=123476492;
    }
    //Weighbridge Addition or Alteration
    elseif ($_SESSION['responsibilitycode']==123477760 or $_SESSION['responsibilitycode']==123478077)
    {
        $addresponsibilityid=123477760;
        $alterresponsibilityid=0;
    }
    //Smartcard
    elseif ($_SESSION['responsibilitycode']==123986642)
    {
        $addresponsibilityid=0;
        $alterresponsibilityid=123986642;
    }

    if ($addresponsibilityid!=0 and $alterresponsibilityid!=0)
    {
        if (isaccessible($addresponsibilityid)==0 and isaccessible($alterresponsibilityid)==0)
        {
            echo'Communication Error';
            exit;
        }
    }
    elseif ($addresponsibilityid!=0)
    {
        if (isaccessible($addresponsibilityid)==0)
        {
            echo'Communication Error';
            exit;
        }
    }
    elseif ($alterresponsibilityid!=0)
    {
        if (isaccessible($alterresponsibilityid)==0)
        {
            echo'Communication Error';
            exit;
        }
    }
    $farmercode_de = fnDecrypt($_GET['farmercode']);
    $flag_de = fnDecrypt($_GET['flag']);
    $connection=swapp_connection();
    $farmer1 = new farmer($connection);
    $farmer1->farmercode=$farmercode_de;
    $farmer1->fetch();
?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"></meta>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="../css/w3.css">
        <title>Contract</title>
        <link rel="stylesheet" href="../css/swapp123.css">
        <script src="../js/1.11.0/jquery.min.js">
         </script>
         <script>
            $(document).ready(function(){
             setInterval(function(){cache_clear()},3600000);
             });
             function cache_clear()
            {
             window.location.reload(true);
            }
        </script>
        <link rel="stylesheet" href="../css/ui/1.11.4/themes/smoothness/jquery-ui.css">
        <script src="..//js/jquery-1.10.2.js"></script>
        <script src="..//js/ui/1.11.4/jquery-ui.js"></script>
        <script>
            $(function()
            {
                $("#farmernameuni").autocomplete({
                source: function(request, response) {
                    $.getJSON("contractornamemarathitoenglish_search.php", { term: request.term,contractornameeng:$('#farmernameeng').val()}, 
                            response);
                },
                minLength:1,
                delay:200,
                autoFocus:true,
                autoselect:true,
                select:function(event,ui)
                {var v = ui.item.value;
                 var u = ui.item.univalue;
                $('#farmernameeng').val(v);
                this.value=u;
                return false;}
                });
            });
        </script>
        <script>
            $(function()
            {
                $("#farmernameeng").autocomplete({
                source: function(request, response) {
                    $.getJSON("contractornameenglishtomarathi_search.php", { term: request.term,contractornameuni:$('#farmernameuni').val(),isfarmer:1}, 
                            response);
                },
                minLength:1,
                delay:200,
                autoFocus:true,
                autoselect:true,
                select:function(event,ui)
                {var v = ui.item.value;
                    var e = ui.item.engvalue;
                    var d = ui.item.dupfarmernameeng;
                $('#farmernameuni').val(v);
                $('#dupfarmernameeng').val(d);
                this.value=e;
                return false;}
                });
            });
        </script>
        <script>
        $(function () 
        {
            $('#valueToSearch').on('keyup',function(){
            //Your ajax call will go Here
            $.ajax({
                url:senddata.php, // separate file for search
                data : {
                q : $('#valueToSearch').val().trim()
                },
                method:'POST',
                dataType:'json',
                success:function(data){
                    $('#fetch_record').html(data);
                },
                error:function(data){
                alert("something has gone wrong");
                }
            });
            });
            });
        </script>
        <script>
            $(function()
            {
                $("#village").autocomplete({
                source: function(request, response) {
                    $.getJSON("village_search.php", { term: request.term,farmername:$('#farmernameeng').val()}, 
                            response);
                },
                minLength:1,
                delay:200,
                select:function(event,ui)
                {var v = ui.item.value;
                 var i = ui.item.id;
                 var d= ui.item.dupfarmername;
                $('#villagecode').val(i);
                this.value = v;
                $('#dupfarmernameeng').val(d);
                return false;}
                });
            });
        </script>
        <script>
            $(function()
            {
                $("#bankbranch").autocomplete({
                source: 'bankbranch_search.php',
                minLength:1,
                delay:200,
                select:function(event,ui)
                {var v = ui.item.value;
                 var i = ui.item.id;
                 var ifsc=ui.item.ifsc;
                $('#bankbranchcode').val(i);
                $('#ifsc').val(ifsc);
                this.value = v;
                return false;}
                });
            });
        </script>
    </head>
    <body>
        <nav "w3-container">
            <ul class="navbar">
                <li><a class="navbar" href="../mis/entitymenu.php">Entity Menu</a><br/>
                <?php
                    $flag_en = fnEncrypt('Query');
                    echo '<li><a class="navbar" href="../ip_view/farmer.php">New farmer   </a>';
                    echo '<li><a class="navbar" href="../ip_view/farmer.php?flag='.$flag_en.'">Find farmer   </a>';
                    $cnt=$farmer1->adhikarpatracount();
                    if ($farmer1->found==true && $cnt==0)
                    {
                        echo '<li><a class="navbar" href="../ip_view/farmeradhikarpatra.php?farmercode='.fnEncrypt($farmer1->farmercode).'">New Adhikarpatra</a>';
                    }
                    echo '<li><a  class="navbar" href="../../../../../sqlproc/logout.php">Log Out</a><br/>';
                    $st=(string)$farmer1->farmercode;
                    if ($st!='')
                    echo '<img src="../memberphoto/'.$st.'_0001.jpg'.'" width="250" height="250">'; 
                ?>
            </ul>
        </nav>
        <article class="w3-container">


<?php
    echo '<section>';
    echo '<form method="post" action="../ip_controller/farmer_action.php">';
    echo '<div style="width:300px;float:left">';
    echo '<table border="0" >';
    echo '<tr>';
    echo '<td></td>';
    echo '</tr>';
    if ($farmer1->verified==1)
        echo '<img src="../img/createimage.php?name=Verified Farmer&width=251&size=14&r=150&g=0&b=0&r1=255&g1=230&b1=0"></br></br>';
    else
        echo '<img src="../img/createimage.php?name=Farmer&width=251&size=14&r=150&g=0&b=0&r1=255&g1=230&b1=0"></br></br>';                    
    if ($flag_de == 'Query')
    {
        echo '<img src="../img/createimage.php?name=Find Records&width=201&size=12&r=255&g=255&b=255&r1=0&g1=150&b1=0">';
    }
    elseif ($flag_de == 'Display' and $_SESSION['responsibilitycode']==$alterresponsibilityid )
    {
       echo '<img src="../img/createimage.php?name=Change/Delete Record&width=201&size=12&r=255&g=255&b=255&r1=0&g1=150&b1=0">';
    }
    elseif ($farmer1->found == false)
    {
       echo '<img src="../img/createimage.php?name=New Record Entry&width=201&size=12&r=255&g=255&b=255&r1=0&g1=150&b1=0">';
    }
                               
        //record query parameter
        if ($flag_de == 'Query')
        {
            $farmer1->textbox($fieldname='farmercode',$englishlabel='Farmer Code',$unicodelabel='शेतकरी कोड',$value=$farmer1->farmercode,$width=270,$height=30,$align='right',$iscompulsory=False,$isreadonly=True,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $farmer1->textbox($fieldname='farmernameuni',$englishlabel='Farmer Name (Unicode)',$unicodelabel='शेतकरी नाव (मराठी)',$value=$farmer1->farmernameuni,$width=270,$height=30,$align='left',$iscompulsory=True,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $farmer1->textbox($fieldname='farmernameeng',$englishlabel='Farmer Name (English)',$unicodelabel='शेतकरी नाव (इंग्रजी)',$value=$farmer1->farmernameeng,$width=270,$height=30,$align='left',$iscompulsory=True,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
            if ($_SESSION['responsibilitycode']==123476175 or $_SESSION['responsibilitycode']==123476492)
            {
                $farmer1->textbox($fieldname='farmernamebankeng',$englishlabel='Bank Farmer Name (English)',$unicodelabel='बँक शेतकरी नाव (इंग्रजी)',$value=$farmer1->farmernamebankeng,$width=270,$height=30,$align='left',$iscompulsory=False,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
                $farmer1->textbox($fieldname='farmernamebankuni',$englishlabel='Bank Farmer Name (Unicode)',$unicodelabel='बँक शेतकरी नाव (मराठी)',$value=$farmer1->farmernamebankuni,$width=270,$height=30,$align='left',$iscompulsory=False,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
            }
            $farmer1->textcombobox($fieldname='villagecode',$combosearchfield='village',$combocodefield='villagecode',$englishlabel='Village',$unicodelabel='गाव',$value=$farmer1->village,$codevalue=$farmer1->villagecode,$width=270,$height=30,$iscompulsory=True,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $farmer1->listcombo($fieldname='farmercategorycode',$connection,$sourcetable='farmercategory',$combocodefield='farmercategorycode',$codevalue=$farmer1->farmercategorycode,$nameeng='farmercategorynameeng',$nameuni='farmercategorynameuni',$englishlabel='Farmer Category',$unicodelabel='शेतकरी प्रकार',$width=270,$height=30,$iscompulsory=True,$isreadonly=False,$found=$farmer1->found,$isautofocus=false);
            $farmer1->textbox($fieldname='mobilenumber',$englishlabel='Mobile Number',$unicodelabel='मोबाईल नंबर',$value=$farmer1->mobilenumber,$width=270,$height=30,$align='right',$iscompulsory=False,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
            //$farmer1->textbox($fieldname='mobilenumber2',$englishlabel='Mobile Number 2',$unicodelabel='मोबाईल नंबर २',$value=$farmer1->mobilenumber2,$width=270,$height=30,$align='right',$iscompulsory=False,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $farmer1->textbox($fieldname='adharnumber',$englishlabel='Adhar Number',$unicodelabel='आधार नंबर',$value=$farmer1->adharnumber,$width=270,$height=30,$align='right',$iscompulsory=False,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
            if ($_SESSION['responsibilitycode']==123476175 or $_SESSION['responsibilitycode']==123476492)
            {
                $farmer1->textcombobox($fieldname='bankbranchcode',$combosearchfield='bankbranch',$combocodefield='bankbranchcode',$englishlabel='Bank Branch',$unicodelabel='बँक शाखा',$value=$farmer1->bankbranch,$codevalue=$farmer1->bankbranchcode,$width=270,$height=30,$iscompulsory=False,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
                $farmer1->textbox($fieldname='ifsc',$englishlabel='IFSC Code',$unicodelabel='IFSC Code',$value=$farmer1->ifsc,$width=270,$height=30,$align='left',$iscompulsory=False,$isreadonly=true,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
                $farmer1->textbox($fieldname='accountnumber',$englishlabel='Account Number',$unicodelabel='खाते क्रमांक',$value=$farmer1->accountnumber,$width=270,$height=30,$align='left',$iscompulsory=False,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
            }
        }
        //new record
        elseif ($farmer1->found == false)
        {
            if ($_SESSION['responsibilitycode']==123457740 or $_SESSION["responsibilitycode"] == 123980930 or $_SESSION["responsibilitycode"] == 123981247 or $_SESSION["responsibilitycode"] == 123981564)
            {
                $farmer1->textbox($fieldname='farmernameuni',$englishlabel='Farmer Name (Unicode)',$unicodelabel='शेतकरी नाव (मराठी)',$value=$farmer1->farmernameuni,$width=270,$height=30,$align='left',$iscompulsory=True,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=true,$isplacebolder=true,$placeholder='शेवटी * दाबल्यावर नाव इंग्रजीत होईल');
                $farmer1->textbox($fieldname='farmernameeng',$englishlabel='Farmer Name (English)',$unicodelabel='शेतकरी नाव (इंग्रजी)',$value=$farmer1->farmernameeng,$width=270,$height=30,$align='left',$iscompulsory=True,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false,$isplacebolder=true,$placeholder='नावानंतर + दाबल्यावर राव,सिंग..');
                $farmer1->textcombobox($fieldname='villagecode',$combosearchfield='village',$combocodefield='villagecode',$englishlabel='Village',$unicodelabel='गाव',$value=$farmer1->village,$codevalue=$farmer1->villagecode,$width=270,$height=30,$iscompulsory=True,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
                $farmer1->listcombo($fieldname='farmercategorycode',$connection,$sourcetable='farmercategory',$combocodefield='farmercategorycode',$codevalue=$farmer1->farmercategorycode,$nameeng='farmercategorynameeng',$nameuni='farmercategorynameuni',$englishlabel='Farmer Category',$unicodelabel='शेतकरी प्रकार',$width=270,$height=30,$iscompulsory=True,$isreadonly=False,$found=$farmer1->found,$isautofocus=false);
                $farmer1->textbox($fieldname='mobilenumber',$englishlabel='Mobile Number',$unicodelabel='मोबाईल नंबर',$value=$farmer1->mobilenumber,$width=270,$height=30,$align='right',$iscompulsory=False,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
                //$farmer1->textbox($fieldname='mobilenumber2',$englishlabel='Mobile Number 2',$unicodelabel='मोबाईल नंबर २',$value=$farmer1->mobilenumber2,$width=270,$height=30,$align='right',$iscompulsory=False,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
                $farmer1->textbox($fieldname='adharnumber',$englishlabel='Adhar Number',$unicodelabel='आधार नंबर',$value=$farmer1->adharnumber,$width=270,$height=30,$align='right',$iscompulsory=False,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
                $farmer1->textbox($fieldname='pannumber',$englishlabel='PAN Number',$unicodelabel='पॅन नंबर',$value=$farmer1->pannumber,$width=270,$height=30,$align='right',$iscompulsory=False,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
                $farmer1->textbox($fieldname='birthdate',$englishlabel='Birthdate',$unicodelabel='जन्म दिनांक',$value=$farmer1->birthdate,$width=270,$height=30,$align='right',$iscompulsory=False,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
                //$farmer1->textcombobox($fieldname='bankbranchcode',$combosearchfield='bankbranch',$combocodefield='bankbranchcode',$englishlabel='Bank Branch',$unicodelabel='बँक शाखा',$value=$farmer1->bankbranch,$codevalue=$farmer1->bankbranchcode,$width=270,$height=30,$iscompulsory=False,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
                //$farmer1->textbox($fieldname='accountnumber',$englishlabel='Account Number',$unicodelabel='खाते क्रमांक',$value=$farmer1->accountnumber,$width=270,$height=30,$align='left',$iscompulsory=False,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
            }
            else
            {
                $farmer1->textbox($fieldname='farmernameuni',$englishlabel='Farmer Name (Unicode)',$unicodelabel='शेतकरी नाव (मराठी)',$value=$farmer1->farmernameuni,$width=270,$height=30,$align='left',$iscompulsory=True,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=true);
                $farmer1->textbox($fieldname='farmernameeng',$englishlabel='Farmer Name (English)',$unicodelabel='शेतकरी नाव (इंग्रजी)',$value=$farmer1->farmernameeng,$width=270,$height=30,$align='left',$iscompulsory=True,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
                if ($_SESSION['responsibilitycode']==123476175 or $_SESSION['responsibilitycode']==123476492)
                {
                    $farmer1->textbox($fieldname='farmernamebankeng',$englishlabel='Bank Farmer Name (English)',$unicodelabel='बँक शेतकरी नाव (इंग्रजी)',$value=$farmer1->farmernamebankeng,$width=270,$height=30,$align='left',$iscompulsory=False,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
                    $farmer1->textbox($fieldname='farmernamebankuni',$englishlabel='Bank Farmer Name (Unicode)',$unicodelabel='बँक शेतकरी नाव (मराठी)',$value=$farmer1->farmernamebankuni,$width=270,$height=30,$align='left',$iscompulsory=False,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
                }
                $farmer1->textcombobox($fieldname='villagecode',$combosearchfield='village',$combocodefield='villagecode',$englishlabel='Village',$unicodelabel='गाव',$value=$farmer1->village,$codevalue=$farmer1->villagecode,$width=270,$height=30,$iscompulsory=True,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
                $farmer1->listcombo($fieldname='farmercategorycode',$connection,$sourcetable='farmercategory',$combocodefield='farmercategorycode',$codevalue=$farmer1->farmercategorycode,$nameeng='farmercategorynameeng',$nameuni='farmercategorynameuni',$englishlabel='Farmer Category',$unicodelabel='शेतकरी प्रकार',$width=270,$height=30,$iscompulsory=True,$isreadonly=False,$found=$farmer1->found,$isautofocus=false);
                $farmer1->textbox($fieldname='mobilenumber',$englishlabel='Mobile Number',$unicodelabel='मोबाईल नंबर',$value=$farmer1->mobilenumber,$width=270,$height=30,$align='right',$iscompulsory=False,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
                //$farmer1->textbox($fieldname='mobilenumber2',$englishlabel='Mobile Number 2',$unicodelabel='मोबाईल नंबर २',$value=$farmer1->mobilenumber2,$width=270,$height=30,$align='right',$iscompulsory=False,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
                $farmer1->textbox($fieldname='adharnumber',$englishlabel='Adhar Number',$unicodelabel='आधार नंबर',$value=$farmer1->adharnumber,$width=270,$height=30,$align='right',$iscompulsory=False,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
                $farmer1->textbox($fieldname='pannumber',$englishlabel='PAN Number',$unicodelabel='पॅन नंबर',$value=$farmer1->pannumber,$width=270,$height=30,$align='right',$iscompulsory=False,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
                $farmer1->textbox($fieldname='birthdate',$englishlabel='Birthdate',$unicodelabel='जन्म दिनांक',$value=$farmer1->birthdate,$width=270,$height=30,$align='right',$iscompulsory=False,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
                if ($_SESSION['responsibilitycode']==123476175 or $_SESSION['responsibilitycode']==123476492)
                {
                    $farmer1->textcombobox($fieldname='bankbranchcode',$combosearchfield='bankbranch',$combocodefield='bankbranchcode',$englishlabel='Bank Branch',$unicodelabel='बँक शाखा',$value=$farmer1->bankbranch,$codevalue=$farmer1->bankbranchcode,$width=270,$height=30,$iscompulsory=False,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
                    $farmer1->textbox($fieldname='ifsc',$englishlabel='IFSC Code',$unicodelabel='IFSC Code',$value=$farmer1->ifsc,$width=270,$height=30,$align='left',$iscompulsory=False,$isreadonly=true,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);                    
                    $farmer1->textbox($fieldname='accountnumber',$englishlabel='Account Number',$unicodelabel='खाते क्रमांक',$value=$farmer1->accountnumber,$width=270,$height=30,$align='left',$iscompulsory=False,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
                }
            }
        }
        //record found
        elseif ($farmer1->found == true and $alterresponsibilityid==123476492)
        {
            $farmer1->textbox($fieldname='farmercode',$englishlabel='Farmer Code',$unicodelabel='शेतकरी कोड',$value=$farmer1->farmercode,$width=270,$height=30,$align='right',$iscompulsory=False,$isreadonly=True,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $farmer1->textbox($fieldname='farmernameuni',$englishlabel='Farmer Name (Unicode)',$unicodelabel='शेतकरी नाव (मराठी)',$value=$farmer1->farmernameuni,$width=270,$height=30,$align='left',$iscompulsory=True,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $farmer1->textbox($fieldname='farmernameeng',$englishlabel='Farmer Name (English)',$unicodelabel='शेतकरी नाव (इंग्रजी)',$value=$farmer1->farmernameeng,$width=270,$height=30,$align='left',$iscompulsory=True,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
            if ($_SESSION['responsibilitycode']==123476175 or $_SESSION['responsibilitycode']==123476492)
            {
                $farmer1->textbox($fieldname='farmernamebankeng',$englishlabel='Bank Farmer Name (English)',$unicodelabel='बँक शेतकरी नाव (इंग्रजी)',$value=$farmer1->farmernamebankeng,$width=270,$height=30,$align='left',$iscompulsory=False,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
                $farmer1->textbox($fieldname='farmernamebankuni',$englishlabel='Bank Farmer Name (Unicode)',$unicodelabel='बँक शेतकरी नाव (मराठी)',$value=$farmer1->farmernamebankuni,$width=270,$height=30,$align='left',$iscompulsory=False,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
            }
            $farmer1->textcombobox($fieldname='villagecode',$combosearchfield='village',$combocodefield='villagecode',$englishlabel='Village',$unicodelabel='गाव',$value=$farmer1->village,$codevalue=$farmer1->villagecode,$width=270,$height=30,$iscompulsory=True,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $farmer1->listcombo($fieldname='farmercategorycode',$connection,$sourcetable='farmercategory',$combocodefield='farmercategorycode',$codevalue=$farmer1->farmercategorycode,$nameeng='farmercategorynameeng',$nameuni='farmercategorynameuni',$englishlabel='Farmer Category',$unicodelabel='शेतकरी प्रकार',$width=270,$height=30,$iscompulsory=True,$isreadonly=False,$found=$farmer1->found,$isautofocus=false);
            $farmer1->textbox($fieldname='mobilenumber',$englishlabel='Mobile Number',$unicodelabel='मोबाईल नंबर',$value=$farmer1->mobilenumber,$width=270,$height=30,$align='right',$iscompulsory=False,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
            //$farmer1->textbox($fieldname='mobilenumber2',$englishlabel='Mobile Number 2',$unicodelabel='मोबाईल नंबर २',$value=$farmer1->mobilenumber2,$width=270,$height=30,$align='right',$iscompulsory=False,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $farmer1->textbox($fieldname='adharnumber',$englishlabel='Adhar Number',$unicodelabel='आधार नंबर',$value=$farmer1->adharnumber,$width=270,$height=30,$align='right',$iscompulsory=False,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $farmer1->textcombobox($fieldname='bankbranchcode',$combosearchfield='bankbranch',$combocodefield='bankbranchcode',$englishlabel='Bank Branch',$unicodelabel='बँक शाखा',$value=$farmer1->bankbranch,$codevalue=$farmer1->bankbranchcode,$width=270,$height=30,$iscompulsory=False,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
                $farmer1->textbox($fieldname='ifsc',$englishlabel='IFSC Code',$unicodelabel='IFSC Code',$value=$farmer1->ifsc,$width=270,$height=30,$align='left',$iscompulsory=False,$isreadonly=true,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
                $farmer1->textbox($fieldname='accountnumber',$englishlabel='Account Number',$unicodelabel='खाते क्रमांक',$value=$farmer1->accountnumber,$width=270,$height=30,$align='left',$iscompulsory=False,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);

            /* if ($farmer1->verified == 0)
            {
                $farmer1->textcombobox($fieldname='bankbranchcode',$combosearchfield='bankbranch',$combocodefield='bankbranchcode',$englishlabel='Bank Branch',$unicodelabel='बँक शाखा',$value=$farmer1->bankbranch,$codevalue=$farmer1->bankbranchcode,$width=270,$height=30,$iscompulsory=False,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
                $farmer1->textbox($fieldname='ifsc',$englishlabel='IFSC Code',$unicodelabel='IFSC Code',$value=$farmer1->ifsc,$width=270,$height=30,$align='left',$iscompulsory=False,$isreadonly=true,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
                $farmer1->textbox($fieldname='accountnumber',$englishlabel='Account Number',$unicodelabel='खाते क्रमांक',$value=$farmer1->accountnumber,$width=270,$height=30,$align='left',$iscompulsory=False,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
            }
            else
            { */
                //$farmer1->textcombobox($fieldname='bankbranchcode',$combosearchfield='bankbranch',$combocodefield='bankbranchcode',$englishlabel='Bank Branch',$unicodelabel='बँक शाखा',$value=$farmer1->bankbranch,$codevalue=$farmer1->bankbranchcode,$width=270,$height=30,$iscompulsory=False,$isreadonly=true,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
                //$farmer1->textbox($fieldname='ifsc',$englishlabel='IFSC Code',$unicodelabel='IFSC Code',$value=$farmer1->ifsc,$width=270,$height=30,$align='left',$iscompulsory=False,$isreadonly=true,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
                //$farmer1->textbox($fieldname='accountnumber',$englishlabel='Account Number',$unicodelabel='खाते क्रमांक',$value=$farmer1->accountnumber,$width=270,$height=30,$align='left',$iscompulsory=False,$isreadonly=true,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
            //}
        }
        //smartcard master
        elseif ($farmer1->found == true and $alterresponsibilityid==123986642)
        {
            $farmer1->textbox($fieldname='farmercode',$englishlabel='Farmer Code',$unicodelabel='शेतकरी कोड',$value=$farmer1->farmercode,$width=270,$height=30,$align='right',$iscompulsory=False,$isreadonly=True,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $farmer1->textbox($fieldname='farmernameuni',$englishlabel='Farmer Name (Unicode)',$unicodelabel='शेतकरी नाव (मराठी)',$value=$farmer1->farmernameuni,$width=270,$height=30,$align='left',$iscompulsory=True,$isreadonly=True,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $farmer1->textbox($fieldname='farmernameeng',$englishlabel='Farmer Name (English)',$unicodelabel='शेतकरी नाव (इंग्रजी)',$value=$farmer1->farmernameeng,$width=270,$height=30,$align='left',$iscompulsory=True,$isreadonly=True,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $farmer1->textcombobox($fieldname='villagecode',$combosearchfield='village',$combocodefield='villagecode',$englishlabel='Village',$unicodelabel='गाव',$value=$farmer1->village,$codevalue=$farmer1->villagecode,$width=270,$height=30,$iscompulsory=True,$isreadonly=True,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $farmer1->listcombo($fieldname='farmercategorycode',$connection,$sourcetable='farmercategory',$combocodefield='farmercategorycode',$codevalue=$farmer1->farmercategorycode,$nameeng='farmercategorynameeng',$nameuni='farmercategorynameuni',$englishlabel='Farmer Category',$unicodelabel='शेतकरी प्रकार',$width=270,$height=30,$iscompulsory=True,$isreadonly=True,$found=$farmer1->found,$isautofocus=false);
            $farmer1->textbox($fieldname='mobilenumber',$englishlabel='Mobile Number',$unicodelabel='मोबाईल नंबर',$value=$farmer1->mobilenumber,$width=270,$height=30,$align='right',$iscompulsory=False,$isreadonly=True,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
            //$farmer1->textbox($fieldname='mobilenumber2',$englishlabel='Mobile Number 2',$unicodelabel='मोबाईल नंबर २',$value=$farmer1->mobilenumber2,$width=270,$height=30,$align='right',$iscompulsory=False,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $farmer1->textbox($fieldname='adharnumber',$englishlabel='Adhar Number',$unicodelabel='आधार नंबर',$value=$farmer1->adharnumber,$width=270,$height=30,$align='right',$iscompulsory=False,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $farmer1->textbox($fieldname='pannumber',$englishlabel='PAN Number',$unicodelabel='पॅन नंबर',$value=$farmer1->pannumber,$width=270,$height=30,$align='right',$iscompulsory=False,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $farmer1->textbox($fieldname='birthdate',$englishlabel='Birthdate',$unicodelabel='जन्म दिनांक',$value=$farmer1->birthdate,$width=270,$height=30,$align='right',$iscompulsory=False,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
        }
        elseif ($farmer1->found == true and $alterresponsibilityid!=123476492 and $alterresponsibilityid!=123986642)
        {
            $farmer1->textbox($fieldname='farmercode',$englishlabel='Farmer Code',$unicodelabel='शेतकरी कोड',$value=$farmer1->farmercode,$width=270,$height=30,$align='right',$iscompulsory=False,$isreadonly=True,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $farmer1->textbox($fieldname='farmernameuni',$englishlabel='Farmer Name (Unicode)',$unicodelabel='शेतकरी नाव (मराठी)',$value=$farmer1->farmernameuni,$width=270,$height=30,$align='left',$iscompulsory=True,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $farmer1->textbox($fieldname='farmernameeng',$englishlabel='Farmer Name (English)',$unicodelabel='शेतकरी नाव (इंग्रजी)',$value=$farmer1->farmernameeng,$width=270,$height=30,$align='left',$iscompulsory=True,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
            if ($_SESSION['responsibilitycode']==123476175 or $_SESSION['responsibilitycode']==123476492)
            {
                $farmer1->textbox($fieldname='farmernamebankeng',$englishlabel='Bank Farmer Name (English)',$unicodelabel='बँक शेतकरी नाव (इंग्रजी)',$value=$farmer1->farmernamebankeng,$width=270,$height=30,$align='left',$iscompulsory=False,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
                $farmer1->textbox($fieldname='farmernamebankuni',$englishlabel='Bank Farmer Name (Unicode)',$unicodelabel='बँक शेतकरी नाव (मराठी)',$value=$farmer1->farmernamebankuni,$width=270,$height=30,$align='left',$iscompulsory=False,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
            }
            $farmer1->textcombobox($fieldname='villagecode',$combosearchfield='village',$combocodefield='villagecode',$englishlabel='Village',$unicodelabel='गाव',$value=$farmer1->village,$codevalue=$farmer1->villagecode,$width=270,$height=30,$iscompulsory=True,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $farmer1->listcombo($fieldname='farmercategorycode',$connection,$sourcetable='farmercategory',$combocodefield='farmercategorycode',$codevalue=$farmer1->farmercategorycode,$nameeng='farmercategorynameeng',$nameuni='farmercategorynameuni',$englishlabel='Farmer Category',$unicodelabel='शेतकरी प्रकार',$width=270,$height=30,$iscompulsory=True,$isreadonly=False,$found=$farmer1->found,$isautofocus=false);
            $farmer1->textbox($fieldname='mobilenumber',$englishlabel='Mobile Number',$unicodelabel='मोबाईल नंबर',$value=$farmer1->mobilenumber,$width=270,$height=30,$align='right',$iscompulsory=False,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
            //$farmer1->textbox($fieldname='mobilenumber2',$englishlabel='Mobile Number 2',$unicodelabel='मोबाईल नंबर २',$value=$farmer1->mobilenumber2,$width=270,$height=30,$align='right',$iscompulsory=False,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $farmer1->textbox($fieldname='adharnumber',$englishlabel='Adhar Number',$unicodelabel='आधार नंबर',$value=$farmer1->adharnumber,$width=270,$height=30,$align='right',$iscompulsory=False,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
            if ($_SESSION['responsibilitycode']==123476175 or $_SESSION['responsibilitycode']==123476492)
            {
                $farmer1->textcombobox($fieldname='bankbranchcode',$combosearchfield='bankbranch',$combocodefield='bankbranchcode',$englishlabel='Bank Branch',$unicodelabel='बँक शाखा',$value=$farmer1->bankbranch,$codevalue=$farmer1->bankbranchcode,$width=270,$height=30,$iscompulsory=False,$isreadonly=True,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
                $farmer1->textbox($fieldname='ifsc',$englishlabel='IFSC Code',$unicodelabel='IFSC Code',$value=$farmer1->ifsc,$width=270,$height=30,$align='left',$iscompulsory=False,$isreadonly=False,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
                $farmer1->textbox($fieldname='accountnumber',$englishlabel='Account Number',$unicodelabel='खाते क्रमांक',$value=$farmer1->accountnumber,$width=270,$height=30,$align='left',$iscompulsory=False,$isreadonly=True,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
            }
        }
        echo '<tr>';
        if ($flag_de != 'Query')
        {
            echo '<td><input class="button123" type="hidden" style="font-size:12pt;height:30px" name="farmercode" id="farmercode" value="'.$farmercode_de.'" style="width:300px"></td>';
        }
        echo '</tr>';
        if (($_SESSION['responsibilitycode']==$addresponsibilityid or $_SESSION['responsibilitycode']==$alterresponsibilityid) and $flag_de=='Query')
        {
            echo '<tr>';
            echo '<td><input class="button123" type="submit" name="btn" value="Display" style="width:100px"></td>';
            echo '</tr>';
        }
        elseif ($_SESSION['responsibilitycode']==$alterresponsibilityid and $farmer1->found==true)
        {
            echo '<tr>';
            echo '<td><input class="button123" type="submit" name="btn" value="Change" style="width:100px"></td>';
            echo '</tr>';
            if ($alterresponsibilityid==123476492)
            {
                /* echo '<tr>';
                echo '<td><input class="button123" type="submit" name="btn" value="Delete" style="width:100px"></td>';
                echo '</tr>'; */
            }
        }
        elseif (($_SESSION['responsibilitycode']==$addresponsibilityid or $_SESSION['responsibilitycode']==$alterresponsibilityid) and $farmer1->found==false)
        {
            echo '<tr>';
            echo '<td><input class="button123" type="submit" name="btn" value="Add" style="width:100px"></td>';
            echo '</tr>';
        }
        if ($farmer1->found==false)
        {
            echo '</table>';
            echo '</div>';
            echo '<div style="width:300px;float:left">';
            echo '<table border="0" >';

            $farmer1->textbox($fieldname='dupfarmernameeng',$englishlabel='Existing Farmer Name (Unicode)',$unicodelabel='ड्यूप्लिकेट शेतकरी नाव',$value=$farmer1->dupfarmernameeng,$width=500,$height=30,$align='left',$iscompulsory=False,$isreadonly=True,$found=$farmer1->found,$flag=$flag_de,$js='',$isautofocus=false);
        }
        if ($farmer1->found==true and ($_SESSION['responsibilitycode']==123476175 or $_SESSION['responsibilitycode']==123476492))
        {
            echo '</table>';
            echo '</div>';
            echo '<div style="width:300px;float:left">';
            echo '<table border="0" >';
            $farmeradhikarpatra1 = new farmeradhikarpatra($connection);
            $result = $farmeradhikarpatra1->fetchall($farmercode_de);
            $r = oci_execute($result);
            $farmercode_en = fnEncrypt($farmercode_de);
            echo '<tr>';
            if ($_SESSION['lng']=="English")
            {
                echo '<th width="100%"style="text-align:left;background:#7fb5da;">Adhikar Patra</th>';
            }
            else
            {
                echo '<th width="100%" style="text-align:left;background:#7fb5da;">अधिकारपत्र</th>';
            }
            echo '</tr>';
            $flag_en = fnEncrypt('Display');
            while ($row = oci_fetch_array($result,OCI_ASSOC+OCI_RETURN_NULLS))
            {
                $farmercode_en = fnEncrypt($row['FARMERCODE']);
                $adhikarpatracode_en = fnEncrypt($row['ADHIKARPATRACODE']);
                if ($_SESSION['lng']=="English")
                {
                    echo '<tr>';
                    echo '<td style="text-align:left;font-size:14px"><a href="../ip_view/faremreadhikarpatra.php?farmercode='.$farmercode_en.'&adhikarpatracode='.$adhikarpatracode_en.'&flag='.$flag_en.'">'.$row['ADHIKARPATRANAMEENG'].'</a></td>';
                    echo '</tr>';
                }
                else
                {
                    echo '<tr>';
                    echo '<td style="text-align:left;font-size:14px"><a href="../ip_view/farmeradhikarpatra.php?farmercode='.$farmercode_en.'&adhikarpatracode='.$adhikarpatracode_en.'&flag='.$flag_en.'">'.$row['ADHIKARPATRANAMEUNI'].'</a></td>';
                    echo '</tr>';
                }
            }
        }
        echo '</table>';
        echo '</form>';
        echo '</section>';
    ?>
    </article>
    <footer>
    </footer>
    </body>
</html>

