<?php
    //This is generated by Swapp Software Application on 06/06/2019 11:50:16 AM for PHP
    require_once("../info/phpsqlajax_dbinfo.php");
    require_once("../info/phpgetloginview.php");
    require_once("../info/routine.php");
    $connection =swapp_connection();
    $searchTerm = $_GET['term'];
    if (preg_match('/^[0-9]*$/', $searchTerm))
    {
    }
    elseif ((strlen($searchTerm)<3) and $searchTerm != '**')
    {
        exit;
    }
   if ($searchTerm == '**')
   {
       $query = "select transactionnumber,
       fieldslipnumber,
       fieldslipnumber
       from fieldslip where seasoncode=".$_SESSION['yearperiodcode']." and rownum <= 10";
   }
   else
   {
       $query = "select transactionnumber,
       fieldslipnumber,
       fieldslipnumber
       from fieldslip where (upper(fieldslipnumber) like upper('%".$searchTerm."%')
       or fieldslipnumber like '%".$searchTerm."%'
       or to_char(transactionnumber) like '".$searchTerm."') and seasoncode=20192020 and rownum <= 10";
   }
   $result = oci_parse($connection, $query); $r = oci_execute($result);
   $r = oci_execute($result);
   while ($row = oci_fetch_array($result,OCI_ASSOC+OCI_RETURN_NULLS))
   {
       $id = $row['TRANSACTIONNUMBER'];
       if ($_SESSION['lng'] == "English")
       {
           $name = $row['FIELDSLIPNUMBER'];
       }
       else
       {
           $name = $row['FIELDSLIPNUMBER'];
       }
       $data[] = array( 
           'id' => $id
           ,'label' => $name
           ,'value' => $name
           );
   }
   //return json data
   echo json_encode($data);
?>

