<?php
    //This is generated by Nigade Software Technologies (opc) Private Limited on 14/08/2020 09:33:09 am for PHP
    require_once("../info/phpsqlajax_dbinfo.php");
    require_once("../info/phpgetloginform.php");
    require_once("../info/ncryptdcrypt.php");
    require_once("../info/routine.php");
    require_once("../ip_model/formparameterdetail_db_oracle.php");
    $connection=swapp_connection_user('nst_nasaka_db');
    //Addition or Alteration
    //Addition or Alteration
    $addresponsibilityid=123480930;
    $alterresponsibilityid=123480930;
    if (isaccessible($addresponsibilityid)==0 and isaccessible($alterresponsibilityid)==0)
    {
        echo'Communication Error';
        exit;
    }
    $formcode_de = fnDecrypt($_GET['formcode']);
    $serialnumber_de = fnDecrypt($_GET['serialnumber']);
    $flag_de = fnDecrypt($_GET['flag']);
    $formparameterdetail1 = new formparameterdetail($connection);
    $formparameterdetail1->formcode=$formcode_de;
    $formparameterdetail1->serialnumber=$serialnumber_de;
    $formparameterdetail1->fetch();
?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"></meta>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="../css/w3.css">
        <title>formparameterdetail</title>
        <link rel="stylesheet" href="../css/swapp123.css">
        <script src="../js/1.11.0/jquery.min.js">
         </script>
         <script>
            $(document).ready(function(){
             setInterval(function(){cache_clear()},3600000);
             });
             function cache_clear()
            {
             window.location.reload(true);
            }
        </script>
        <script>
            var data = {};
            $(document).ready(function() {
            $('input[type="submit"]').on('click', function() {
            resetErrors();
            var url = '../ip_controller/formparameterdetail_action.php';
            $.each($('form input, form select'), function(i, v) {
            if (v.type !== 'submit') {
            data[v.name] = v.value;
            //data['btn']=$('input[type="submit"]').val();
            data['btn']=document.activeElement.getAttribute('value');
            }
            }); //end each
            $.ajax({
            dataType: 'json',
            type: 'POST',
            url: url,
            data: data,
            success: function(resp) {
            if (resp === true) {
            //successful validation
            data['btn']=$('input[type="submit"]').val();
            $('form').submit();
            console.log('submitted');
            return false;
            } else {
            $.each(resp, function(i, v) {
            console.log(i + " => " + v); // view in console for error messages
            var msg = '<label class="error" for="'+i+'">'+v+'</label>';
            $('input[name="' + i + '"], select[name="' + i + '"]').addClass('').after(msg);
            });
            var keys = Object.keys(resp);
            $('input[name="'+keys[0]+'"]').focus();
            }
            return false;
            },
            error: function() {
            console.log('there was a problem checking the fields');
            }
            });
            return false;
            });
            });
            function resetErrors() {
            $('form input, form select').removeClass('inputTxtError');
            $('label.error').remove();
            }
        </script>
        <link rel="stylesheet" href="../css/ui/1.11.4/themes/smoothness/jquery-ui.css">
        <script src="..//js/jquery-1.10.2.js"></script>
        <script src="..//js/ui/1.11.4/jquery-ui.js"></script>
    </head>
    <body>
        <nav "w3-container">
            <ul class="navbar">
                <li><a class="navbar" href="../mis/entitymenu.php">Entity Menu</a><br/>
                <?php
                    $flag_en = fnEncrypt('Query');
                    //echo '<li><a class="navbar" href="../ip_view/formparameterdetail.php">New formparameterdetail   </a>';
                    //echo '<li><a class="navbar" href="../ip_view/formparameterdetail.php?flag='.$flag_en.'">Find formparameterdetail   </a>';
                    $formcode_en = fnEncrypt($formcode_de);
                    $serialnumber_en = fnEncrypt($serialnumber_de);
                    echo '<li><a class="navbar" href="../ip_view/form.php?formcode='.$formcode_en.'&serialnumber='.$serialnumber_en.'&flag='.$flag_en.'">Form </a>';
                    echo '<li><a  class="navbar" href="../../../../../sqlproc/logout.php">Log Out</a><br/>';
                ?>
            </ul>
        </nav>
        <article class="w3-container">


<?php
    echo '<section>';
    echo '<form method="post" action="../ip_controller/formparameterdetail_action.php">';
    echo '<div style="width:250px;float:left">';
    echo '<table border="0" >';
    echo '<tr>';
    echo '<td></td>';
    echo '</tr>';
    echo '<img src="../img/createimage.php?name=formparameterdetail&width=251&size=14&r=150&g=0&b=0&r1=255&g1=230&b1=0"></br></br>';
    if ($flag_de == 'Query')
    {
        echo '<img src="../img/createimage.php?name=Find Records&width=201&size=12&r=255&g=255&b=255&r1=0&g1=150&b1=0">';
    }
    elseif ($flag_de == 'Display' and $_SESSION['responsibilitycode']==$alterresponsibilityid )
    {
       echo '<img src="../img/createimage.php?name=Change/Delete Record&width=201&size=12&r=255&g=255&b=255&r1=0&g1=150&b1=0">';
    }
    elseif ($formparameterdetail1->found == false)
    {
       echo '<img src="../img/createimage.php?name=New Record Entry&width=201&size=12&r=255&g=255&b=255&r1=0&g1=150&b1=0">';
    }
        //record query parameter
        if ($flag_de == 'Query')
        {
            $formparameterdetail1->textbox($fieldname='parametername',$englishlabel='Parameter Name',$unicodelabel='पॅरामिटर नाव',$value=$formparameterdetail1->parametername,$width=200,$height=30,$align='left',$iscompulsory=True,$isreadonly=False,$found=$formparameterdetail1->found,$flag=$flag_de,$js='',$isautofocus=false);
        }
        //new record
        elseif ($formparameterdetail1->found == false)
        {
            $formparameterdetail1->textbox($fieldname='parametername',$englishlabel='Parameter Name',$unicodelabel='पॅरामिटर नाव',$value=$formparameterdetail1->parametername,$width=200,$height=30,$align='left',$iscompulsory=True,$isreadonly=False,$found=$formparameterdetail1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $formparameterdetail1->textbox($fieldname='parametervalue',$englishlabel='Parameter Value',$unicodelabel='पॅरामिटर माहिती',$value=$formparameterdetail1->parametervalue,$width=200,$height=30,$align='left',$iscompulsory=True,$isreadonly=False,$found=$formparameterdetail1->found,$flag=$flag_de,$js='',$isautofocus=false);
        }
        //record found
        elseif ($formparameterdetail1->found == true)
        {
            $formparameterdetail1->textbox($fieldname='formcode',$englishlabel='Form Code',$unicodelabel='फाॅर्म कोड',$value=$formparameterdetail1->formcode,$width=200,$height=30,$align='right',$iscompulsory=False,$isreadonly=True,$found=$formparameterdetail1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $formparameterdetail1->textbox($fieldname='serialnumber',$englishlabel='Serial Number',$unicodelabel='अनुक्रमांक',$value=$formparameterdetail1->serialnumber,$width=200,$height=30,$align='right',$iscompulsory=False,$isreadonly=True,$found=$formparameterdetail1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $formparameterdetail1->textbox($fieldname='parametername',$englishlabel='Parameter Name',$unicodelabel='पॅरामिटर नाव',$value=$formparameterdetail1->parametername,$width=200,$height=30,$align='left',$iscompulsory=True,$isreadonly=False,$found=$formparameterdetail1->found,$flag=$flag_de,$js='',$isautofocus=false);
            $formparameterdetail1->textbox($fieldname='parametervalue',$englishlabel='Parameter Value',$unicodelabel='पॅरामिटर माहिती',$value=$formparameterdetail1->parametervalue,$width=200,$height=30,$align='left',$iscompulsory=True,$isreadonly=False,$found=$formparameterdetail1->found,$flag=$flag_de,$js='',$isautofocus=false);
        }
        echo '<tr>';
        echo '<td><input class="button123" type="hidden" style="font-size:12pt;height:30px" name="formcode" id="formcode" value="'.$formcode_de.'" style="width:300px"></td>';
        echo '<td><input class="button123" type="hidden" style="font-size:12pt;height:30px" name="serialnumber" id="serialnumber" value="'.$serialnumber_de.'" style="width:300px"></td>';
echo '<tr>';
echo '<td><input class="error" type="hidden" style="font-size:12pt;height:30px" name="error" id="error" value="error" style="width:300px"></td>';
echo '</tr>';
        echo '</tr>';
        if (($_SESSION['responsibilitycode']==$addresponsibilityid or $_SESSION['responsibilitycode']==$alterresponsibilityid) and $flag_de=='Query')
        {
            echo '<tr>';
            echo '<td><input class="button123" type="submit" name="btn" value="Display" style="width:100px"></td>';
            echo '</tr>';
        }
        elseif ($_SESSION['responsibilitycode']==$alterresponsibilityid and $formparameterdetail1->found==true)
        {
            echo '<tr>';
            echo '<td><input class="button123" type="submit" name="btn" value="Change" style="width:100px"></td>';
            echo '</tr>';
            echo '<tr>';
            echo '<td><input class="button123" type="submit" name="btn" value="Delete" style="width:100px"></td>';
            echo '</tr>';
        }
        elseif (($_SESSION['responsibilitycode']==$addresponsibilityid or $_SESSION['responsibilitycode']==$alterresponsibilityid) and $formparameterdetail1->found==false)
        {
            echo '<tr>';
            echo '<td><input class="button123" type="submit" name="btn" value="Add" style="width:100px"></td>';
            echo '</tr>';
        }
        echo '</table>';
        echo '</div>';
        echo '</form>';
        echo '</section>';
    ?>
    </article>
    <footer>
    </footer>
    </body>
</html>

