<?php
    //This is generated by Swapp Software Application on 18/09/2019 11:51:40 AM for PHP
    require_once("../info/phpsqlajax_dbinfo.php");
    require_once("../info/phpgetloginform.php");
    require_once("../info/ncryptdcrypt.php");
    require_once("../info/routine.php");
    require_once("../ip_model/swapp_table_info_db_oracle.php");
    //Addition or Alteration
    $addresponsibilityid=123480930;
    $alterresponsibilityid=123480930;
    if (isaccessible($addresponsibilityid)==0 and isaccessible($alterresponsibilityid)==0)
    {
        echo'Communication Error';
        exit;
    }
    $owner_de = fnDecrypt($_GET['owner']);
    $tablename_de = fnDecrypt($_GET['tablename']);
    $columid_de = fnDecrypt($_GET['columid']);
    $fieldname_de = fnDecrypt($_GET['fieldname']);
    $flag_de = fnDecrypt($_GET['flag']);
    $connection=swapp_connection();
    $_SESSION['status']='initial';
?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"></meta>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="../css/w3.css">
        <title>Contract</title>
        <link rel="stylesheet" href="../css/swapp123.css">
        <script src="../js/1.11.0/jquery.min.js">
         </script>
         <script>
            $(document).ready(function(){
             setInterval(function(){cache_clear()},3600000);
             });
             function cache_clear()
            {
             window.location.reload(true);
            }
        </script>
        
        <script>
            var data = {};
            $(document).ready(function() {
            $('input[type="submit"]').on('click', function() {
            resetErrors();
            var url = '../ip_controller/swapp_table_info_action.php';
            $.each($('form input, form select'), function(i, v) {
            if (v.type !== 'submit') {
            data[v.name] = v.value;
            data['btn']=$('input[type="submit"]').val();
            }
            }); //end each
            $.ajax({
            dataType: 'json',
            type: 'POST',
            url: url,
            data: data,
            success: function(resp) {
            if (resp === true) {
            //successful validation
            data['btn']=$('input[type="submit"]').val();
            $('form').submit();
            console.log('submitted');
            return false;
            } else {
            $.each(resp, function(i, v) {
            console.log(i + " => " + v); // view in console for error messages
            var msg = '<label class="error" for="'+i+'">'+v+'</label>';
            $('input[name="' + i + '"], select[name="' + i + '"]').addClass('inputTxtError').after(msg);
            });
            var keys = Object.keys(resp);
            $('input[name="'+keys[0]+'"]').focus();
            }
            return false;
            },
            error: function() {
            console.log('there was a problem checking the fields');
            }
            });
            return false;
            });
            });
            function resetErrors() {
            $('form input, form select').removeClass('inputTxtError');
            $('label.error').remove();
            }
        </script>
        <script>
            $(function()
            {
                $("#combotableowner").autocomplete({
                source: 'tableowner_search.php',
                minLength:3,
                delay:200,
                autoFocus:true,
                autoselect:true,
                select:function(event,ui)
                {var v = ui.item.value;
                 var i = ui.item.id;
                $('#combotableowner').val(i);
                this.value = v;
                return false;}
                });
            });
        </script>
        <script>
            $(function()
            {
                $("#combotable").autocomplete({
                source: function(request, response) {
                    $.getJSON("combotable_search.php"
                    ,{term: request.term
                    ,owner:$('#owner').val()
                    ,tablename:$('#tablename').val()
                    ,combotableowner:$('#combotableowner').val()
                    }, 
                            response);
                },
                minLength:3,
                delay:200,
                autoFocus:true,
                autoselect:true,
                select:function(event,ui)
                {var v = ui.item.value;
                 var i = ui.item.id;
                 var c = ui.item.pkcol;
                 var e = ui.item.coleng;
                 var u = ui.item.coluni;
                 var n = ui.item.comowner;
                $('#combotable').val(i);
                this.value = v;
                $('#combodatafield').val(c);
                $('#comboengfield').val(e);
                $('#combounicodefield').val(u);
                $('#combotableowner').val(n);
                return false;}
                });
            });
        </script>
        <link rel="stylesheet" href="../css/ui/1.11.4/themes/smoothness/jquery-ui.css">
        <script src="..//js/jquery-1.10.2.js"></script>
        <script src="..//js/ui/1.11.4/jquery-ui.js"></script>
    </head>
    <body>
        <nav "w3-container">
            <ul class="navbar">
                <li><a class="navbar" href="../mis/entitymenu.php">Entity Menu</a><br/>
                <?php
                    $flag_en = fnEncrypt('Query');
                    echo '<li><a class="navbar" href="../ip_view/swapp_table_info.php">New PHP Form Generator   </a>';
                    echo '<li><a class="navbar" href="../ip_view/swapp_table_info.php?flag='.$flag_en.'">Find PHP Form Generator   </a>';
                    echo '<li><a class="navbar" href="../ip_view/swapp_table.php?owner='.fnEncrypt($owner_de).'&tablename='.fnEncrypt($tablename_de).'">Field List</a>';
                    echo '<li><a  class="navbar" href="../../../../../sqlproc/logout.php">Log Out</a><br/>';
                ?>
            </ul>
        </nav>
        <article class="w3-container">
<?php
    $swapp_table_info1 = new swapp_table_info($connection);
    $swapp_table_info1->owner=strtoupper($owner_de);
    $swapp_table_info1->tablename=strtoupper($tablename_de);
    $swapp_table_info1->columid=$columid_de;
    $swapp_table_info1->fieldname=strtoupper($fieldname_de);
    $swapp_table_info1->fetch();
    echo '<section>';
    echo '<form method="post" action="../ip_controller/swapp_table_info_action.php">';
    echo '<div style="width:300px;float:left">';
    echo '<table border="0">';
    echo '<tr>';
    echo '<td></td>';
    echo '</tr>';
    echo '<img src="../img/createimage.php?name=PHP Form Generator&width=251&size=14&r=150&g=0&b=0&r1=255&g1=230&b1=0"></br></br>';
    if ($flag_de == 'Query')
    {
        echo '<img src="../img/createimage.php?name=Find Records&width=201&size=12&r=255&g=255&b=255&r1=0&g1=150&b1=0">';
    }
    elseif ($flag_de == 'Display' and $_SESSION['responsibilitycode']==$alterresponsibilityid )
    {
       echo '<img src="../img/createimage.php?name=Change/Delete Record&width=201&size=12&r=255&g=255&b=255&r1=0&g1=150&b1=0">';
    }
    elseif ($swapp_table_info1->found == false)
    {
       echo '<img src="../img/createimage.php?name=New Record Entry&width=201&size=12&r=255&g=255&b=255&r1=0&g1=150&b1=0">';
    }
        if ($flag_de != 'Query')
        {
            if ($_SESSION['lng']=="English")
            {
                echo '<tr>';
                echo '<td><label for="owner" class="thick">Owner User</label></td>';
                echo '</tr>';
            }
            else
            {
                echo '<tr>';
                echo '<td><label for="owner" class="thick">ओनर युजर</label></td>';
                echo '</tr>';
            }
            echo '<tr>';
            echo '<td><input type="text" readonly="readonly" tabindex="-1" style="font-size:12pt;height:30px" name="owner" id="owner" value="'.$swapp_table_info1->owner.'" style="width:300px"></td>';
            echo '<td><label for="owner">*</label></td>';
            echo '</tr>';
        }
        if ($flag_de != 'Query')
        {
            if ($_SESSION['lng']=="English")
            {
                echo '<tr>';
                echo '<td><label for="tablename" class="thick">Table Name</label></td>';
                echo '</tr>';
            }
            else
            {
                echo '<tr>';
                echo '<td><label for="tablename" class="thick">टेबलचे नाव</label></td>';
                echo '</tr>';
            }
            echo '<tr>';
            echo '<td><input type="text" readonly="readonly" tabindex="-1" style="font-size:12pt;height:30px" name="tablename" id="tablename" value="'.$swapp_table_info1->tablename.'" style="width:300px"></td>';
            echo '<td><label for="tablename">*</label></td>';
            echo '</tr>';
        }
        if ($flag_de != 'Query')
        {
            if ($_SESSION['lng']=="English")
            {
                echo '<tr>';
                echo '<td><label for="columid" class="thick">Column Id</label></td>';
                echo '</tr>';
            }
            else
            {
                echo '<tr>';
                echo '<td><label for="columid" class="thick">कॉलम नंबर</label></td>';
                echo '</tr>';
            }
            echo '<tr>';
            echo '<td><input type="text" readonly="readonly" tabindex="-1" style="font-size:12pt;height:30px" name="columid" id="columid" value="'.$swapp_table_info1->columid.'" style="width:300px"></td>';
            echo '<td><label for="columid">*</label></td>';
            echo '</tr>';
        }
        if ($flag_de != 'Query')
        {
            if ($_SESSION['lng']=="English")
            {
                echo '<tr>';
                echo '<td><label for="fieldname" class="thick">Field Name</label></td>';
                echo '</tr>';
            }
            else
            {
                echo '<tr>';
                echo '<td><label for="fieldname" class="thick">फिल्डचे नाव</label></td>';
                echo '</tr>';
            }
            echo '<tr>';
            echo '<td><input type="text" readonly="readonly" tabindex="-1" style="font-size:12pt;height:30px" name="fieldname" id="fieldname" value="'.$swapp_table_info1->fieldname.'" style="width:300px"></td>';
            echo '<td><label for="fieldname">*</label></td>';
            echo '</tr>';
        }
        if ($flag_de != 'Query')
        {
            if ($_SESSION['lng']=="English")
            {
                echo '<tr>';
                echo '<td><label for="data_type" class="thick">Data Type</label></td>';
                echo '</tr>';
            }
            else
            {
                echo '<tr>';
                echo '<td><label for="data_type" class="thick">डेटा प्रकार</label></td>';
                echo '</tr>';
            }
            echo '<tr>';
            $query1 = "select 'NUMBER' as code,'NUMBER' as name_eng,'आकडे' as name_unicode from dual
            union all
            select 'VARCHAR2' as code,'VARCHAR2' as name_eng,'अक्षरी' as name_unicode from dual
            union all
            select 'DATE' as code,'DATE' as name_eng,'दिनांक' as name_unicode from dual
            ";
            $result1 = oci_parse($connection, $query1);
            $r = oci_execute($result1);
            echo '<tr>';
            echo '<td><select name="data_type" id="data_type" style="height:35px;font-size:14px;">';
            /* if ($_SESSION['lng']=="English")
            {
                echo '<option value="0">[Select]</option>';
            }
            else
            {
                echo '<option value="0">[निवडा]</option>';
            } */
            while ($row1 = oci_fetch_array($result1,OCI_ASSOC+OCI_RETURN_NULLS))
            {
                if ($_SESSION['lng']=="English")
                {
                    if ($row1['CODE']==$swapp_table_info1->data_type)
                    {
                        echo '<option value="'.$row1['CODE'].'" Selected>'.$row1['NAME_ENG'].'</option>';
                    }
                    else
                    {
                        echo '<option value="'.$row1['CODE'].'">'.$row1['NAME_ENG'].'</option>';
                    }
                 }
                 else
                 {
                     if ($row1['CODE']==$swapp_table_info1->data_type)
                     {
                         echo'<option value="'.$row1['CODE'].'" Selected>'.$row1['NAME_UNICODE'].'</option>';
                     }
                     else
                     {
                         echo '<option value="'.$row1['CODE'].'">'.$row1['NAME_UNICODE'].'</option>';
                     }
                 }
             }
             echo '</select>';
            echo '<td><label for="data_type">*</label></td>';
             echo '</tr>';
        }
        if ($flag_de != 'Query')
        {
            if ($_SESSION['lng']=="English")
            {
                echo '<tr>';
                echo '<td><label for="iscompulsory" class="thick">Is Compulsory</label></td>';
                echo '</tr>';
            }
            else
            {
                echo '<tr>';
                echo '<td><label for="iscompulsory" class="thick">आवश्यक आहे?</label></td>';
                echo '</tr>';
            }
            echo '<tr>';
            $query1 = "select 1 as code,'Yes' as name_eng,'होय' as name_unicode from dual
            union all
            select 0 as code,'No' as name_eng,'नाही' as name_unicode from dual";
            $result1 = oci_parse($connection, $query1);
            $r = oci_execute($result1);
            echo '<tr>';
            echo '<td><select name="iscompulsory" id="iscompulsory" style="height:35px;font-size:14px;">';
            /* if ($_SESSION['lng']=="English")
            {
                echo '<option value="0">[Select]</option>';
            }
            else
            {
                echo '<option value="0">[निवडा]</option>';
            } */
            while ($row1 = oci_fetch_array($result1,OCI_ASSOC+OCI_RETURN_NULLS))
            {
                if ($_SESSION['lng']=="English")
                {
                    if ($row1['CODE']==$swapp_table_info1->iscompulsory)
                    {
                        echo '<option value="'.$row1['CODE'].'" Selected>'.$row1['NAME_ENG'].'</option>';
                    }
                    else
                    {
                        echo '<option value="'.$row1['CODE'].'">'.$row1['NAME_ENG'].'</option>';
                    }
                 }
                 else
                 {
                     if ($row1['CODE']==$swapp_table_info1->iscompulsory)
                     {
                         echo'<option value="'.$row1['CODE'].'" Selected>'.$row1['NAME_UNICODE'].'</option>';
                     }
                     else
                     {
                         echo '<option value="'.$row1['CODE'].'">'.$row1['NAME_UNICODE'].'</option>';
                     }
                 }
             }
             echo '</select>';
            echo '<td><label for="iscompulsory">*</label></td>';
             echo '</tr>';
        }
        if ($flag_de != 'Query')
        {
            if ($_SESSION['lng']=="English")
            {
                echo '<tr>';
                echo '<td><label for="dependoncolumid" class="thick">Depend on Column Id</label></td>';
                echo '</tr>';
            }
            else
            {
                echo '<tr>';
                echo '<td><label for="dependoncolumid" class="thick">कॉलम नंबर वर अवलंबून</label></td>';
                echo '</tr>';
            }
            echo '<tr>';
            echo '<td><input type="text" style="font-size:12pt;height:30px" name="dependoncolumid" id="dependoncolumid" value="'.$swapp_table_info1->dependoncolumid.'" style="width:300px"></td>';
            echo '</tr>';
        }

        if ($flag_de != 'Query')
        {
            if ($_SESSION['lng']=="English")
            {
                echo '<tr>';
                echo '<td><label for="entry_para_maxg_cal" class="thick">Input Data</label></td>';
                echo '</tr>';
            }
            else
            {
                echo '<tr>';
                echo '<td><label for="entry_para_maxg_cal" class="thick">इनपुट माहिती</label></td>';
                echo '</tr>';
            }
            echo '<tr>';
            $query1 = "select 0 as code,'Entry' as name_eng,'भरणे' as name_unicode from dual
            union all
            select 1 as code,'Parameter' as name_eng,'पॅरामीटर' as name_unicode from dual
            union all
            select 2 as code,'Max' as name_eng,'मॅक्स' as name_unicode from dual
            union all
            select 3 as code,'Calculation' as name_eng,'कॅलक्युलेशन' as name_unicode from dual
            ";

            $result1 = oci_parse($connection, $query1);
            $r = oci_execute($result1);
            echo '<tr>';
            echo '<td><select name="entry_para_maxg_cal" id="entry_para_maxg_cal" style="height:35px;font-size:14px;">';
            /* if ($_SESSION['lng']=="English")
            {
                echo '<option value="0">[Select]</option>';
            }
            else
            {
                echo '<option value="0">[निवडा]</option>';
            } */
            while ($row1 = oci_fetch_array($result1,OCI_ASSOC+OCI_RETURN_NULLS))
            {
                if ($_SESSION['lng']=="English")
                {
                    if ($row1['CODE']==$swapp_table_info1->entry_para_maxg_cal)
                    {
                        echo '<option value="'.$row1['CODE'].'" Selected>'.$row1['NAME_ENG'].'</option>';
                    }
                    else
                    {
                        echo '<option value="'.$row1['CODE'].'">'.$row1['NAME_ENG'].'</option>';
                    }
                 }
                 else
                 {
                     if ($row1['CODE']==$swapp_table_info1->entry_para_maxg_cal)
                     {
                         echo'<option value="'.$row1['CODE'].'" Selected>'.$row1['NAME_UNICODE'].'</option>';
                     }
                     else
                     {
                         echo '<option value="'.$row1['CODE'].'">'.$row1['NAME_UNICODE'].'</option>';
                     }
                 }
             }
             echo '</select>';
            echo '<td><label for="entry_para_maxg_cal">*</label></td>';
             echo '</tr>';
        }
        echo '</table>';
        echo '</div>';
        echo '<div style="width:300px;float:left">';
        echo '<table border="0">';
        if ($flag_de != 'Query')
        {
            if ($_SESSION['lng']=="English")
            {
                echo '<tr>';
                echo '<td><label for="engdesc" class="thick">Name (English)</label></td>';
                echo '</tr>';
            }
            else
            {
                echo '<tr>';
                echo '<td><label for="engdesc" class="thick">नाव (इंग्रजी)</label></td>';
                echo '</tr>';
            }
            echo '<tr>';
            echo '<td><input autocomplete=off type="text" style="font-size:12pt;height:30px" name="engdesc" id="engdesc" value="'.$swapp_table_info1->engdesc.'" style="width:300px"></td>';
            echo '<td><label for="engdesc">*</label></td>';
            echo '</tr>';
        }
        if ($flag_de != 'Query')
        {
            if ($_SESSION['lng']=="English")
            {
                echo '<tr>';
                echo '<td><label for="unicodedesc" class="thick">Name (Unicode)</label></td>';
                echo '</tr>';
            }
            else
            {
                echo '<tr>';
                echo '<td><label for="unicodedesc" class="thick">नाव (मराठी)</label></td>';
                echo '</tr>';
            }
            echo '<tr>';
            echo '<td><input autocomplete=off type="text" style="font-size:12pt;height:30px" name="unicodedesc" id="unicodedesc" value="'.$swapp_table_info1->unicodedesc.'" style="width:300px"></td>';
            echo '<td><label for="unicodedesc">*</label></td>';
            echo '</tr>';
        }
        if ($flag_de != 'Query')
        {
            if ($_SESSION['lng']=="English")
            {
                echo '<tr>';
                echo '<td><label for="iscombo" class="thick">Input Control Type</label></td>';
                echo '</tr>';
            }
            else
            {
                echo '<tr>';
                echo '<td><label for="iscombo" class="thick">इनपूट कंट्रोल प्रकार</label></td>';
                echo '</tr>';
            }
            echo '<tr>';
            $query1 = "select 0 as code,'TextBox' as name_eng,'टेक्स्ट बाॅक्स' as name_unicode from dual
            union all
            select 1 as code,'List Combo' as name_eng,'लिस्ट कोम्बो' as name_unicode from dual
            union all
            select 2 as code,'Text Combo' as name_eng,'टेक्स्ट कोम्बो' as name_unicode from dual
            union all
            select 3 as code,'Boolean List Combo' as name_eng,'बुलियन लिस्ट कोम्बो' as name_unicode from dual";
            $result1 = oci_parse($connection, $query1);
            $r = oci_execute($result1);
            echo '<tr>';
            echo '<td><select name="iscombo" id="iscombo" style="height:35px;font-size:14px;">';
            /* if ($_SESSION['lng']=="English")
            {
                echo '<option value="0">[Select]</option>';
            }
            else
            {
                echo '<option value="0">[निवडा]</option>';
            } */
            while ($row1 = oci_fetch_array($result1,OCI_ASSOC+OCI_RETURN_NULLS))
            {
                if ($_SESSION['lng']=="English")
                {
                    if ($row1['CODE']==$swapp_table_info1->iscombo)
                    {
                        echo '<option value="'.$row1['CODE'].'" Selected>'.$row1['NAME_ENG'].'</option>';
                    }
                    else
                    {
                        echo '<option value="'.$row1['CODE'].'">'.$row1['NAME_ENG'].'</option>';
                    }
                 }
                 else
                 {
                     if ($row1['CODE']==$swapp_table_info1->iscombo)
                     {
                         echo'<option value="'.$row1['CODE'].'" Selected>'.$row1['NAME_UNICODE'].'</option>';
                     }
                     else
                     {
                         echo '<option value="'.$row1['CODE'].'">'.$row1['NAME_UNICODE'].'</option>';
                     }
                 }
             }
             echo '</select>';
             echo '</tr>';
        }
        if ($flag_de != 'Query')
        {
            if ($_SESSION['lng']=="English")
            {
                echo '<tr>';
                echo '<td><label for="combotableowner" class="thick">Combo Table Owner</label></td>';
                echo '</tr>';
            }
            else
            {
                echo '<tr>';
                echo '<td><label for="combotableowner" class="thick">कंबो टेबल ओनर</label></td>';
                echo '</tr>';
            }
            echo '<tr>';
            echo '<td><input class="advancedSearchTextBox" type="text" style="font-size:12pt;height:30px" name="combotableowner" id="combotableowner" value="'.$swapp_table_info1->combotableowner.'" style="width:300px"></td>';
            echo '</tr>';
        }
        if ($flag_de != 'Query')
        {
            if ($_SESSION['lng']=="English")
            {
                echo '<tr>';
                echo '<td><label for="combotable" class="thick">Combo Table</label></td>';
                echo '</tr>';
            }
            else
            {
                echo '<tr>';
                echo '<td><label for="combotable" class="thick">कंबो टेबल</label></td>';
                echo '</tr>';
            }
            echo '<tr>';
            echo '<td><input class="advancedSearchTextBox" type="text" style="font-size:12pt;height:30px" name="combotable" id="combotable" value="'.$swapp_table_info1->combotable.'" style="width:300px"></td>';
            echo '</tr>';
        }
        if ($flag_de != 'Query')
        {
            if ($_SESSION['lng']=="English")
            {
                echo '<tr>';
                echo '<td><label for="comboengfield" class="thick">Combo Name (English)</label></td>';
                echo '</tr>';
            }
            else
            {
                echo '<tr>';
                echo '<td><label for="comboengfield" class="thick">कंबो नाव (इंग्रजी)</label></td>';
                echo '</tr>';
            }
            echo '<tr>';
            echo '<td><input type="text" style="font-size:12pt;height:30px" name="comboengfield" id="comboengfield" value="'.$swapp_table_info1->comboengfield.'" style="width:300px"></td>';
            echo '</tr>';
        }
        if ($flag_de != 'Query')
        {
            if ($_SESSION['lng']=="English")
            {
                echo '<tr>';
                echo '<td><label for="combounicodefield" class="thick">Combo Name (Unicode)</label></td>';
                echo '</tr>';
            }
            else
            {
                echo '<tr>';
                echo '<td><label for="combounicodefield" class="thick">कंबो नाव (मराठी)</label></td>';
                echo '</tr>';
            }
            echo '<tr>';
            echo '<td><input type="text" style="font-size:12pt;height:30px" name="combounicodefield" id="combounicodefield" value="'.$swapp_table_info1->combounicodefield.'" style="width:300px"></td>';
            echo '</tr>';
        }
        if ($flag_de != 'Query')
        {
            if ($_SESSION['lng']=="English")
            {
                echo '<tr>';
                echo '<td><label for="combodatafield" class="thick">Combo Data Field</label></td>';
                echo '</tr>';
            }
            else
            {
                echo '<tr>';
                echo '<td><label for="combodatafield" class="thick">कंबो नाव डेटा फिल्ड</label></td>';
                echo '</tr>';
            }
            echo '<tr>';
            echo '<td><input type="text" style="font-size:12pt;height:30px" name="combodatafield" id="combodatafield" value="'.$swapp_table_info1->combodatafield.'" style="width:300px"></td>';
            echo '</tr>';
        }
        if ($flag_de != 'Query')
        {
            if ($_SESSION['lng']=="English")
            {
                echo '<tr>';
                echo '<td><label for="combotablecondition" class="thick">Combotable Condition</label></td>';
                echo '</tr>';
            }
            else
            {
                echo '<tr>';
                echo '<td><label for="combotablecondition" class="thick">कंबो कंडिशन</label></td>';
                echo '</tr>';
            }
            echo '<tr>';
            echo '<td><input type="text" style="font-size:12pt;height:30px" name="combotablecondition" id="combotablecondition" value="'.$swapp_table_info1->combotablecondition.'" style="width:300px"></td>';
            echo '</tr>';
        }
        echo '</table>';
        echo '</div>';
        echo '<div style="width:300px;float:left">';
        echo '<table border="0">';
        if ($flag_de != 'Query')
        {
            if ($_SESSION['lng']=="English")
            {
                echo '<tr>';
                echo '<td><label for="isprimarykey" class="thick">Is Primary</label></td>';
                echo '</tr>';
            }
            else
            {
                echo '<tr>';
                echo '<td><label for="isprimarykey" class="thick">प्रायमरी आहे?</label></td>';
                echo '</tr>';
            }
            echo '<tr>';
            $query1 = "select 1 as code,'Yes' as name_eng,'होय' as name_unicode from dual
            union all
            select 0 as code,'No' as name_eng,'नाही' as name_unicode from dual";
            $result1 = oci_parse($connection, $query1);
            $r = oci_execute($result1);
            echo '<tr>';
            echo '<td><select name="isprimarykey" id="isprimarykey" style="height:35px;font-size:14px;">';
            /* if ($_SESSION['lng']=="English")
            {
                echo '<option value="0">[Select]</option>';
            }
            else
            {
                echo '<option value="0">[निवडा]</option>';
            } */
            while ($row1 = oci_fetch_array($result1,OCI_ASSOC+OCI_RETURN_NULLS))
            {
                if ($_SESSION['lng']=="English")
                {
                    if ($row1['CODE']==$swapp_table_info1->isprimarykey)
                    {
                        echo '<option value="'.$row1['CODE'].'" Selected>'.$row1['NAME_ENG'].'</option>';
                    }
                    else
                    {
                        echo '<option value="'.$row1['CODE'].'">'.$row1['NAME_ENG'].'</option>';
                    }
                 }
                 else
                 {
                     if ($row1['CODE']==$swapp_table_info1->isprimarykey)
                     {
                         echo'<option value="'.$row1['CODE'].'" Selected>'.$row1['NAME_UNICODE'].'</option>';
                     }
                     else
                     {
                         echo '<option value="'.$row1['CODE'].'">'.$row1['NAME_UNICODE'].'</option>';
                     }
                 }
             }
             echo '</select>';
             echo '</tr>';
        }
        if ($flag_de != 'Query')
        {
            if ($_SESSION['lng']=="English")
            {
                echo '<tr>';
                echo '<td><label for="isadddisplay" class="thick">Is Add Display</label></td>';
                echo '</tr>';
            }
            else
            {
                echo '<tr>';
                echo '<td><label for="isadddisplay" class="thick">नवीन दाखवायचे?</label></td>';
                echo '</tr>';
            }
            echo '<tr>';
            $query1 = "select 1 as code,'Yes' as name_eng,'होय' as name_unicode from dual
            union all
            select 0 as code,'No' as name_eng,'नाही' as name_unicode from dual";
            $result1 = oci_parse($connection, $query1);
            $r = oci_execute($result1);
            echo '<tr>';
            echo '<td><select name="isadddisplay" id="isadddisplay" style="height:35px;font-size:14px;">';
            /* if ($_SESSION['lng']=="English")
            {
                echo '<option value="0">[Select]</option>';
            }
            else
            {
                echo '<option value="0">[निवडा]</option>';
            } */
            while ($row1 = oci_fetch_array($result1,OCI_ASSOC+OCI_RETURN_NULLS))
            {
                if ($_SESSION['lng']=="English")
                {
                    if ($row1['CODE']==$swapp_table_info1->isadddisplay)
                    {
                        echo '<option value="'.$row1['CODE'].'" Selected>'.$row1['NAME_ENG'].'</option>';
                    }
                    else
                    {
                        echo '<option value="'.$row1['CODE'].'">'.$row1['NAME_ENG'].'</option>';
                    }
                 }
                 else
                 {
                     if ($row1['CODE']==$swapp_table_info1->isadddisplay)
                     {
                         echo'<option value="'.$row1['CODE'].'" Selected>'.$row1['NAME_UNICODE'].'</option>';
                     }
                     else
                     {
                         echo '<option value="'.$row1['CODE'].'">'.$row1['NAME_UNICODE'].'</option>';
                     }
                 }
             }
             echo '</select>';
             echo '</tr>';
        }
        if ($flag_de != 'Query')
        {
            if ($_SESSION['lng']=="English")
            {
                echo '<tr>';
                echo '<td><label for="isreadonly" class="thick">Is Readonly</label></td>';
                echo '</tr>';
            }
            else
            {
                echo '<tr>';
                echo '<td><label for="isreadonly" class="thick">रीड ओनली?</label></td>';
                echo '</tr>';
            }
            echo '<tr>';
            $query1 = "select 1 as code,'Yes' as name_eng,'होय' as name_unicode from dual
            union all
            select 0 as code,'No' as name_eng,'नाही' as name_unicode from dual";
            $result1 = oci_parse($connection, $query1);
            $r = oci_execute($result1);
            echo '<tr>';
            echo '<td><select name="isreadonly" id="isreadonly" style="height:35px;font-size:14px;">';
            /* if ($_SESSION['lng']=="English")
            {
                echo '<option value="0">[Select]</option>';
            }
            else
            {
                echo '<option value="0">[निवडा]</option>';
            } */
            while ($row1 = oci_fetch_array($result1,OCI_ASSOC+OCI_RETURN_NULLS))
            {
                if ($_SESSION['lng']=="English")
                {
                    if ($row1['CODE']==$swapp_table_info1->isreadonly)
                    {
                        echo '<option value="'.$row1['CODE'].'" Selected>'.$row1['NAME_ENG'].'</option>';
                    }
                    else
                    {
                        echo '<option value="'.$row1['CODE'].'">'.$row1['NAME_ENG'].'</option>';
                    }
                 }
                 else
                 {
                     if ($row1['CODE']==$swapp_table_info1->isreadonly)
                     {
                         echo'<option value="'.$row1['CODE'].'" Selected>'.$row1['NAME_UNICODE'].'</option>';
                     }
                     else
                     {
                         echo '<option value="'.$row1['CODE'].'">'.$row1['NAME_UNICODE'].'</option>';
                     }
                 }
             }
             echo '</select>';
             echo '</tr>';
        }
        if ($flag_de != 'Query')
        {
            if ($_SESSION['lng']=="English")
            {
                echo '<tr>';
                echo '<td><label for="isfinddisplay" class="thick">Is Find/Display</label></td>';
                echo '</tr>';
            }
            else
            {
                echo '<tr>';
                echo '<td><label for="isfinddisplay" class="thick">शोधल्यावर दाखवायचे?</label></td>';
                echo '</tr>';
            }
            echo '<tr>';
            $query1 = "select 1 as code,'Yes' as name_eng,'होय' as name_unicode from dual
            union all
            select 0 as code,'No' as name_eng,'नाही' as name_unicode from dual";
            $result1 = oci_parse($connection, $query1);
            $r = oci_execute($result1);
            echo '<tr>';
            echo '<td><select name="isfinddisplay" id="isfinddisplay" style="height:35px;font-size:14px;">';
            /* if ($_SESSION['lng']=="English")
            {
                echo '<option value="0">[Select]</option>';
            }
            else
            {
                echo '<option value="0">[निवडा]</option>';
            } */
            while ($row1 = oci_fetch_array($result1,OCI_ASSOC+OCI_RETURN_NULLS))
            {
                if ($_SESSION['lng']=="English")
                {
                    if ($row1['CODE']==$swapp_table_info1->isfinddisplay)
                    {
                        echo '<option value="'.$row1['CODE'].'" Selected>'.$row1['NAME_ENG'].'</option>';
                    }
                    else
                    {
                        echo '<option value="'.$row1['CODE'].'">'.$row1['NAME_ENG'].'</option>';
                    }
                 }
                 else
                 {
                     if ($row1['CODE']==$swapp_table_info1->isfinddisplay)
                     {
                         echo'<option value="'.$row1['CODE'].'" Selected>'.$row1['NAME_UNICODE'].'</option>';
                     }
                     else
                     {
                         echo '<option value="'.$row1['CODE'].'">'.$row1['NAME_UNICODE'].'</option>';
                     }
                 }
             }
             echo '</select>';
             echo '</tr>';
        }
        if ($flag_de != 'Query')
        {
            if ($_SESSION['lng']=="English")
            {
                echo '<tr>';
                echo '<td><label for="isqueryinput" class="thick">Is Query/Input</label></td>';
                echo '</tr>';
            }
            else
            {
                echo '<tr>';
                echo '<td><label for="isqueryinput" class="thick">शोधण्यासाठी पॅरामीटर?</label></td>';
                echo '</tr>';
            }
            echo '<tr>';
            $query1 = "select 1 as code,'For English' as name_eng,'होय' as name_unicode from dual
            union all
            select 0 as code,'No' as name_eng,'नाही' as name_unicode from dual";
            $result1 = oci_parse($connection, $query1);
            $r = oci_execute($result1);
            echo '<tr>';
            echo '<td><select name="isqueryinput" id="isqueryinput" style="height:35px;font-size:14px;">';
            /* if ($_SESSION['lng']=="English")
            {
                echo '<option value="0">[Select]</option>';
            }
            else
            {
                echo '<option value="0">[निवडा]</option>';
            } */
            while ($row1 = oci_fetch_array($result1,OCI_ASSOC+OCI_RETURN_NULLS))
            {
                if ($_SESSION['lng']=="English")
                {
                    if ($row1['CODE']==$swapp_table_info1->isqueryinput)
                    {
                        echo '<option value="'.$row1['CODE'].'" Selected>'.$row1['NAME_ENG'].'</option>';
                    }
                    else
                    {
                        echo '<option value="'.$row1['CODE'].'">'.$row1['NAME_ENG'].'</option>';
                    }
                 }
                 else
                 {
                     if ($row1['CODE']==$swapp_table_info1->isqueryinput)
                     {
                         echo'<option value="'.$row1['CODE'].'" Selected>'.$row1['NAME_UNICODE'].'</option>';
                     }
                     else
                     {
                         echo '<option value="'.$row1['CODE'].'">'.$row1['NAME_UNICODE'].'</option>';
                     }
                 }
             }
             echo '</select>';
             echo '</tr>';
        }
        if ($flag_de != 'Query')
        {
            if ($_SESSION['lng']=="English")
            {
                echo '<tr>';
                echo '<td><label for="islistquery" class="thick">List Query</label></td>';
                echo '</tr>';
            }
            else
            {
                echo '<tr>';
                echo '<td><label for="islistquery" class="thick">लिस्टमध्ये</label></td>';
                echo '</tr>';
            }
            echo '<tr>';
            $query1 = "select 0 as code,'No' as name_eng,'नाही' as name_unicode from dual
            union all
            select 1 as code,'For English' as name_eng,'इंग्रजीसाठी' as name_unicode from dual
            union all
            select 2 as code,'for Unicode' as name_eng,'मराठीसाठी' as name_unicode from dual
            union all
            select 3 as code,'for English/Unicode' as name_eng,'इंग्रजी/मराठीसाठी' as name_unicode from dual";
            $result1 = oci_parse($connection, $query1);
            $r = oci_execute($result1);
            echo '<tr>';
            echo '<td><select name="islistquery" id="islistquery" style="height:35px;font-size:14px;">';
            /* if ($_SESSION['lng']=="English")
            {
                echo '<option value="0">[Select]</option>';
            }
            else
            {
                echo '<option value="0">[निवडा]</option>';
            } */
            while ($row1 = oci_fetch_array($result1,OCI_ASSOC+OCI_RETURN_NULLS))
            {
                if ($_SESSION['lng']=="English")
                {
                    if ($row1['CODE']==$swapp_table_info1->islistquery)
                    {
                        echo '<option value="'.$row1['CODE'].'" Selected>'.$row1['NAME_ENG'].'</option>';
                    }
                    else
                    {
                        echo '<option value="'.$row1['CODE'].'">'.$row1['NAME_ENG'].'</option>';
                    }
                 }
                 else
                 {
                     if ($row1['CODE']==$swapp_table_info1->islistquery)
                     {
                         echo'<option value="'.$row1['CODE'].'" Selected>'.$row1['NAME_UNICODE'].'</option>';
                     }
                     else
                     {
                         echo '<option value="'.$row1['CODE'].'">'.$row1['NAME_UNICODE'].'</option>';
                     }
                 }
             }
             echo '</select>';
             echo '</tr>';
        }
        echo '<tr>';
        echo '</tr>';
        if ($flag_de != 'Query')
        {
            if ($_SESSION['lng']=="English")
            {
                echo '<tr>';
                echo '<td><label for="div" class="thick">DIV</label></td>';
                echo '</tr>';
            }
            else
            {
                echo '<tr>';
                echo '<td><label for="div" class="thick">डीआयव्ही</label></td>';
                echo '</tr>';
            }
            echo '<tr>';
            echo '<td><input type="text" style="font-size:12pt;height:30px" name="div" id="div" value="'.$swapp_table_info1->div.'" style="width:300px"></td>';
            echo '</tr>';
        }
        if ($flag_de != 'Query')
        {
            if ($_SESSION['lng']=="English")
            {
                echo '<tr>';
                echo '<td><label for="sequencenumber" class="thick">Sequence Number</label></td>';
                echo '</tr>';
            }
            else
            {
                echo '<tr>';
                echo '<td><label for="sequencenumber" class="thick">क्रम</label></td>';
                echo '</tr>';
            }
            echo '<tr>';
            echo '<td><input type="text" style="font-size:12pt;height:30px" name="sequencenumber" id="sequencenumber" value="'.$swapp_table_info1->sequencenumber.'" style="width:300px"></td>';
            echo '</tr>';
        }
        echo '<tr>';
        echo '<td><input class="error" type="hidden" style="font-size:12pt;height:30px" name="error" id="error" value="error" style="width:300px"></td>';
        echo '</tr>';
        if (($_SESSION['responsibilitycode']==$addresponsibilityid or $_SESSION['responsibilitycode']==$alterresponsibilityid) and $flag_de=='Query')
        {
            echo '<tr>';
            echo '<td><input class="button123" type="submit" name="btn" value="Display" style="width:100px"></td>';
            echo '</tr>';
        }
        elseif ($_SESSION['responsibilitycode']==$alterresponsibilityid and $swapp_table_info1->found==true)
        {
            echo '<tr>';
            echo '<td><input class="button123" type="submit" name="btn" value="Change" style="width:100px"></td>';
            echo '</tr>';
            echo '<tr>';
            echo '<td><input class="button123" type="submit" name="btn" value="Delete" style="width:100px"></td>';
            echo '</tr>';
        }
        elseif (($_SESSION['responsibilitycode']==$addresponsibilityid or $_SESSION['responsibilitycode']==$alterresponsibilityid) and $swapp_table_info1->found==false)
        {
            echo '<tr>';
            echo '<td><input class="button123" type="submit" name="btn" value="Add" style="width:100px"></td>';
            echo '</tr>';
        }
        echo '</table>';
        echo '</form>';
        echo '</section>';
    ?>
    </article>
    <footer>
    </footer>
    </body>
</html>