<?php
    //This is generated by Swapp Software Application on 06/06/2019 11:50:16 AM for PHP
    require_once("../info/phpsqlajax_dbinfo.php");
    require_once("../info/phpgetloginview.php");
    require_once("../info/routine.php");
    $connection =swapp_connection();
    $searchTerm = $_GET['term'];
    if (preg_match('/^[0-9]*$/', $searchTerm))
    {
    }
    elseif ((strlen($searchTerm)<3) and $searchTerm != '**')
    {
        exit;
    }
   if ($searchTerm == '**')
   {
       $query = "SELECT USERNAME FROM all_users and rownum <= 10";
   }
   else
   {
       $query = "SELECT USERNAME FROM all_users
       where upper(username) like upper('%".$searchTerm."%') and rownum <= 10";
   }
   $result = oci_parse($connection, $query); $r = oci_execute($result);
   $r = oci_execute($result);
   while ($row = oci_fetch_array($result,OCI_ASSOC+OCI_RETURN_NULLS))
   {
        $id=$row['USERNAME'];
        $name=$row['USERNAME'];
        $data[] = array( 
           'id' => $id
           ,'label' => $name
           ,'value' => $name
           );
   }
   //return json data
   echo json_encode($data);
?>