<?php
    //This is generated by Swapp Software Application on 12/12/2020 10:07:02 am for PHP
    require_once("../info/phpsqlajax_dbinfo.php");
    require_once("../info/phpgetloginview.php");
    require_once("../info/routine.php");
    $connection =swapp_connection();
    $searchTerm = $_GET['term'];
    $mainstorecode = $_GET['mainstorecode'];

    if (preg_match('/^[0-9]*$/', $searchTerm))
    {
    }
    elseif (strlen($searchTerm)<3 and $searchTerm != '**')
    {
        exit;
    }
    $cond='1=1';
    if ($mainstorecode!='')
    {
        $cond = $cond.' and mainstorecode='.$mainstorecode;
    }
   if ($searchTerm == '**')
   {
       $query = "select SUBSTORECODE,
       SUBSTORENAMEUNI,
       SUBSTORENAMEENG
       from SUBSTORE where ".$cond." order by SUBSTORENAMEENG";
   }
   else
   {
       $query = "select SUBSTORECODE,
       SUBSTORENAMEUNI,
       SUBSTORENAMEENG
       from SUBSTORE where (upper(SUBSTORENAMEENG) like upper('%".$searchTerm."%')
       or SUBSTORENAMEUNI like '%".$searchTerm."%'
       or to_char(SUBSTORECODE) like '".$searchTerm."') and ".$cond.
       " order by SUBSTORENAMEENG";
   }
   $result = oci_parse($connection, $query); $r = oci_execute($result);
   while ($row = oci_fetch_array($result,OCI_ASSOC+OCI_RETURN_NULLS))
   {
       $id = $row['SUBSTORECODE'];
       if ($_SESSION['lng'] == "English")
       {
           $name = $row['SUBSTORENAMEENG'];
       }
       else
       {
           $name = $row['SUBSTORENAMEUNI'];
       }
       $data[] = array( 
           'id' => $id
           ,'label' => $name
           ,'value' => $name
           );
   }
   //return json data
   echo json_encode($data);
?>

