<?php
    //This is generated by Swapp Software Application on 23/10/2018 06:50:03 PM for PHP
    require("../info/phpgetloginview.php");
    include("../info/ncryptdcrypt.php");
    require("../info/routine.php");
    include("../ip_model/saledetail_db_oracle.php");
    $connection=petrolpump_connection();
    $saledetail1 = new saledetail($connection);
    $saledetail1->itemcode = $_POST["itemcode"];
    $saledetail1->qty = $_POST["qty"];
    $saledetail1->rate = $_POST["rate"];
		$saledetail1->amount = $_POST["amount"];
    $saledetail1->reftransactionid = $_POST["reftransactionid"];
    $saledetail1->wbslipnumber = $_POST["wbslipnumber"];
    $saledetail1->maxqty = $_POST["maxqty"];
    $flag_de = fnDecrypt($_GET['flag']);

    $shiftcode_en = fnEncrypt($_POST['shiftcode']);
    $transactioncategoryid_en = fnEncrypt($_POST['transactioncategoryid']);
    $reftransactionid_en = fnEncrypt($_POST['reftransactionid']);
    $transactionid_en = fnEncrypt($_POST['transactionid']);
    

  switch ($_POST['btn'])
  {
    case 'Add':
      $ret = $saledetail1->insert();
      if ($ret==1)
      {
         oci_commit($connection);
         echo '<span class="w3-container" style="background-color:#0a0;color:#ff8;text-align:left;">saledetail is added successfully</span></br>';
         //echo '<a href="../ip_view/saledetail.php?customercode='.fnEncrypt($saledetail1->customercode).'">Add/Display saledetail</a></br>';
         $flag_en = fnEncrypt('Display');
				 header("Location:../ip_view/saleheader.php?shiftcode='.$shiftcode_en.'&transactioncategoryid='.$transactioncategoryid_en.'&transactionid='.$reftransactionid_en.'&flag='.$flag_en.'"); /* Redirect browser */
         exit();
			}
      else
      {
        oci_rollback($connection);
        echo '<span style="background-color:#f44;color:#ff8;text-align:left;">'.$saledetail1->Get_invalidmessagetext().'</span></br>';
        echo '<a href="../ip_view/saleheader.php?shiftcode='.$shiftcode_en.'&transactioncategoryid='.$transactioncategoryid_en.'&transactionid='.$reftransactionid_en.'">Saledetail List</a></br>';
        
      }
      break;
    case 'Change':
      $saledetail1->transactionid = $_POST["transactionid"];
      $ret = $saledetail1->update();
      if ($ret==1)
      {
         oci_commit($connection);
         echo '<span class="w3-container" style="background-color:#0a0;color:#ff8;text-align:left;">Saledetail is Updated successfully</span></br>';  
         $flag_en = fnEncrypt('Display');
				 header("Location:../ip_view/saleheader.php?shiftcode='.$shiftcode_en.'&transactioncategoryid='.$transactioncategoryid_en.'&transactionid='.$reftransactionid_en.'&flag='.$flag_en.'"); /* Redirect browser */
         exit();
      }
      else
      {
        oci_rollback($connection);
        echo '<span style="background-color:#f44;color:#ff8;text-align:left;">'.$saledetail1->Get_invalidmessagetext().'</span></br>';
        echo '<a href="../ip_view/saleheader.php?shiftcode='.$shiftcode_en.'&transactioncategoryid='.$transactioncategoryid_en.'&transactionid='.$reftransactionid_en.'">Saledetail List</a></br>';
			}
			break;
		case 'Display':
			break;
		case 'Delete':
      $saledetail1->transactionid = $_POST["transactionid"];
			$ret = $saledetail1->delete();
			if ($ret == 1)
			{
				oci_commit($connection);
				echo '<span class="w3-container" style="background-color:#0a0;color:#ff8;text-align:left;">Saledetail is Deleted Successfully</span></br>';
				$flag_en = fnEncrypt('Display');
				header("Location:../ip_view/saleheader.php?shiftcode='.$shiftcode_en.'&transactioncategoryid='.$transactioncategoryid_en.'&transactionid='.$reftransactionid_en.'&flag='.$flag_en.'"); /* Redirect browser */
        exit();
			}
			else
			{
				oci_rollback($connection);
				echo '<span style="background-color:#f44;color:#ff8;text-align:left;">'.$saledetail1->Get_invalidmessagetext().'</span></br>';
				echo '<a href="../ip_view/saleheader.php?shiftcode='.$shiftcode_en.'&transactioncategoryid='.$transactioncategoryid_en.'&transactionid='.$reftransactionid_en.'">Saledetail List</a></br>';
			}
			break;
		default:
			echo 'Communication Error';
			break;
	}

