<?php
    //This is generated by Swapp Software Application on 23/11/2018 04:19:16 PM for PHP
    require("../info/phpsqlajax_dbinfo.php");
    require("../info/phpgetloginview.php");
    require("../info/routine.php");
    $connection =swapp_connection();
    $searchTerm = $_GET['term'];
    if (preg_match('/^[0-9]*$/', $searchTerm))
    {
    }
    elseif (strlen($searchTerm)<3 and $searchTerm != '**')
    {
        exit;
    }
   if ($searchTerm == '**')
   {
       $query = "select a.accountcode,
       accountnameuni,
       accountnameeng,
       accountclosingbalance(".$_SESSION['yearperiodcode'].",a.accountcode) as balance
       from accounthead a,accountcontroltable t 
       where (a.groupcode=t.bankgroupcode 
       or a.groupcode=t.bankgroupcode1
       or a.groupcode=t.bankgroupcode2
       )
       and rownum <= 10";
   }
   else
   {
       $query = "select a.accountcode,
       accountnameuni,
       accountnameeng,
       accountclosingbalance(".$_SESSION['yearperiodcode'].",a.accountcode) as balance
       from accounthead a,accountcontroltable t 
       where (a.groupcode=t.bankgroupcode 
       or a.groupcode=t.bankgroupcode1
       or a.groupcode=t.bankgroupcode2
       ) and (upper(accountnameeng) like upper('%".$searchTerm."%')
       or accountnameuni like '%".$searchTerm."%'
       or to_char(a.accountcode) like '".$searchTerm."'
       or refcode = '".$searchTerm."') and rownum <= 10";
   }
   $result = oci_parse($connection, $query); $r = oci_execute($result);
   $r = oci_execute($result);
   while ($row = oci_fetch_array($result,OCI_ASSOC+OCI_RETURN_NULLS))
   {
       $id = $row['ACCOUNTCODE'];
       if ($_SESSION['lng'] == "English")
       {
           $name = $row['ACCOUNTNAMEENG'];
       }
       else
       {
           $name = $row['ACCOUNTNAMEUNI'];
       }
       if ($row['BALANCE']>=0)
       {
           $balance=round($row['BALANCE'],2).' Dr';
       }
       elseif ($row['BALANCE']<0)
       {
           $balance=abs(round($row['BALANCE'],2)).' Cr';
       }
       $data[] = array( 
           'id' => $id
           ,'label' => $name
           ,'value' => $name
           ,'ledgerbalance' => $balance
           );
   }
   //return json data
   echo json_encode($data);
?>

