<?php
    //This is generated by Swapp Software Application on 11/01/2019 07:42:58 PM for PHP
    require("../info/phpsqlajax_dbinfo.php");
    require("../info/phpgetloginform.php");
    include("../info/ncryptdcrypt.php");
    require("../info/routine.php");
    require("../ip_model/passbookheader_db_oracle.php");
    //Addition or Alteration
    $addresponsibilityid=123459106;
    $alterresponsibilityid=854723695125479;
    if (isaccessible($addresponsibilityid)==0 and isaccessible($alterresponsibilityid)==0)
    {
        echo 'Communication Error';
        exit;
    }
    $transactionnumber_de = fnDecrypt($_GET['transactionnumber']);
    $flag_de = fnDecrypt($_GET['flag']);
    $connection=swapp_connection();
?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"></meta>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="../css/w3.css">
        <title>Contract</title>
        <link rel="stylesheet" href="../css/swapp123.css">
        <script src="../js/1.11.0/jquery.min.js">
         </script>
         <script>
            $(document).ready(function(){
             setInterval(function(){cache_clear()},3600000);
             });
             function cache_clear()
            {
             window.location.reload(true);
            }
        </script>
        <link rel="stylesheet" href="../css/ui/1.11.4/themes/smoothness/jquery-ui.css">
        <script src="..//js/jquery-1.10.2.js"></script>
        <script src="..//js/ui/1.11.4/jquery-ui.js"></script>
    </head>
    <body>
        <nav "w3-container">
            <ul class="navbar">
                <li><a class="navbar" href="../mis/entitymenu.php">Entity Menu</a><br/>
                <?php
                    $flag_en = fnEncrypt('Query');
                    echo '<li><a class="navbar" href="../ip_view/passbookheader.php">New Passbook Header   </a>';
                    echo '<li><a class="navbar" href="../ip_view/passbookheader.php?flag='.$flag_en.'">Find Passbook Header   </a>';
                    echo '<li><a  class="navbar" href="../../../../../sqlproc/logout.php">Log Out</a><br/>';
                ?>
            </ul>
        </nav>
        <article class="w3-container">


<?php
    $passbookheader1 = new passbookheader($connection);
    $passbookheader1->transactionnumber=$transactionnumber_de;
    $passbookheader1->fetch();
    echo '<section>';
    echo '<form method="post" action="../ip_controller/passbookheader_action.php">';
    echo '<table border="0" >';
    echo '<tr>';
    echo '<td></td>';
    echo '</tr>';
    echo '<img src="../img/createimage.php?name=Passbook Header&width=251&size=14&r=150&g=0&b=0&r1=255&g1=230&b1=0"></br></br>';
    if ($flag_de == 'Query')
    {
        echo '<img src="../img/createimage.php?name=Find Records&width=201&size=12&r=255&g=255&b=255&r1=0&g1=150&b1=0">';
    }
    elseif ($flag_de == 'Display' and $_SESSION['responsibilitycode']==$alterresponsibilityid )
    {
       echo '<img src="../img/createimage.php?name=Change/Delete Record&width=201&size=12&r=255&g=255&b=255&r1=0&g1=150&b1=0">';
    }
    elseif ($passbookheader1->found == false)
    {
       echo '<img src="../img/createimage.php?name=New Record Entry&width=201&size=12&r=255&g=255&b=255&r1=0&g1=150&b1=0">';
    }
        if ($passbookheader1->found == false or $passbookheader1->found == true or $flag_de == 'Query')
        {
            if ($_SESSION['lng']=="English")
            {
                echo '<tr>';
                echo '<td><label for="bankaccountcode" class="thick">Bank Account</label></td>';
                echo '</tr>';
            }
            else
            {
                echo '<tr>';
                echo '<td><label for="bankaccountcode" class="thick">बँक खाते</label></td>';
                echo '</tr>';
            }
            echo '<tr>';
            $query1 = "select a.accountcode as code,a.accountnameeng as name_eng,a.accountnameuni as name_unicode 
            from accounthead a,accountcontroltable t 
            where ((a.groupcode=t.bankgroupcode
            and a.subgroupcode=t.banksubgroupcode) 
            or (a.groupcode=t.bankgroupcode1)
            or (a.groupcode=t.bankgroupcode2))";
            $result1 = oci_parse($connection, $query1);
            $r = oci_execute($result1);
            echo '<tr>';
            echo '<td><select name="bankaccountcode" id="bankaccountcode" style="height:35px;font-size:14px;">';
            if ($_SESSION['lng']=="English")
            {
                echo '<option value="0">[Select]</option>';
            }
            else
            {
                echo '<option value="0">[निवडा]</option>';
            }
            while ($row1 = oci_fetch_array($result1,OCI_ASSOC+OCI_RETURN_NULLS))
            {
                if ($_SESSION['lng']=="English")
                {
                    if ($row1['CODE']==$passbookheader1->bankaccountcode)
                    {
                        echo '<option value="'.$row1['CODE'].'" Selected>'.$row1['NAME_ENG'].'</option>';
                    }
                    else
                    {
                        echo '<option value="'.$row1['CODE'].'">'.$row1['NAME_ENG'].'</option>';
                    }
                 }
                 else
                 {
                     if ($row1['CODE']==$passbookheader1->bankaccountcode)
                     {
                         echo'<option value="'.$row1['CODE'].'" Selected>'.$row1['NAME_UNICODE'].'</option>';
                     }
                     else
                     {
                         echo '<option value="'.$row1['CODE'].'">'.$row1['NAME_UNICODE'].'</option>';
                     }
                 }
             }
             echo '</select>';
            echo '<td><label for="bankaccountcode">*</label></td>';
             echo '</tr>';
        }
        if ($passbookheader1->found == false or $passbookheader1->found == true or $flag_de == 'Query')
        {
            if ($_SESSION['lng']=="English")
            {
                echo '<tr>';
                echo '<td><label for="fromdate" class="thick">From Date</label></td>';
                echo '</tr>';
            }
            else
            {
                echo '<tr>';
                echo '<td><label for="fromdate" class="thick">दिनांक पासून</label></td>';
                echo '</tr>';
            }
            echo '<tr>';
            echo '<td><input type="text" style="font-size:12pt;height:30px" name="fromdate" id="fromdate" value="'.$passbookheader1->fromdate.'" style="width:300px"></td>';
            echo '<td><label for="fromdate">*</label></td>';
            echo '</tr>';
        }
        if ($passbookheader1->found == false or $passbookheader1->found == true or $flag_de == 'Query')
        {
            if ($_SESSION['lng']=="English")
            {
                echo '<tr>';
                echo '<td><label for="todate" class="thick">To Date</label></td>';
                echo '</tr>';
            }
            else
            {
                echo '<tr>';
                echo '<td><label for="todate" class="thick">दिनांक पर्यंत</label></td>';
                echo '</tr>';
            }
            echo '<tr>';
            echo '<td><input type="text" style="font-size:12pt;height:30px" name="todate" id="todate" value="'.$passbookheader1->todate.'" style="width:300px"></td>';
            echo '<td><label for="todate">*</label></td>';
            echo '</tr>';
        }
        if ($passbookheader1->found == false or $passbookheader1->found == true or $flag_de == 'Query')
        {
            if ($_SESSION['lng']=="English")
            {
                echo '<tr>';
                echo '<td><label for="passbookopeningbalance" class="thick">Opening Balance</label></td>';
                echo '</tr>';
            }
            else
            {
                echo '<tr>';
                echo '<td><label for="passbookopeningbalance" class="thick">आरंभीची शिल्लक</label></td>';
                echo '</tr>';
            }
            echo '<tr>';
            echo '<td><input type="text" style="font-size:12pt;height:30px" name="passbookopeningbalance" id="passbookopeningbalance" value="'.$passbookheader1->passbookopeningbalance.'" style="width:300px"></td>';
            echo '<td><label for="passbookopeningbalance">*</label></td>';
            echo '</tr>';
        }
        if ($passbookheader1->found == false or $passbookheader1->found == true or $flag_de == 'Query')
        {
            if ($_SESSION['lng']=="English")
            {
                echo '<tr>';
                echo '<td><label for="passbookclosingbalance" class="thick">Closing Balance</label></td>';
                echo '</tr>';
            }
            else
            {
                echo '<tr>';
                echo '<td><label for="passbookclosingbalance" class="thick">अखेरची शिल्लक</label></td>';
                echo '</tr>';
            }
            echo '<tr>';
            echo '<td><input type="text" style="font-size:12pt;height:30px" name="passbookclosingbalance" id="passbookclosingbalance" value="'.$passbookheader1->passbookclosingbalance.'" style="width:300px"></td>';
            echo '<td><label for="passbookclosingbalance">*</label></td>';
            echo '</tr>';
        }
        echo '<tr>';
        echo '<td><input class="button123" type="hidden" style="font-size:12pt;height:30px" name="transactionnumber" id="transactionnumber" value="'.$transactionnumber_de.'" style="width:300px"></td>';
        echo '</tr>';
        if (($_SESSION['responsibilitycode']==$addresponsibilityid or $_SESSION['responsibilitycode']==$alterresponsibilityid) and $flag_de=='Query')
        {
            echo '<tr>';
            echo '<td><input class="button123" type="submit" name="btn" value="Display" style="width:100px"></td>';
            echo '</tr>';
        }
        elseif ($_SESSION['responsibilitycode']==$alterresponsibilityid and $passbookheader1->found==true)
        {
            echo '<tr>';
            echo '<td><input class="button123" type="submit" name="btn" value="Change" style="width:100px"></td>';
            echo '</tr>';
            echo '<tr>';
            echo '<td><input class="button123" type="submit" name="btn" value="Delete" style="width:100px"></td>';
            echo '</tr>';
        }
        elseif (($_SESSION['responsibilitycode']==$addresponsibilityid or $_SESSION['responsibilitycode']==$alterresponsibilityid) and $passbookheader1->found==false)
        {
            echo '<tr>';
            echo '<td><input class="button123" type="submit" name="btn" value="Add" style="width:100px"></td>';
            echo '</tr>';
        }
        echo '</table>';
        echo '</form>';
        echo '</section>';
    ?>
    </article>
    <footer>
    </footer>
    </body>
</html>

