<?php
//This is generated by Swapp Software Application on 10/11/2018 06:06:11 PM for PHP
include("../swappbase/formbase.php");
class accountgroup extends swappform
{
    Public $groupcode;
    Public $groupnameeng;
    Public $groupnameuni;
    Public $grouptypecode;
    Public $sequencenumber;
    Public $divisioncode;
    public function __construct(&$connection)
    {
     		 parent::__construct($connection);
         $this->groupcode='';
         $this->groupnameeng='';
         $this->groupnameuni='';
         $this->grouptypecode='';
	   }
    private function entryvalidation()
    {
    		$this->start_validation();
        $this->checkrequired($this->groupnameeng,'Group Name (English)');
        $this->checkrequired($this->groupnameuni,'Group Name (Unicode)');
        $this->checkrequired($this->grouptypecode,'Group Type');
        $this->checkrequired($this->divisioncode,'Division');
        $this->end_validation();
        return $this->invalidid;
	  }
    private function datavalidation()
    {
        $this->start_validation();
    		$this->invalidid=0;
    		$this->invalidmessagetext='Validated';
    		$this->end_validation();
    		return $this->invalidid;
    }
    public function insert()
    {
        $this->dataoperationmode = operationmode::Insert;
	    if ($this->entryvalidation() <> 0)
        {
            return 0;
            exit;
        }
        elseif ($this->datavalidation() <> 0)
        {
            return 0;
            exit;
        }
	    if ($this->groupcode == '')
        {
            $query = "select nvl(max(groupcode),0)+1 as groupcode from accountgroup";
            $result = oci_parse($this->connection, $query);
            $r = oci_execute($result,OCI_NO_AUTO_COMMIT);
            $row = oci_fetch_array($result,OCI_ASSOC+OCI_RETURN_NULLS);
            $this->groupcode = $row["GROUPCODE"];
        }
        $query = "
            insert into accountgroup(
            groupcode
            ,groupnameeng
            ,groupnameuni
            ,grouptypecode
            ,sequencenumber
            ,divisioncode
	        )
	        values (
            ".$this->invl($this->groupcode,true)."
            ,".$this->invl($this->groupnameeng,false)."
            ,".$this->invl($this->groupnameuni,false)."
            ,".$this->invl($this->grouptypecode,true,true)."
            ,".$this->invl($this->sequencenumber,true,true)."
            ,".$this->invl($this->divisioncode,true,true)."
            )";
        $result = oci_parse($this->connection, $query);
        if (oci_execute($result,OCI_NO_AUTO_COMMIT))
        {
            return 1;
            exit;
        }
        else
        {
            return 0;
            exit;
        }
    }
    public function display()
	  {
		    $this->dataoperationmode = operationmode::Select;
		    $cond='';
		    if ($this->groupnameeng!='')
		    {
			      if ($cond=='')
			      {
				        $cond="groupnameeng like '%".$this->groupnameeng."%'";
			       }
			       else
			       {
				         $cond=$cond." and groupnameeng like '%".$this->groupnameeng."%'";
			       }
		    }
		    if ($this->groupnameuni!='')
		    {
			      if ($cond=='')
			      {
				        $cond="groupnameuni like '%".$this->groupnameuni."%'";
			       }
			       else
			       {
				         $cond=$cond." and groupnameuni like '%".$this->groupnameuni."%'";
			       }
		    }
		    if ($this->grouptypecode!='' and $this->grouptypecode!=0)
		    {
			      if ($cond=='')
			      {
				        $cond="grouptypecode = ".$this->grouptypecode;
			       }
			       else
			       {
				         $cond=$cond." and grouptypecode = ".$this->grouptypecode;
			       }
		    }
            if ($this->divisioncode!='' and $this->divisioncode!=0)
		    {
			      if ($cond=='')
			      {
				        $cond="divisioncode = ".$this->divisioncode;
			       }
			       else
			       {
				         $cond=$cond." and divisioncode = ".$this->divisioncode;
			       }
		    }
        if ($cond!='')
		    {
		        $query = "select * from accountgroup where ".$cond." order by groupcode";
			      $result = oci_parse($this->connection, $query);
            $r = oci_execute($result,OCI_NO_AUTO_COMMIT);
			      return $result;
		     }
		     else
		     {
		         $query = "select * from accountgroup order by groupcode";
			       $result = oci_parse($this->connection, $query);
             $r = oci_execute($result,OCI_NO_AUTO_COMMIT);
			       return $result;
		     }
	  }
    public function update()
    {
        $this->dataoperationmode = operationmode::Update;
        if ($this->entryvalidation() <> 0)
        {
            return 0;
            exit;
        }
        elseif ($this->datavalidation() <> 0)
        {
            return 0;
            exit;
        }
        $query = "
        update accountgroup set 
        groupnameeng =".$this->invl($this->groupnameeng,false)."
        ,groupnameuni =".$this->invl($this->groupnameuni,false)."
        ,grouptypecode = ".$this->invl($this->grouptypecode,true)."
        ,sequencenumber = ".$this->invl($this->sequencenumber,true)."
        ,divisioncode = ".$this->invl($this->divisioncode,true)."
        where 
        groupcode = ".$this->invl($this->groupcode,true)."
        ";
        $result = oci_parse($this->connection, $query);
        if (oci_execute($result,OCI_NO_AUTO_COMMIT))
        {
            return 1;
            exit;
        }
            else
        {
            return 0;
            exit;
        }
    }
    public function delete()
    {
        $this->dataoperationmode = operationmode::Update;
        if ($this->entryvalidation() <> 0)
        {
            return 0;
            exit;
        }
        elseif ($this->datavalidation() <> 0)
        {
            return 0;
            exit;
        }
        $query = "
        delete from accountgroup
        where 
        groupcode = ".$this->invl($this->groupcode,true)."
        ";
        $result = oci_parse($this->connection, $query);
        if (oci_execute($result,OCI_NO_AUTO_COMMIT))
        {
             return 1;
             exit;
        }
        else
        {
            return 0;
            exit;
        }
    }
    public function fetch()
    {
        $this->dataoperationmode = operationmode::Select;
        $query = "select 
        groupcode
        ,groupnameeng
        ,groupnameuni
        ,grouptypecode
        ,sequencenumber
        ,divisioncode
        from ACCOUNTGROUP where 
        groupcode = ".$this->invl($this->groupcode,true)."
        ";
        $result = oci_parse($this->connection, $query);
        $r = oci_execute($result,OCI_NO_AUTO_COMMIT);
        if ($row = oci_fetch_array($result,OCI_ASSOC+OCI_RETURN_NULLS))
        {
                $this->groupcode = $row['GROUPCODE'];
                $this->groupnameeng = $row['GROUPNAMEENG'];
                $this->groupnameuni = $row['GROUPNAMEUNI'];
                $this->grouptypecode = $row['GROUPTYPECODE'];
                $this->sequencenumber = $row['SEQUENCENUMBER'];
                $this->divisioncode = $row['DIVISIONCODE'];
                $this->found=true;
                return true;
        }
        else
        {
        return false;
        }
    }
}
?>

