<?php
//This is generated by Swapp Software Application on 10/11/2018 06:06:11 PM for PHP
include("../swappbase/formbase.php");
class accountsubgroup extends swappform
{
    Public $subgroupcode;
    Public $subgroupnameeng;
    Public $subgroupnameuni;
    Public $groupcode;
    public function __construct(&$connection)
    {
     		 parent::__construct($connection);
         $this->subgroupcode='';
         $this->subgroupnameeng='';
         $this->subgroupnameuni='';
         $this->groupcode='';
	   }
    private function entryvalidation()
    {
    		$this->start_validation();
        $this->checkrequired($this->subgroupnameeng,'Sub group name(English)');
        $this->checkrequired($this->subgroupnameuni,'Sub group name(Unicode)');
        $this->checkrequired($this->groupcode,'Group code');
        $this->end_validation();
        return $this->invalidid;
	  }
    private function datavalidation()
    {
        $this->start_validation();
    		$this->invalidid=0;
    		$this->invalidmessagetext='Validated';
    		$this->end_validation();
    		return $this->invalidid;
    }
    public function insert()
    {
        $this->dataoperationmode = operationmode::Insert;
	    if ($this->entryvalidation() <> 0)
        {
            return 0;
            exit;
        }
        elseif ($this->datavalidation() <> 0)
        {
            return 0;
            exit;
        }
	    if ($this->subgroupcode == '')
        {
            $query = "select nvl(max(subgroupcode),0)+1 as subgroupcode from accountsubgroup";
            $result = oci_parse($this->connection, $query);
            $r = oci_execute($result,OCI_NO_AUTO_COMMIT);
            $row = oci_fetch_array($result,OCI_ASSOC+OCI_RETURN_NULLS);
            $this->subgroupcode = $row["SUBGROUPCODE"];
        }
        $query = "
            insert into accountsubgroup(
            subgroupcode
            ,subgroupnameeng
            ,subgroupnameuni
            ,groupcode
	        )
	        values (
            ".$this->invl($this->subgroupcode,true)."
            ,".$this->invl($this->subgroupnameeng,false)."
            ,".$this->invl($this->subgroupnameuni,false)."
            ,".$this->invl($this->groupcode,true,true)."
            )";
        $result = oci_parse($this->connection, $query);
        if (oci_execute($result,OCI_NO_AUTO_COMMIT))
        {
            return 1;
            exit;
        }
        else
        {
            return 0;
            exit;
        }
    }
    public function display()
	  {
		    $this->dataoperationmode = operationmode::Select;
		    $cond='';
		    if ($this->subgroupnameeng!='')
		    {
			      if ($cond=='')
			      {
				        $cond="subgroupnameeng like '%".$this->subgroupnameeng."%'";
			       }
			       else
			       {
				         $cond=$cond." and subgroupnameeng like '%".$this->subgroupnameeng."%'";
			       }
		    }
		    if ($this->subgroupnameuni!='')
		    {
			      if ($cond=='')
			      {
				        $cond="subgroupnameuni like '%".$this->subgroupnameuni."%'";
			       }
			       else
			       {
				         $cond=$cond." and subgroupnameuni like '%".$this->subgroupnameuni."%'";
			       }
            }
            if ($this->groupcode!='')
		    {
			      if ($cond=='')
			      {
				        $cond="groupcode =".$this->groupcode;
			       }
			       else
			       {
				         $cond=$cond." and groupcode =".$this->groupcode;
			       }
		    }
        if ($cond!='')
		    {
		        $query = "select * from accountsubgroup where ".$cond." order by subgroupcode";
			      $result = oci_parse($this->connection, $query);
            $r = oci_execute($result,OCI_NO_AUTO_COMMIT);
			      return $result;
		     }
		     else
		     {
		         $query = "select * from accountsubgroup order by subgroupcode";
			       $result = oci_parse($this->connection, $query);
             $r = oci_execute($result,OCI_NO_AUTO_COMMIT);
			       return $result;
		     }
	  }
    public function update()
    {
        $this->dataoperationmode = operationmode::Update;
        if ($this->entryvalidation() <> 0)
        {
            return 0;
            exit;
        }
        elseif ($this->datavalidation() <> 0)
        {
            return 0;
            exit;
        }
        $query = "
        update accountsubgroup set 
        subgroupnameeng =".$this->invl($this->subgroupnameeng,false)."
        ,subgroupnameuni =".$this->invl($this->subgroupnameuni,false)."
        ,groupcode = ".$this->invl($this->groupcode,true)."
        where 
        subgroupcode = ".$this->invl($this->subgroupcode,true)."
        ";
        $result = oci_parse($this->connection, $query);
        if (oci_execute($result,OCI_NO_AUTO_COMMIT))
        {
            return 1;
            exit;
        }
            else
        {
            return 0;
            exit;
        }
    }
    public function delete()
    {
        $this->dataoperationmode = operationmode::Update;
        if ($this->entryvalidation() <> 0)
        {
            return 0;
            exit;
        }
        elseif ($this->datavalidation() <> 0)
        {
            return 0;
            exit;
        }
        $query = "
        delete from accountsubgroup
        where 
        subgroupcode = ".$this->invl($this->subgroupcode,true)."
        ";
        $result = oci_parse($this->connection, $query);
        if (oci_execute($result,OCI_NO_AUTO_COMMIT))
        {
             return 1;
             exit;
        }
        else
        {
            return 0;
            exit;
        }
    }
    public function fetch()
    {
        $this->dataoperationmode = operationmode::Select;
        $query = "select 
        subgroupcode
        ,subgroupnameeng
        ,subgroupnameuni
        ,groupcode
        from ACCOUNTSUBGROUP where 
        subgroupcode = ".$this->invl($this->subgroupcode,true)."
        ";
        $result = oci_parse($this->connection, $query);
        $r = oci_execute($result,OCI_NO_AUTO_COMMIT);
        if ($row = oci_fetch_array($result,OCI_ASSOC+OCI_RETURN_NULLS))
        {
                $this->subgroupcode = $row['SUBGROUPCODE'];
                $this->subgroupnameeng = $row['SUBGROUPNAMEENG'];
                $this->subgroupnameuni = $row['SUBGROUPNAMEUNI'];
                $this->groupcode = $row['GROUPCODE'];
                $this->found=true;
                return true;
        }
        else
        {
        return false;
        }
    }
}
?>

