<?php
//This is generated by Swapp Software Application on 19/12/2018 08:47:49 PM for PHP
include_once("../swappbase/formbase.php");
class voucheractiondetail extends swappform
{
    Public $voucheractionid;
    Public $transactionnumber;
    Public $usercode;
    Public $actioncode;
    Public $actiondate;
    public function __construct(&$connection)
    {
     		 parent::__construct($connection);
         $this->voucheractionid='';
         $this->transactionnumber='';
         $this->usercode='';
         $this->actioncode='';
         $this->actiondate='';
	   }
    private function entryvalidation()
    {
        $this->start_validation();
        $this->checkrequired($this->usercode,'');
        $this->checkrequired($this->actioncode,'');
        $this->end_validation();
        return $this->invalidid;
	  }
    private function datavalidation()
    {
        $this->start_validation();
    		$this->invalidid=0;
    		$this->invalidmessagetext='Validated';
    		$this->end_validation();
    		return $this->invalidid;
    }
    public function insert()
    {
        $this->dataoperationmode = operationmode::Insert;
	    if ($this->entryvalidation() <> 0)
        {
            return 0;
            exit;
        }
        elseif ($this->datavalidation() <> 0)
        {
            return 0;
            exit;
        }
	    if ($this->voucheractionid == '')
        {
            $query = "select nvl(max(voucheractionid),0)+1 as voucheractionid from voucheractiondetail";
            $result = oci_parse($this->connection, $query);
            $r = oci_execute($result,OCI_NO_AUTO_COMMIT);
            $row = oci_fetch_array($result,OCI_ASSOC+OCI_RETURN_NULLS);
            $this->voucheractionid = $row["VOUCHERACTIONID"];
        }
        if ($this->actiondate!='')
        {
            $this->actiondate = DateTime::createFromFormat('d/m/Y',$this->actiondate)->format('d-M-Y');
        }
        $query = "
            insert into voucheractiondetail(
            voucheractionid
            ,transactionnumber
            ,usercode
            ,actioncode
	        )
	        values (
            ".$this->invl($this->voucheractionid,true)."
            ,".$this->invl($this->transactionnumber,true)."
            ,".$this->invl($this->usercode,true)."
            ,".$this->invl($this->actioncode,true)."
            )";
        $result = oci_parse($this->connection, $query);
        if (oci_execute($result,OCI_NO_AUTO_COMMIT))
        {
            return 1;
            exit;
        }
        else
        {
            return 0;
            exit;
        }
    }
    public function display()
	  {
		    $this->dataoperationmode = operationmode::Select;
		    $cond='';
		    if ($this->voucheractionid!='' and $this->voucheractionid!=0)
		    {
			      if ($cond=='')
			      {
				        $cond="t.voucheractionid = ".$this->voucheractionid;
			       }
			       else
			       {
				         $cond=$cond." and t.voucheractionid = ".$this->voucheractionid;
			       }
		    }
		    if ($this->transactionnumber!='' and $this->transactionnumber!=0)
		    {
			      if ($cond=='')
			      {
				        $cond="t.transactionnumber = ".$this->transactionnumber;
			       }
			       else
			       {
				         $cond=$cond." and t.transactionnumber = ".$this->transactionnumber;
			       }
		    }
		    if ($this->usercode!='' and $this->usercode!=0)
		    {
			      if ($cond=='')
			      {
				        $cond="t.usercode = ".$this->usercode;
			       }
			       else
			       {
				         $cond=$cond." and t.usercode = ".$this->usercode;
			       }
		    }
		    if ($this->actioncode!='' and $this->actioncode!=0)
		    {
			      if ($cond=='')
			      {
				        $cond="t.actioncode = ".$this->actioncode;
			       }
			       else
			       {
				         $cond=$cond." and t.actioncode = ".$this->actioncode;
			       }
		    }
		    if ($this->actiondate!='')
		    {
			      $this->actiondate = DateTime::createFromFormat('d/m/Y',$this->actiondate)->format('d-M-Y');
			      if ($cond=='')
			      {
				        $cond="t.actiondate = '".$this->actiondate."'";
			       }
			       else
			       {
				         $cond=$cond." and t.actiondate = '".$this->actiondate."'";
			       }
		    }
        if ($cond!='')
		    {
		        $query = "select t.* from voucheractiondetail t where ".$cond." order by voucheractionid,transactionnumber";
			      $result = oci_parse($this->connection, $query);
            $r = oci_execute($result,OCI_NO_AUTO_COMMIT);
			      return $result;
		     }
		     else
		     {
		         $query = "select t.* from voucheractiondetail t order by voucheractionid,transactionnumber";
			       $result = oci_parse($this->connection, $query);
             $r = oci_execute($result,OCI_NO_AUTO_COMMIT);
			       return $result;
		     }
	  }
    public function update()
    {
        $this->dataoperationmode = operationmode::Update;
        if ($this->entryvalidation() <> 0)
        {
            return 0;
            exit;
        }
        elseif ($this->datavalidation() <> 0)
        {
            return 0;
            exit;
        }
        $this->actiondate = DateTime::createFromFormat('d/m/Y',$this->actiondate)->format('d-M-Y');
        $query = "
        update voucheractiondetail set 
        usercode = ".$this->invl($this->usercode,true)."
        ,actioncode = ".$this->invl($this->actioncode,true)."
        where 
        voucheractionid = ".$this->invl($this->voucheractionid,true)."
        transactionnumber = ".$this->invl($this->transactionnumber,true)."
        ";
        $result = oci_parse($this->connection, $query);
        if (oci_execute($result,OCI_NO_AUTO_COMMIT))
        {
            return 1;
            exit;
        }
            else
        {
            return 0;
            exit;
        }
    }
    public function delete()
    {
        $this->dataoperationmode = operationmode::Delete;
        if ($this->entryvalidation() <> 0)
        {
            return 0;
            exit;
        }
        elseif ($this->datavalidation() <> 0)
        {
            return 0;
            exit;
        }
        $this->actiondate = DateTime::createFromFormat('d/m/Y',$this->actiondate)->format('d-M-Y');
        $query = "
        delete from voucheractiondetail
        where 
        voucheractionid ='".$this->invl($this->voucheractionid,false)."'
        transactionnumber ='".$this->invl($this->transactionnumber,false)."'
        ";
        $result = oci_parse($this->connection, $query);
        if (oci_execute($result,OCI_NO_AUTO_COMMIT))
        {
             return 1;
             exit;
        }
        else
        {
            return 0;
            exit;
        }
    }
    public function fetch()
    {
        $this->dataoperationmode = operationmode::Select;
        $query = "select 
        voucheractionid
        ,transactionnumber
        ,usercode
        ,actioncode
        ,actiondate
        from voucheractiondetail where 
        voucheractionid = ".$this->invl($this->voucheractionid,true)."
         and transactionnumber = ".$this->invl($this->transactionnumber,true)."
        ";
        $result = oci_parse($this->connection, $query);
        $r = oci_execute($result,OCI_NO_AUTO_COMMIT);
        if ($row = oci_fetch_array($result,OCI_ASSOC+OCI_RETURN_NULLS))
        {
                $this->voucheractionid = $row['VOUCHERACTIONID'];
                $this->transactionnumber = $row['TRANSACTIONNUMBER'];
                $this->usercode = $row['USERCODE'];
                $this->actioncode = $row['ACTIONCODE'];
                $this->actiondate = $row['ACTIONDATE'];
                $this->found=true;
                return true;
        }
        else
        {
        return false;
        }
    }

    public function fetchpendingvoucher($voucherdate,$vouchersubtypecode)
    {
        $this->dataoperationmode = operationmode::Select;
        if ($voucherdate=='')
        {
            $query = "select * from vw_voucher_approval_pending t 
            where yearperiodcode=".$_SESSION['yearperiodcode']." and t.responsibilitycode=".$_SESSION['responsibilitycode'].
            " and voucherdate is null
            and vouchersubtypecode=".$vouchersubtypecode.
            " order by transactionnumber";
        }
        else
        {
            $query = "select * from vw_voucher_approval_pending t 
            where t.responsibilitycode=".$_SESSION['responsibilitycode'].
            " and voucherdate='".$voucherdate."'
            and vouchersubtypecode=".$vouchersubtypecode.
            " order by transactionnumber";
        } 
        $result = oci_parse($this->connection, $query);
        $r = oci_execute($result,OCI_NO_AUTO_COMMIT);
        return $result;
    }
    public function fetchpendingvoucherdaily()
    {
        $this->dataoperationmode = operationmode::Select;
        $query = "select t.voucherdate,count(*) as cnt 
        from vw_voucher_approval_pending t 
        where t.responsibilitycode=".$_SESSION['responsibilitycode'].
        " group by t.voucherdate
        order by t.voucherdate"; 
        $result = oci_parse($this->connection, $query);
        $r = oci_execute($result,OCI_NO_AUTO_COMMIT);
        return $result;
 
    }
    public function fetchpendingvouchersubtype($voucherdate)
    {
        $this->dataoperationmode = operationmode::Select;
        if ($voucherdate=='')
        {
            $query = "select t.vouchersubtypecode,vouchersubtypenameuni,count(*) as cnt 
            from vw_voucher_approval_pending t 
            where yearperiodcode=".$_SESSION['yearperiodcode']." and t.responsibilitycode=".$_SESSION['responsibilitycode'].
            " and voucherdate is null group by t.vouchersubtypecode,vouchersubtypenameuni";     
        }
        else
        {
            $query = "select t.vouchersubtypecode,vouchersubtypenameuni,count(*) as cnt 
        from vw_voucher_approval_pending t 
        where t.responsibilitycode=".$_SESSION['responsibilitycode'].
        " and voucherdate='".$voucherdate."'
         group by t.vouchersubtypecode,vouchersubtypenameuni"; 
        }
        
        $result = oci_parse($this->connection, $query);
        $r = oci_execute($result,OCI_NO_AUTO_COMMIT);
        return $result;
 
    }
}
?>

