<?php
//This is generated by Swapp Software Application on 25/05/2019 06:16:57 PM for PHP
require_once("../swappbase/formbase.php");
class caneutilization extends swappform
{
    Public $caneutilizationcode;
    Public $caneutilizationnnameeng;
    Public $caneutilizationnameuni;
    public function __construct(&$connection)
    {
     		 parent::__construct($connection);
         $this->caneutilizationcode='';
         $this->caneutilizationnnameeng='';
         $this->caneutilizationnameuni='';
	   }
    public function entryvalidation()
    {
    		$this->start_validation();
        $this->checkrequired($this->caneutilizationnnameeng,'Cane Utization (English)');
        $this->checkrequired($this->caneutilizationnameuni,'Cane Utilization (Marathi)');
        $this->end_validation();
        return $this->invalidid;
	  }
    private function datavalidation()
    {
        $this->start_validation();
    		$this->invalidid=0;
    		$this->invalidmessagetext='Validated';
    		$this->end_validation();
    		return $this->invalidid;
    }
    public function insert()
    {
        $this->dataoperationmode = operationmode::Insert;
	    if ($this->entryvalidation() <> 0)
        {
            return 0;
            exit;
        }
        elseif ($this->datavalidation() <> 0)
        {
            return 0;
            exit;
        }
	    if ($this->caneutilizationcode == '')
        {
            $query = "select nvl(max(caneutilizationcode),0)+1 as caneutilizationcode from caneutilization";
            $result = oci_parse($this->connection, $query);
            $r = oci_execute($result);
            $row = oci_fetch_array($result,OCI_ASSOC+OCI_RETURN_NULLS);
            $this->caneutilizationcode = $row["CANEUTILIZATIONCODE"];
        }
        $query = "
            insert into caneutilization(
            caneutilizationcode
            ,caneutilizationnnameeng
            ,caneutilizationnameuni
	        )
	        values (
            ".$this->invl($this->caneutilizationcode,true)."
            ,".$this->invl($this->caneutilizationnnameeng,false)."
            ,".$this->invl($this->caneutilizationnameuni,false)."
            )";
        $result = oci_parse($this->connection, $query);
        if (oci_execute($result,OCI_NO_AUTO_COMMIT))
        {
            return 1;
            exit;
        }
        else
        {
            return 0;
            exit;
        }
    }
    public function display()
	  {
		    $this->dataoperationmode = operationmode::Select;
		    $cond='';
		    if ($this->caneutilizationcode!='' and $this->caneutilizationcode!=0)
		    {
			      if ($cond=='')
			      {
				        $cond="t.caneutilizationcode = ".$this->caneutilizationcode;
			       }
			       else
			       {
				         $cond=$cond." and t.caneutilizationcode = ".$this->caneutilizationcode;
			       }
		    }
		    if ($this->caneutilizationnnameeng!='')
		    {
			      if ($cond=='')
			      {
				        $cond="t.caneutilizationnnameeng like '%".$this->caneutilizationnnameeng."%'";
			       }
			       else
			       {
				         $cond=$cond." and t.caneutilizationnnameeng like '%".$this->caneutilizationnnameeng."%'";
			       }
		    }
		    if ($this->caneutilizationnameuni!='')
		    {
			      if ($cond=='')
			      {
				        $cond="t.caneutilizationnameuni like '%".$this->caneutilizationnameuni."%'";
			       }
			       else
			       {
				         $cond=$cond." and t.caneutilizationnameuni like '%".$this->caneutilizationnameuni."%'";
			       }
		    }
        if ($cond!='')
		    {
		        $query = "select t.* from caneutilization t where ".$cond." order by caneutilizationcode";
			      $result = oci_parse($this->connection, $query);
            $r = oci_execute($result);
			      return $result;
		     }
		     else
		     {
		         $query = "select t.* from caneutilization t order by caneutilizationcode";
			       $result = oci_parse($this->connection, $query);
             $r = oci_execute($result);
			       return $result;
		     }
	  }
    public function update()
    {
        $this->dataoperationmode = operationmode::Update;
        if ($this->entryvalidation() <> 0)
        {
            return 0;
            exit;
        }
        elseif ($this->datavalidation() <> 0)
        {
            return 0;
            exit;
        }
        $query = "
        update caneutilization set 
        caneutilizationnnameeng =".$this->invl($this->caneutilizationnnameeng,false)."
        ,caneutilizationnameuni =".$this->invl($this->caneutilizationnameuni,false)."
        where 
        caneutilizationcode = ".$this->invl($this->caneutilizationcode,true)."
        ";
        $result = oci_parse($this->connection, $query);
        if (oci_execute($result,OCI_NO_AUTO_COMMIT))
        {
            return 1;
            exit;
        }
            else
        {
            return 0;
            exit;
        }
    }
    public function delete()
    {
        $this->dataoperationmode = operationmode::Delete;
        if ($this->entryvalidation() <> 0)
        {
            return 0;
            exit;
        }
        elseif ($this->datavalidation() <> 0)
        {
            return 0;
            exit;
        }
        $query = "
        delete from caneutilization
        where 
        caneutilizationcode ='".$this->invl($this->caneutilizationcode,false)."'
        ";
        $result = oci_parse($this->connection, $query);
        if (oci_execute($result,OCI_NO_AUTO_COMMIT))
        {
             return 1;
             exit;
        }
        else
        {
            return 0;
            exit;
        }
    }
    public function fetch()
    {
        $this->dataoperationmode = operationmode::Select;
        $query = "select 
        caneutilizationcode
        ,caneutilizationnnameeng
        ,caneutilizationnameuni
        from caneutilization where 
        caneutilizationcode = ".$this->invl($this->caneutilizationcode,true)."
        ";
        $result = oci_parse($this->connection, $query);
        $r = oci_execute($result);
        if ($row = oci_fetch_array($result,OCI_ASSOC+OCI_RETURN_NULLS))
        {
                $this->caneutilizationcode = $row['CANEUTILIZATIONCODE'];
                $this->caneutilizationnnameeng = $row['CANEUTILIZATIONNNAMEENG'];
                $this->caneutilizationnameuni = $row['CANEUTILIZATIONNAMEUNI'];
                $this->found=true;
                return true;
        }
        else
        {
        return false;
        }
    }
}
?>

