<?php
//This is generated by Swapp Software Application on 25/05/2019 12:24:27 PM for PHP
require_once("../swappbase/formbase.php");
class circle extends swappform
{
    Public $circlecode;
    Public $circlenameeng;
    Public $circlenameuni;
    Public $divisioncode;
    Public $factorycode;
    public function __construct(&$connection)
    {
     		 parent::__construct($connection);
         $this->circlecode='';
         $this->circlenameeng='';
         $this->circlenameuni='';
         $this->divisioncode='';
         $this->factorycode='';
	   }
    public function entryvalidation()
    {
    		$this->start_validation();
        $this->checkrequired($this->circlenameeng,'Circle Name (English)');
        $this->englishtextonly($this->circlenameeng,'Circle Name (English)');
        $this->checkrequired($this->circlenameuni,'Circle Name (Unicode)');
        $this->unicodedevanagaritextonly($this->circlenameuni,'Circle Name (Unicode)');
        $this->checkrequired($this->divisioncode,'Division');
        $this->checkrequired($this->factorycode,'Factory');
        $this->end_validation();
        return $this->invalidid;
	  }
    private function datavalidation()
    {
        $this->start_validation();
    		$this->invalidid=0;
    		$this->invalidmessagetext='Validated';
    		$this->end_validation();
    		return $this->invalidid;
    }
    public function insert()
    {
        $this->dataoperationmode = operationmode::Insert;
	    if ($this->entryvalidation() <> 0)
        {
            return 0;
            exit;
        }
        elseif ($this->datavalidation() <> 0)
        {
            return 0;
            exit;
        }
	    if ($this->circlecode == '')
        {
            $query = "select nvl(max(circlecode),0)+1 as circlecode from circle";
            $result = oci_parse($this->connection, $query);
            $r = oci_execute($result);
            $row = oci_fetch_array($result,OCI_ASSOC+OCI_RETURN_NULLS);
            $this->circlecode = $row["CIRCLECODE"];
        }
        $query = "
            insert into circle(
            circlecode
            ,circlenameeng
            ,circlenameuni
            ,divisioncode
            ,factorycode
	        )
	        values (
            ".$this->invl($this->circlecode,true)."
            ,".$this->invl($this->circlenameeng,false)."
            ,".$this->invl($this->circlenameuni,false)."
            ,".$this->invl($this->divisioncode,true,true)."
            ,".$this->invl($this->factorycode,true,true)."
            )";
        $result = oci_parse($this->connection, $query);
        if (oci_execute($result,OCI_NO_AUTO_COMMIT))
        {
            return 1;
            exit;
        }
        else
        {
            return 0;
            exit;
        }
    }
    public function display()
	  {
		    $this->dataoperationmode = operationmode::Select;
		    $cond='';
		    if ($this->circlenameeng!='')
		    {
			      if ($cond=='')
			      {
				        $cond="t.circlenameeng like '%".$this->circlenameeng."%'";
			       }
			       else
			       {
				         $cond=$cond." and t.circlenameeng like '%".$this->circlenameeng."%'";
			       }
		    }
		    if ($this->circlenameuni!='')
		    {
			      if ($cond=='')
			      {
				        $cond="t.circlenameuni like '%".$this->circlenameuni."%'";
			       }
			       else
			       {
				         $cond=$cond." and t.circlenameuni like '%".$this->circlenameuni."%'";
			       }
		    }
		    if ($this->divisioncode!='' and $this->divisioncode!=0)
		    {
			      if ($cond=='')
			      {
				        $cond="t.divisioncode = ".$this->divisioncode;
			       }
			       else
			       {
				         $cond=$cond." and t.divisioncode = ".$this->divisioncode;
			       }
		    }
		    if ($this->factorycode!='' and $this->factorycode!=0)
		    {
			      if ($cond=='')
			      {
				        $cond="t.factorycode = ".$this->factorycode;
			       }
			       else
			       {
				         $cond=$cond." and t.factorycode = ".$this->factorycode;
			       }
		    }
        if ($cond!='')
		    {
		        $query = "select t.* from circle t where ".$cond." order by circlecode";
			      $result = oci_parse($this->connection, $query);
            $r = oci_execute($result);
			      return $result;
		     }
		     else
		     {
		         $query = "select t.* from circle t order by circlecode";
			       $result = oci_parse($this->connection, $query);
             $r = oci_execute($result);
			       return $result;
		     }
	  }
    public function update()
    {
        $this->dataoperationmode = operationmode::Update;
        if ($this->entryvalidation() <> 0)
        {
            return 0;
            exit;
        }
        elseif ($this->datavalidation() <> 0)
        {
            return 0;
            exit;
        }
        $query = "
        update circle set 
        circlenameeng =".$this->invl($this->circlenameeng,false)."
        ,circlenameuni =".$this->invl($this->circlenameuni,false)."
        ,divisioncode = ".$this->invl($this->divisioncode,true)."
        ,factorycode = ".$this->invl($this->factorycode,true)."
        where 
        circlecode = ".$this->invl($this->circlecode,true)."
        ";
        $result = oci_parse($this->connection, $query);
        if (oci_execute($result,OCI_NO_AUTO_COMMIT))
        {
            return 1;
            exit;
        }
            else
        {
            return 0;
            exit;
        }
    }
    public function delete()
    {
        $this->dataoperationmode = operationmode::Delete;
        if ($this->entryvalidation() <> 0)
        {
            return 0;
            exit;
        }
        elseif ($this->datavalidation() <> 0)
        {
            return 0;
            exit;
        }
        $query = "
        delete from circle
        where 
        circlecode = ".$this->invl($this->circlecode,true)."
        ";
        $result = oci_parse($this->connection, $query);
        if (oci_execute($result,OCI_NO_AUTO_COMMIT))
        {
             return 1;
             exit;
        }
        else
        {
            return 0;
            exit;
        }
    }
    public function fetch()
    {
        $this->dataoperationmode = operationmode::Select;
        $query = "select 
        circlecode
        ,circlenameeng
        ,circlenameuni
        ,divisioncode
        ,factorycode
        from circle where 
        circlecode = ".$this->invl($this->circlecode,true)."
        ";
        $result = oci_parse($this->connection, $query);
        $r = oci_execute($result);
        if ($row = oci_fetch_array($result,OCI_ASSOC+OCI_RETURN_NULLS))
        {
                $this->circlecode = $row['CIRCLECODE'];
                $this->circlenameeng = $row['CIRCLENAMEENG'];
                $this->circlenameuni = $row['CIRCLENAMEUNI'];
                $this->divisioncode = $row['DIVISIONCODE'];
                $this->factorycode = $row['FACTORYCODE'];
                $this->found=true;
                return true;
        }
        else
        {
        return false;
        }
    }
    public function fetchall($divisioncode)
    {
        $this->dataoperationmode = operationmode::Select;
        $query = "select 
        circlecode
        ,circlenameeng
        ,circlenameuni
        ,divisioncode
        ,factorycode
        from circle where 
        divisioncode = ".$this->invl($divisioncode,true)."
        ";
        $result = oci_parse($this->connection, $query);
        return $result;
    }
}
?>

