<?php
//This is generated by Swapp Software Application on 26/05/2019 06:19:00 PM for PHP
require_once("../swappbase/formbase.php");
class irrigationsource extends swappform
{
    Public $irrigationsourcecode;
    Public $irrigationsourcenameeng;
    Public $irrigationsourcenameuni;
    public function __construct(&$connection)
    {
     		 parent::__construct($connection);
         $this->irrigationsourcecode='';
         $this->irrigationsourcenameeng='';
         $this->irrigationsourcenameuni='';
	   }
    public function entryvalidation()
    {
    		$this->start_validation();
        $this->checkrequired($this->irrigationsourcenameeng,'Irrigation Source (English)');
        $this->checkrequired($this->irrigationsourcenameuni,'Irrigation Source (Unicode)');
        $this->end_validation();
        return $this->invalidid;
	  }
    private function datavalidation()
    {
        $this->start_validation();
    		$this->invalidid=0;
    		$this->invalidmessagetext='Validated';
    		$this->end_validation();
    		return $this->invalidid;
    }
    public function insert()
    {
        $this->dataoperationmode = operationmode::Insert;
	    if ($this->entryvalidation() <> 0)
        {
            return 0;
            exit;
        }
        elseif ($this->datavalidation() <> 0)
        {
            return 0;
            exit;
        }
	    if ($this->irrigationsourcecode == '')
        {
            $query = "select nvl(max(irrigationsourcecode),0)+1 as irrigationsourcecode from irrigationsource";
            $result = oci_parse($this->connection, $query);
            $r = oci_execute($result);
            $row = oci_fetch_array($result,OCI_ASSOC+OCI_RETURN_NULLS);
            $this->irrigationsourcecode = $row["IRRIGATIONSOURCECODE"];
        }
        $query = "
            insert into irrigationsource(
            irrigationsourcecode
            ,irrigationsourcenameeng
            ,irrigationsourcenameuni
	        )
	        values (
            ".$this->invl($this->irrigationsourcecode,true)."
            ,".$this->invl($this->irrigationsourcenameeng,false)."
            ,".$this->invl($this->irrigationsourcenameuni,false)."
            )";
        $result = oci_parse($this->connection, $query);
        if (oci_execute($result,OCI_NO_AUTO_COMMIT))
        {
            return 1;
            exit;
        }
        else
        {
            return 0;
            exit;
        }
    }
    public function display()
	  {
		    $this->dataoperationmode = operationmode::Select;
		    $cond='';
		    if ($this->irrigationsourcenameeng!='')
		    {
			      if ($cond=='')
			      {
				        $cond="t.irrigationsourcenameeng like '%".$this->irrigationsourcenameeng."%'";
			       }
			       else
			       {
				         $cond=$cond." and t.irrigationsourcenameeng like '%".$this->irrigationsourcenameeng."%'";
			       }
		    }
		    if ($this->irrigationsourcenameuni!='')
		    {
			      if ($cond=='')
			      {
				        $cond="t.irrigationsourcenameuni like '%".$this->irrigationsourcenameuni."%'";
			       }
			       else
			       {
				         $cond=$cond." and t.irrigationsourcenameuni like '%".$this->irrigationsourcenameuni."%'";
			       }
		    }
        if ($cond!='')
		    {
		        $query = "select t.* from irrigationsource t where ".$cond." order by irrigationsourcecode";
			      $result = oci_parse($this->connection, $query);
            $r = oci_execute($result);
			      return $result;
		     }
		     else
		     {
		         $query = "select t.* from irrigationsource t order by irrigationsourcecode";
			       $result = oci_parse($this->connection, $query);
             $r = oci_execute($result);
			       return $result;
		     }
	  }
    public function update()
    {
        $this->dataoperationmode = operationmode::Update;
        if ($this->entryvalidation() <> 0)
        {
            return 0;
            exit;
        }
        elseif ($this->datavalidation() <> 0)
        {
            return 0;
            exit;
        }
        $query = "
        update irrigationsource set 
        irrigationsourcenameeng =".$this->invl($this->irrigationsourcenameeng,false)."
        ,irrigationsourcenameuni =".$this->invl($this->irrigationsourcenameuni,false)."
        where 
        irrigationsourcecode = ".$this->invl($this->irrigationsourcecode,true)."
        ";
        $result = oci_parse($this->connection, $query);
        if (oci_execute($result,OCI_NO_AUTO_COMMIT))
        {
            return 1;
            exit;
        }
            else
        {
            return 0;
            exit;
        }
    }
    public function delete()
    {
        $this->dataoperationmode = operationmode::Delete;
        if ($this->entryvalidation() <> 0)
        {
            return 0;
            exit;
        }
        elseif ($this->datavalidation() <> 0)
        {
            return 0;
            exit;
        }
        $query = "
        delete from irrigationsource
        where 
        irrigationsourcecode =".$this->invl($this->irrigationsourcecode,false);
        $result = oci_parse($this->connection, $query);
        if (oci_execute($result,OCI_NO_AUTO_COMMIT))
        {
             return 1;
             exit;
        }
        else
        {
            return 0;
            exit;
        }
    }
    public function fetch()
    {
        $this->dataoperationmode = operationmode::Select;
        $query = "select 
        irrigationsourcecode
        ,irrigationsourcenameeng
        ,irrigationsourcenameuni
        from irrigationsource where 
        irrigationsourcecode = ".$this->invl($this->irrigationsourcecode,true)."
        ";
        $result = oci_parse($this->connection, $query);
        $r = oci_execute($result);
        if ($row = oci_fetch_array($result,OCI_ASSOC+OCI_RETURN_NULLS))
        {
                $this->irrigationsourcecode = $row['IRRIGATIONSOURCECODE'];
                $this->irrigationsourcenameeng = $row['IRRIGATIONSOURCENAMEENG'];
                $this->irrigationsourcenameuni = $row['IRRIGATIONSOURCENAMEUNI'];
                $this->found=true;
                return true;
        }
        else
        {
        return false;
        }
    }
}
?>

