<?php
    //This is generated by Swapp Software Application on 15/05/2019 10:22:32 AM for PHP
    require("../info/phpgetloginview.php");
    include("../info/ncryptdcrypt.php");
    require("../info/routine.php");
    include("../ip_model/deduction_db_oracle.php");
    $connection=swapp_connection();
    $deduction1 = new deduction($connection);
    $deduction1->deductioncode = $_POST["deductioncode"];
    $deduction1->deductionnameeng = $_POST["deductionnameeng"];
    $deduction1->deductionnameuni = $_POST["deductionnameuni"];
    $deduction1->ledgeraccountcode = $_POST["ledgeraccountcode"];
    $flag_de = fnDecrypt($_GET['flag']);
  switch ($_POST['btn'])
  {
    case 'Add':
      $ret = $deduction1->insert();
      if ($ret==1)
      {
        oci_commit($connection);
        echo '<span class="w3-container" style="background-color:#0a0;color:#ff8;text-align:left;">Deduction is added successfully</span></br>';
        echo '<a href="../ip_view/deduction.php">New Deduction</a></br>';
      }
      else
      {
        oci_rollback($connection);
        echo '<span style="background-color:#f44;color:#ff8;text-align:left;">'.$deduction1->Get_invalidmessagetext().'</span></br>';
        echo '<button onclick="history.go(-1);">Back </button>';
      }
      break;
    case 'Change':
      $deduction1->deductioncode = $_POST["deductioncode"];
      $ret = $deduction1->update();
      if ($ret==1)
      {
        oci_commit($connection);
        $flag_en = fnEncrypt('Query');
        echo '<span class="w3-container" style="background-color:#0a0;color:#ff8;text-align:left;">Deduction is Updated successfully</span></br>';  
        echo '<a href="../ip_view/deduction.php?flag='.$flag_en.'">Find Deduction</a></br>';
      }
      else
      {
        oci_rollback($connection);
        echo '<span style="background-color:#f44;color:#ff8;text-align:left;">'.$deduction1->Get_invalidmessagetext().'</span></br>';
        echo '<button onclick="history.go(-1);">Back </button>';
			}
			break;
		case 'Display':
      $deduction1->deductioncode = $_POST["deductioncode"];
      include("../mis/list.php");
      echo '<nav "w3-container">';
      echo '    <ul class="navbar">';
      echo '    <li><a class="navbar" href="../mis/entitymenu.php">Entity Menu</a><br/>';
      $flag_en = fnEncrypt('Query');
      echo '    <li><a class="navbar" href="../ip_view/deduction.php">New Deduction</a>';
      echo '    <li><a class="navbar" href="../ip_view/deduction.php?flag='.$flag_en.'">Find Deduction</a>';
      echo '<li><a style="color:#f48" class="navbar" href="../../../../../sqlproc/logout.php">Log Out</a><br/>';
      echo '    </ul>';
      echo '  </nav>';
      echo '<section>';
      echo '<table border="0" >';
      echo '<tr>';
      echo '<td><label for="" class="thick">List of Deduction</label></td>';
      echo '</tr>';
			$result1 = $deduction1->display();
			if ($deduction1->Get_invalidid()==0)
			{
        $flag_en = fnEncrypt('Display');
				while ($row1 = oci_fetch_array($result1,OCI_ASSOC+OCI_RETURN_NULLS))
				{
					if ($_SESSION['lng']=='English')
					{
            echo '<tr>';
						echo '<td><a href="../ip_view/deduction.php?deductioncode='.fnEncrypt($row1['DEDUCTIONCODE']).'&flag='.$flag_en.'">'.$row1['DEDUCTIONNAMEENG'].'</td>';
            echo '</tr>';
					}
					else
					{
            echo '<tr>';
						echo '<td><a href="../ip_view/deduction.php?deductioncode='.fnEncrypt($row1['DEDUCTIONCODE']).'&flag='.$flag_en.'">'.$row1['DEDUCTIONNAMEUNI'].'</td>';
            echo '</tr>';
					}
				}	
			}
			else
			{
				echo '<span style="background-color:#f44;color:#ff8;text-align:left;">'.$deduction1->Get_invalidmessagetext().'</span></br>';
        echo '<button onclick="history.go(-1);">Back </button>';
			}
			break;
		case 'Delete':
      $deduction1->deductioncode = $_POST["deductioncode"];
			$ret = $deduction1->delete();
			if ($ret == 1)
			{
				oci_commit($connection);
        $flag_en = fnEncrypt('Query');
				echo '<span class="w3-container" style="background-color:#0a0;color:#ff8;text-align:left;">Deduction is Deleted Successfully</span></br>';
        echo '<a href="../ip_view/deduction.php?flag='.$flag_en.'">Find Deduction</a></br>';
			}
			else
			{
				oci_rollback($connection);
				echo '<span style="background-color:#f44;color:#ff8;text-align:left;">'.$deduction1->Get_invalidmessagetext().'</span></br>';
				echo '<a href="../ip_view/deduction.php">Find deduction</a></br>';
        echo '<button onclick="history.go(-1);">Back </button>';
			}
			break;
		default:
			echo 'Communication Error';
      echo '<button onclick="history.go(-1);">Back </button>';
			break;
	}

