<?php
//This is generated by Swapp Software Application on 16/05/2019 06:27:32 PM for PHP
require_once("../swappbase/formbase.php");
class harvestingrate extends swappform
{
    Public $transactionnumber;
    Public $seasoncode;
    Public $billtype;
    Public $harvestersubcategorycode;
    Public $harvestingrate;
    Public $fromdate;
    Public $todate;
    public function __construct(&$connection)
    {
     		 parent::__construct($connection);
         $this->transactionnumber='';
         $this->seasoncode='';
         $this->billtype='';
         $this->harvestersubcategorycode='';
         $this->harvestingrate='';
         $this->fromdate='';
         $this->todate='';
	   }
    private function entryvalidation()
    {
    		$this->start_validation();
        $this->checkrequired($this->billtype,'Bill Type');
        $this->checkrequired($this->harvestersubcategorycode,'Harvester Sub Category');
        $this->checkrequired($this->harvestingrate,'Harvesting Rate');
        $this->checkrequired($this->fromdate,'From Date');
        $this->checkrequired($this->todate,'To Date');
        $this->end_validation();
        return $this->invalidid;
	  }
    private function datavalidation()
    {
        $this->start_validation();
    		$this->invalidid=0;
    		$this->invalidmessagetext='Validated';
    		$this->end_validation();
    		return $this->invalidid;
    }
    public function insert()
    {
        $this->dataoperationmode = operationmode::Insert;
	    if ($this->entryvalidation() <> 0)
        {
            return 0;
            exit;
        }
        elseif ($this->datavalidation() <> 0)
        {
            return 0;
            exit;
        }
	    if ($this->transactionnumber == '')
        {
            $query = "select nvl(max(transactionnumber),0)+1 as transactionnumber from harvestingrate";
            $result = oci_parse($this->connection, $query);
            $r = oci_execute($result);
            $row = oci_fetch_array($result,OCI_ASSOC+OCI_RETURN_NULLS);
            $this->transactionnumber = $row["TRANSACTIONNUMBER"];
        }
        if ($this->fromdate!='')
        {
            $this->fromdate = DateTime::createFromFormat('d/m/Y',$this->fromdate)->format('d-M-Y');
        }
        if ($this->todate!='')
        {
            $this->todate = DateTime::createFromFormat('d/m/Y',$this->todate)->format('d-M-Y');
        }
        $query = "
            insert into harvestingrate(
            transactionnumber
            ,seasoncode
            ,billtype
            ,harvestersubcategorycode
            ,harvestingrate
            ,fromdate
            ,todate
	        )
	        values (
            ".$this->invl($this->transactionnumber,true)."
            ,".$this->invl($this->seasoncode,true)."
            ,".$this->invl($this->billtype,true,true)."
            ,".$this->invl($this->harvestersubcategorycode,true,true)."
            ,".$this->invl($this->harvestingrate,true)."
            ,".$this->invl($this->fromdate,false)."
            ,".$this->invl($this->todate,false)."
            )";
        $result = oci_parse($this->connection, $query);
        if (oci_execute($result,OCI_NO_AUTO_COMMIT))
        {
            return 1;
            exit;
        }
        else
        {
            return 0;
            exit;
        }
    }
    public function display()
	  {
		    $this->dataoperationmode = operationmode::Select;
		    $cond='';
		    if ($this->seasoncode!='' and $this->seasoncode!=0)
		    {
			      if ($cond=='')
			      {
				        $cond="t.seasoncode = ".$this->seasoncode;
			       }
			       else
			       {
				         $cond=$cond." and t.seasoncode = ".$this->seasoncode;
			       }
		    }
		    if ($this->billtype!='' and $this->billtype!=0)
		    {
			      if ($cond=='')
			      {
				        $cond="t.billtype = ".$this->billtype;
			       }
			       else
			       {
				         $cond=$cond." and t.billtype = ".$this->billtype;
			       }
		    }
		    if ($this->harvestersubcategorycode!='' and $this->harvestersubcategorycode!=0)
		    {
			      if ($cond=='')
			      {
				        $cond="t.harvestersubcategorycode = ".$this->harvestersubcategorycode;
			       }
			       else
			       {
				         $cond=$cond." and t.harvestersubcategorycode = ".$this->harvestersubcategorycode;
			       }
		    }
		    if ($this->harvestingrate!='' and $this->harvestingrate!=0)
		    {
			      if ($cond=='')
			      {
				        $cond="t.harvestingrate = ".$this->harvestingrate;
			       }
			       else
			       {
				         $cond=$cond." and t.harvestingrate = ".$this->harvestingrate;
			       }
		    }
		    if ($this->fromdate!='')
		    {
			      $this->fromdate = DateTime::createFromFormat('d/m/Y',$this->fromdate)->format('d-M-Y');
			      if ($cond=='')
			      {
				        $cond="t.fromdate = '".$this->fromdate."'";
			       }
			       else
			       {
				         $cond=$cond." and t.fromdate = '".$this->fromdate."'";
			       }
		    }
		    if ($this->todate!='')
		    {
			      $this->todate = DateTime::createFromFormat('d/m/Y',$this->todate)->format('d-M-Y');
			      if ($cond=='')
			      {
				        $cond="t.todate = '".$this->todate."'";
			       }
			       else
			       {
				         $cond=$cond." and t.todate = '".$this->todate."'";
			       }
		    }
        if ($cond!='')
		    {
		        $query = "select t.* from harvestingrate t where ".$cond." order by transactionnumber";
			      $result = oci_parse($this->connection, $query);
            $r = oci_execute($result);
			      return $result;
		     }
		     else
		     {
		         $query = "select t.* from harvestingrate t order by transactionnumber";
			       $result = oci_parse($this->connection, $query);
             $r = oci_execute($result);
			       return $result;
		     }
	  }
    public function update()
    {
        $this->dataoperationmode = operationmode::Update;
        if ($this->entryvalidation() <> 0)
        {
            return 0;
            exit;
        }
        elseif ($this->datavalidation() <> 0)
        {
            return 0;
            exit;
        }
        $this->fromdate = DateTime::createFromFormat('d/m/Y',$this->fromdate)->format('d-M-Y');
        $this->todate = DateTime::createFromFormat('d/m/Y',$this->todate)->format('d-M-Y');
        $query = "
        update harvestingrate set 
        seasoncode = ".$this->invl($this->seasoncode,true)."
        ,billtype = ".$this->invl($this->billtype,true)."
        ,harvestersubcategorycode = ".$this->invl($this->harvestersubcategorycode,true)."
        ,harvestingrate = ".$this->invl($this->harvestingrate,true)."
        ,fromdate =".$this->invl($this->fromdate,false)."
        ,todate =".$this->invl($this->todate,false)."
        where 
        transactionnumber = ".$this->invl($this->transactionnumber,true)."
        ";
        $result = oci_parse($this->connection, $query);
        if (oci_execute($result,OCI_NO_AUTO_COMMIT))
        {
            return 1;
            exit;
        }
            else
        {
            return 0;
            exit;
        }
    }
    public function delete()
    {
        $this->dataoperationmode = operationmode::Delete;
        if ($this->entryvalidation() <> 0)
        {
            return 0;
            exit;
        }
        elseif ($this->datavalidation() <> 0)
        {
            return 0;
            exit;
        }
        $this->fromdate = DateTime::createFromFormat('d/m/Y',$this->fromdate)->format('d-M-Y');
        $this->todate = DateTime::createFromFormat('d/m/Y',$this->todate)->format('d-M-Y');
        $query = "
        delete from harvestingrate
        where 
        transactionnumber ='".$this->invl($this->transactionnumber,false)."'
        ";
        $result = oci_parse($this->connection, $query);
        if (oci_execute($result,OCI_NO_AUTO_COMMIT))
        {
             return 1;
             exit;
        }
        else
        {
            return 0;
            exit;
        }
    }
    public function fetch()
    {
        $this->dataoperationmode = operationmode::Select;
        $query = "select 
        transactionnumber
        ,seasoncode
        ,billtype
        ,harvestersubcategorycode
        ,harvestingrate
        ,fromdate
        ,todate
        from harvestingrate where 
        transactionnumber = ".$this->invl($this->transactionnumber,true)."
        ";
        $result = oci_parse($this->connection, $query);
        $r = oci_execute($result);
        if ($row = oci_fetch_array($result,OCI_ASSOC+OCI_RETURN_NULLS))
        {
                $this->transactionnumber = $row['TRANSACTIONNUMBER'];
                $this->seasoncode = $row['SEASONCODE'];
                $this->billtype = $row['BILLTYPE'];
                $this->harvestersubcategorycode = $row['HARVESTERSUBCATEGORYCODE'];
                $this->harvestingrate = $row['HARVESTINGRATE'];
                $this->fromdate = DateTime::createFromFormat('d-M-y',$row['FROMDATE'])->format('d/m/Y');
                $this->todate = DateTime::createFromFormat('d-M-y',$row['TODATE'])->format('d/m/Y');
                $this->found=true;
                return true;
        }
        else
        {
        return false;
        }
    }
}
?>

