<?php
    //This is generated by Swapp Software Application on 01/03/2019 08:16:54 PM for PHP
    require("../info/phpsqlajax_dbinfo.php");
    require("../info/phpgetloginview.php");
    require("../info/routine.php");
    $connection =swapp_connection();
    $searchTerm = $_GET['term'];
    if (preg_match('/^[0-9]*$/', $searchTerm))
    {
    }
    elseif (strlen($searchTerm)<3 and $searchTerm != '**')
    {
        exit;
    }
   if ($searchTerm == '**')
   {
       $query = "select PURCHASERCODE,
       PURCHASERNAMEUNI,
       PURCHASERNAMEENG
       from GOODSPURCHASER where PURCHASERCATEGORYCODE=1";
   }
   else
   {
       $query = "select PURCHASERCODE,
       PURCHASERNAMEUNI,
       PURCHASERNAMEENG
       from GOODSPURCHASER where (upper(PURCHASERNAMEENG) like upper('%".$searchTerm."%')
       or PURCHASERNAMEUNI like '%".$searchTerm."%'
       or to_char(PURCHASERCODE) like '".$searchTerm."') and PURCHASERCATEGORYCODE=1";
   }
   $result = oci_parse($connection, $query); $r = oci_execute($result);
   $r = oci_execute($result);
   while ($row = oci_fetch_array($result,OCI_ASSOC+OCI_RETURN_NULLS))
   {
       $id = $row['PURCHASERCODE'];
       if ($_SESSION['lng'] == "English")
       {
           $name = $row['PURCHASERNAMEENG'];
       }
       else
       {
           $name = $row['PURCHASERNAMEUNI'];
       }
       $data[] = array( 
           'id' => $id
           ,'label' => $name
           ,'value' => $name
           );
   }
   //return json data
   echo json_encode($data);
?>

