<?php
//This is generated by Nigade Software Technologies (opc) Private Limited 29/05/2021 10:50:45 am for PHP
require_once("../swappbase/formbase.php");
class customer extends swappform
{
    Public $customercode;
    Public $customernameeng;
    Public $customernameuni;
    Public $customercategorycode;
    Public $customercategorycodetextcombo;
    Public $refcode;
    Public $uptodate;
    public function __construct(&$connection)
    {
     		 parent::__construct($connection);
         $this->customercode='';
         $this->customercodetextcombo='';
         $this->customernameeng='';
         $this->customernameengtextcombo='';
         $this->customernameuni='';
         $this->customernameunitextcombo='';
         $this->customercategorycode='';
         $this->customercategorycodetextcombo='';
         $this->refcode='';
         $this->refcodetextcombo='';
         $this->uptodate='';
         $this->uptodatetextcombo='';
	   }
    public function entryvalidation()
    {
    		$this->start_validation();
        $this->checkrequired($this->customernameeng,'Customer Name (English)','ग्राहक कोड (इंग्रजी)');
        $this->checkrequired($this->customernameuni,'Customer Name (Marathi)','ग्राहक कोड (मराठी)');
        $this->checkrequired($this->customercategorycode,'Customer Category Code','ग्राहक  प्रकार कोड');
        $this->checkrequired($this->refcode,'Reference Code','संदर्भ कोड');
        //$this->checkrequired($this->uptodate,'Uptodate','‌दिनांक पर्यंत');
        $this->end_validation();
        return $this->invalidid;
	  }
    private function datavalidation()
    {
        $this->start_validation();
    		$this->invalidid=0;
    		$this->invalidmessagetext='Validated';
    		$this->end_validation();
    		return $this->invalidid;
    }
    public function insert()
    {
        $this->dataoperationmode = operationmode::Insert;
	    if ($this->entryvalidation() <> 0)
        {
            return 0;
            exit;
        }
        elseif ($this->datavalidation() <> 0)
        {
            return 0;
            exit;
        }
	    if ($this->customercode == '')
        {
            $query = "select nvl(max(customercode),0)+1 as customercode from customer";
            $result = oci_parse($this->connection, $query);
            $r = oci_execute($result);
            $row = oci_fetch_array($result,OCI_ASSOC+OCI_RETURN_NULLS);
            $this->customercode = $row["CUSTOMERCODE"];
        }
        if ($this->uptodate!='')
        {
            $this->uptodate = DateTime::createFromFormat('d/m/Y',$this->uptodate)->format('d-M-Y');
        }
        $query = "
            insert into customer(
            customercode
            ,customernameeng
            ,customernameuni
            ,customercategorycode
            ,refcode
            ,uptodate
	        )
	        values (
            ".$this->invl($this->customercode,true)."
            ,".$this->invl($this->customernameeng,false)."
            ,".$this->invl($this->customernameuni,false)."
            ,".$this->invl($this->customercategorycode,true,true)."
            ,".$this->invl($this->refcode,true)."
            ,".$this->invl($this->uptodate,false)."
            )";
        $result = oci_parse($this->connection, $query);
        if (oci_execute($result,OCI_NO_AUTO_COMMIT))
        {
            return 1;
            exit;
        }
        else
        {
            return 0;
            exit;
        }
    }
    public function display()
	  {
		    $this->dataoperationmode = operationmode::Select;
		    $cond='';
		    if ($this->customercode!='' and $this->customercode!=0)
		    {
			      if ($cond=='')
			      {
				        $cond="t.customercode = ".$this->customercode;
			       }
			       else
			       {
				         $cond=$cond." and t.customercode = ".$this->customercode;
			       }
		    }
		    if ($this->customernameeng!='')
		    {
			      if ($cond=='')
			      {
				        $cond="t.customernameeng like '%".$this->customernameeng."%'";
			       }
			       else
			       {
				         $cond=$cond." and t.customernameeng like '%".$this->customernameeng."%'";
			       }
		    }
		    if ($this->customernameuni!='')
		    {
			      if ($cond=='')
			      {
				        $cond="t.customernameuni like '%".$this->customernameuni."%'";
			       }
			       else
			       {
				         $cond=$cond." and t.customernameuni like '%".$this->customernameuni."%'";
			       }
		    }
		    if ($this->customercategorycode!='' and $this->customercategorycode!=0)
		    {
			      if ($cond=='')
			      {
				        $cond="t.customercategorycode = ".$this->customercategorycode;
			       }
			       else
			       {
				         $cond=$cond." and t.customercategorycode = ".$this->customercategorycode;
			       }
		    }
		    if ($this->refcode!='' and $this->refcode!=0)
		    {
			      if ($cond=='')
			      {
				        $cond="t.refcode = ".$this->refcode;
			       }
			       else
			       {
				         $cond=$cond." and t.refcode = ".$this->refcode;
			       }
		    }
		    if ($this->uptodate!='')
		    {
			      $this->uptodate = DateTime::createFromFormat('d/m/Y',$this->uptodate)->format('d-M-Y');
			      if ($cond=='')
			      {
				        $cond="t.uptodate = '".$this->uptodate."'";
			       }
			       else
			       {
				         $cond=$cond." and t.uptodate = '".$this->uptodate."'";
			       }
		    }
        if ($cond!='')
		    {
		        $query = "select t.* from customer t where ".$cond." order by customercode";
			      $result = oci_parse($this->connection, $query);
            $r = oci_execute($result);
			      return $result;
		     }
		     else
		     {
		         $query = "select t.* from customer t order by customercode";
			       $result = oci_parse($this->connection, $query);
             $r = oci_execute($result);
			       return $result;
		     }
	  }
    public function update()
    {
        $this->dataoperationmode = operationmode::Update;
        if ($this->entryvalidation() <> 0)
        {
            return 0;
            exit;
        }
        elseif ($this->datavalidation() <> 0)
        {
            return 0;
            exit;
        }
        if ($row['UPTODATE']!='')
        $this->uptodate = DateTime::createFromFormat('d/m/Y',$this->uptodate)->format('d-M-Y');
        $query = "
        update customer set 
        customernameeng =".$this->invl($this->customernameeng,false)."
        ,customernameuni =".$this->invl($this->customernameuni,false)."
        ,customercategorycode = ".$this->invl($this->customercategorycode,true,true)."
        ,refcode = ".$this->invl($this->refcode,true,true)."
        ,uptodate =".$this->invl($this->uptodate,false)."
        where 
        customercode = ".$this->invl($this->customercode,true)."
        ";
        $result = oci_parse($this->connection, $query);
        if (oci_execute($result,OCI_NO_AUTO_COMMIT))
        {
            return 1;
            exit;
        }
            else
        {
            return 0;
            exit;
        }
    }
    public function delete()
    {
        $this->dataoperationmode = operationmode::Delete;
        if ($this->entryvalidation() <> 0)
        {
            return 0;
            exit;
        }
        elseif ($this->datavalidation() <> 0)
        {
            return 0;
            exit;
        }
        $this->uptodate = DateTime::createFromFormat('d/m/Y',$this->uptodate)->format('d-M-Y');
        $query = "
        delete from customer
        where 
        customercode ='".$this->invl($this->customercode,false)."'
        ";
        $result = oci_parse($this->connection, $query);
        if (oci_execute($result,OCI_NO_AUTO_COMMIT))
        {
             return 1;
             exit;
        }
        else
        {
            return 0;
            exit;
        }
    }
    public function fetch()
    {
        $this->dataoperationmode = operationmode::Select;
        $query = "select 
        customercode
        ,customernameeng
        ,customernameuni
        ,customercategorycode
        ,refcode
        ,uptodate
        from customer where 
        customercode = ".$this->invl($this->customercode,true)."
        ";
        $result = oci_parse($this->connection, $query);
        $r = oci_execute($result);
        if ($row = oci_fetch_array($result,OCI_ASSOC+OCI_RETURN_NULLS))
        {
                $this->customercode = $row['CUSTOMERCODE'];
                $this->customernameeng = $row['CUSTOMERNAMEENG'];
                $this->customernameuni = $row['CUSTOMERNAMEUNI'];
                $this->customercategorycode = $row['CUSTOMERCATEGORYCODE'];
                $this->refcode = $row['REFCODE'];
                if ($row['UPTODATE']!='')
                $this->uptodate = DateTime::createFromFormat('d-M-y',$row['UPTODATE'])->format('d/m/Y');
                $this->customercategorycodetextcombo = $this->textcomboname($this->connection,$table='CUSTOMERCATEGORY',$datafield='CUSTOMERCATEGORYCODE',$datafieldvalue=$row['CUSTOMERCATEGORYCODE'],$engfield='CUSTOMERCATEGORYNAMEENG',$unicodefield='CUSTOMERCATEGORYNAMEUNI');
                $this->found=true;
                return true;
        }
        else
        {
        return false;
        }
    }
}
?>

