<?php
    //This is generated by Swapp Software Application on 16/11/2018 08:48:59 PM for PHP
    require("../info/phpgetloginview.php");
    include("../info/ncryptdcrypt.php");
    require("../info/routine.php");
    include_once("../ip_model/voucherdetail_db_oracle.php");
    include_once("../ip_model/voucherheader_db_oracle.php");
    $connection=swapp_connection();
    $voucherdetail1 = new voucherdetail($connection);
    $voucherdetail1->transactionnumber = $_POST["transactionnumber"];
    $voucherdetail1->detailserialnumber = $_POST["detailserialnumber"];
    $voucherdetail1->accountcode = $_POST["accountcode"];
    $voucherdetail1->subledgercode = $_POST["subledgercode"];
    $voucherdetail1->credit = $_POST["credit"];
    $voucherdetail1->debit = $_POST["debit"];
    $voucherdetail1->costcentrecode = $_POST["costcentrecode"];
    $flag_de = fnDecrypt($_GET['flag']);
    $voucherheader1 = new voucherheader($connection);
    $voucherheader1->transactionnumber = $voucherdetail1->transactionnumber;
    $voucherheader1->fetch();
    $transactionnumber_en = fnEncrypt($voucherdetail1->transactionnumber);
    $vouchersubtypecode_en = fnEncrypt($voucherheader1->vouchersubtypecode);
  switch ($_POST['btn'])
  {
    case 'Add':
      $ret = $voucherdetail1->insert();
      if ($ret==1)
      {
            if (in_array($voucherheader1->vouchersubtypecode,array(1,4,7)))
            {
                if (abs($voucherdetail1->updatecashdetail())==1)
                {
                    if ($voucherdetail1->updateheader()==1)
                    {
                        oci_commit($connection);
                        echo '<span class="w3-container" style="background-color:#0a0;color:#ff8;text-align:left;">Voucher Detail is added successfully</span></br>';
                        header("Location: ../ip_view/voucherheader.php?vouchersubtypecode='.$vouchersubtypecode_en.'&transactionnumber='.$transactionnumber_en.'");
                    }
                    else
                    {
                        oci_rollback($connection);
                        echo '<span style="background-color:#f44;color:#ff8;text-align:left;">'.$voucherdetail1->Get_invalidmessagetext().'</span></br>';
                        echo '<button onclick="history.go(-1);">Back </button>';
                    }
                }
            }
            else
            {
                if ($voucherdetail1->updateheader()==1)
                {
                    oci_commit($connection);
                    echo '<span class="w3-container" style="background-color:#0a0;color:#ff8;text-align:left;">Voucher Detail is added successfully</span></br>';
                    header("Location: ../ip_view/voucherheader.php?vouchersubtypecode='.$vouchersubtypecode_en.'&transactionnumber='.$transactionnumber_en.'");
                }
                else
                {
                    oci_rollback($connection);
                    echo '<span style="background-color:#f44;color:#ff8;text-align:left;">'.$voucherdetail1->Get_invalidmessagetext().'</span></br>';
                    echo '<button onclick="history.go(-1);">Back </button>';
                }
            }
      }
      else
      {
            oci_rollback($connection);
            echo '<span style="background-color:#f44;color:#ff8;text-align:left;">'.$voucherdetail1->Get_invalidmessagetext().'</span></br>';
            echo '<button onclick="history.go(-1);">Back </button>';
      }
      break;
    case 'Change':
      $voucherdetail1->transactionnumber = $_POST["transactionnumber"];
      $voucherdetail1->detailserialnumber = $_POST["detailserialnumber"];
      $ret = $voucherdetail1->update();
      if ($ret==1)
      {
            if (in_array($voucherheader1->vouchersubtypecode,array(1,4,7)))
            {
                if (abs($voucherdetail1->updatecashdetail())==1)
                {
                    if ($voucherdetail1->updateheader()==1)
                    {
                        oci_commit($connection);
                        echo '<span class="w3-container" style="background-color:#0a0;color:#ff8;text-align:left;">Voucher Detail is Updated successfully</span></br>';
                        header("Location: ../ip_view/voucherheader.php?vouchersubtypecode='.$vouchersubtypecode_en.'&transactionnumber='.$transactionnumber_en.'");
                    }
                    else
                    {
                        oci_rollback($connection);
                        echo '<span style="background-color:#f44;color:#ff8;text-align:left;">'.$voucherdetail1->Get_invalidmessagetext().'</span></br>';
                        echo '<button onclick="history.go(-1);">Back </button>';
                    }
                }
                else
                {
                    oci_rollback($connection);
                    echo '<span style="background-color:#f44;color:#ff8;text-align:left;">'.$voucherdetail1->Get_invalidmessagetext().'</span></br>';
                    echo '<button onclick="history.go(-1);">Back </button>';
                }
            }
            else
            {
                if ($voucherdetail1->updateheader()==1)
                {
                    oci_commit($connection);
                    echo '<span class="w3-container" style="background-color:#0a0;color:#ff8;text-align:left;">Voucher Detail is Updated successfully</span></br>';
                    header("Location: ../ip_view/voucherheader.php?vouchersubtypecode='.$vouchersubtypecode_en.'&transactionnumber='.$transactionnumber_en.'");
                }
                else
                {
                    oci_rollback($connection);
                    echo '<span style="background-color:#f44;color:#ff8;text-align:left;">'.$voucherdetail1->Get_invalidmessagetext().'</span></br>';
                    echo '<button onclick="history.go(-1);">Back </button>';
                }
            }
      }
      else
      {
        oci_rollback($connection);
        echo '<span style="background-color:#f44;color:#ff8;text-align:left;">'.$voucherdetail1->Get_invalidmessagetext().'</span></br>';
        echo '<button onclick="history.go(-1);">Back </button>';
      }
        break;
	case 'Display':
      $voucherdetail1->transactionnumber = $_POST["transactionnumber"];
      $voucherdetail1->detailserialnumber = $_POST["detailserialnumber"];
      include("../mis/list.php");
      echo '<nav "w3-container">';
      echo '    <ul class="navbar">';
      echo '    <li><a class="navbar" href="../mis/entitymenu.php">Entity Menu</a><br/>';
      $flag_en = fnEncrypt('Query');
      echo '    <li><a class="navbar" href="../ip_view/voucherdetail.php?vouchersubtypecode='.$vouchersubtypecode_en.'&transactionnumber='.$transactionnumber_en.'">New Voucher Detail</a>';
      echo '    <li><a class="navbar" href="../ip_view/voucherdetail.php?vouchersubtypecode='.$vouchersubtypecode_en.'&transactionnumber='.$transactionnumber_en.'&flag='.$flag_en.'">Find Voucher Detail</a>';
      echo '<li><a style="color:#f48" class="navbar" href="../../../../../sqlproc/logout.php">Log Out</a><br/>';
      echo '    </ul>';
      echo '  </nav>';
      echo '<section>';
      echo '<table border="0" >';
      echo '<tr>';
      echo '<td><label for="" class="thick">List of Voucher Detail</label></td>';
      echo '</tr>';
			$result1 = $voucherdetail1->display();
			if ($voucherdetail1->Get_invalidid()==0)
			{
        $flag_en = fnEncrypt('Display');
				while ($row1 = oci_fetch_array($result1,OCI_ASSOC+OCI_RETURN_NULLS))
				{
					if ($_SESSION['lng']=='English')
					{
            echo '<tr>';
						echo '<td><a href="../ip_view/voucherdetail.php?transactionnumber='.fnEncrypt($row1['TRANSACTIONNUMBER']).'&detailserialnumber='.fnEncrypt($row1['DETAILSERIALNUMBER']).'&flag='.$flag_en.'">'.$row1['ACCOUNTCODE'].' '.$row1['SUBLEDGERCODE'].'</td>';
            echo '</tr>';
					}
					else
					{
            echo '<tr>';
						echo '<td><a href="../ip_view/voucherdetail.php?transactionnumber='.fnEncrypt($row1['TRANSACTIONNUMBER']).'&detailserialnumber='.fnEncrypt($row1['DETAILSERIALNUMBER']).'&flag='.$flag_en.'">'.$row1['ACCOUNTCODE'].'</td>';
            echo '</tr>';
					}
				}	
			}
			else
			{
				echo '<span style="background-color:#f44;color:#ff8;text-align:left;">'.$voucherdetail1->Get_invalidmessagetext().'</span></br>';
			}
			break;
		case 'Delete':
            $voucherdetail1->transactionnumber = $_POST["transactionnumber"];
            $voucherdetail1->detailserialnumber = $_POST["detailserialnumber"];
			$ret = $voucherdetail1->delete();
			if ($ret == 1)
			{
                if (in_array($voucherheader1->vouchersubtypecode,array(1,4,7)))
                {    
                    if (abs($voucherdetail1->updatecashdetail())==1)
                    {
                        if ($voucherdetail1->updateheader()==1)
                        {
                            oci_commit($connection);
                            echo '<span class="w3-container" style="background-color:#0a0;color:#ff8;text-align:left;">Voucher Detail is Deleted successfully</span></br>';
                            header("Location: ../ip_view/voucherheader.php?vouchersubtypecode='.$vouchersubtypecode_en.'&transactionnumber='.$transactionnumber_en.'");
                        }
                        else
                        {
                            oci_rollback($connection);
                            echo '<span style="background-color:#f44;color:#ff8;text-align:left;">'.$voucherdetail1->Get_invalidmessagetext().'</span></br>';
                            echo '<button onclick="history.go(-1);">Back </button>';
                        }
                    }
                    else
                    {
                        oci_rollback($connection);
                        echo '<span style="background-color:#f44;color:#ff8;text-align:left;">'.$voucherdetail1->Get_invalidmessagetext().'</span></br>';
                        echo '<button onclick="history.go(-1);">Back </button>';
                    }
                }
                else
                {
                    if ($voucherdetail1->updateheader()==1)
                    {
                        oci_commit($connection);
                        echo '<span class="w3-container" style="background-color:#0a0;color:#ff8;text-align:left;">Voucher Detail is Updated successfully</span></br>';
                        header("Location: ../ip_view/voucherheader.php?vouchersubtypecode='.$vouchersubtypecode_en.'&transactionnumber='.$transactionnumber_en.'");
                    }
                    else
                    {
                        oci_rollback($connection);
                        echo '<span style="background-color:#f44;color:#ff8;text-align:left;">'.$voucherdetail1->Get_invalidmessagetext().'</span></br>';
                        echo '<button onclick="history.go(-1);">Back </button>';
                    }
                }
			}
			else
			{
				oci_rollback($connection);
				echo '<span style="background-color:#f44;color:#ff8;text-align:left;">'.$voucherdetail1->Get_invalidmessagetext().'</span></br>';
				echo '<a href="../ip_view/voucherdetail.php">Find voucherdetail</a></br>';
			}
			break;
		default:
			echo 'Communication Error';
			break;
	}

