<?php
    //This is generated by Swapp Software Application on 19/03/2019 06:42:18 PM for PHP
    require("../info/phpgetloginview.php");
    include("../info/ncryptdcrypt.php");
    require("../info/routine.php");
    include("../ip_model/salememodetail_db_oracle.php");
    $connection=swapp_connection();
    $salememodetail1 = new salememodetail($connection);
    $salememodetail1->transactionnumber = $_POST["transactionnumber"];
    $salememodetail1->serialnumber = $_POST["serialnumber"];
    $salememodetail1->finishedgoodscode = $_POST["finishedgoodscode"];
    $salememodetail1->productionyearcode = $_POST["productionyearcode"];
    $salememodetail1->salequantity = $_POST["salequantity"];
    $salememodetail1->salerate = $_POST["salerate"];
    $salememodetail1->transportationrate = $_POST["transportationrate"];
    $salememodetail1->amount = $_POST["amount"];
    $salememodetail1->transportationamount = $_POST["transportationamount"];
    $salememodetail1->cgstrate = $_POST["cgstrate"];
    $salememodetail1->sgstrate = $_POST["sgstrate"];
    $salememodetail1->igstrate = $_POST["igstrate"];
    $salememodetail1->ugstrate = $_POST["ugstrate"];
    $salememodetail1->vatrate = $_POST["vatrate"];
    $salememodetail1->cgstamount = $_POST["cgstamount"];
    $salememodetail1->sgstamount = $_POST["sgstamount"];
    $salememodetail1->igstamount = $_POST["igstamount"];
    $salememodetail1->ugstamount = $_POST["ugstamount"];
    $salememodetail1->vatamount = $_POST["vatamount"];
    $salememodetail1->totaltaxamount = $_POST["totaltaxamount"];
    $salememodetail1->grossamount = $_POST["grossamount"];
    $goodscategorycode=$_POST["goodscategorycode"];
    $salecategorycode=$_POST["salecategorycode"];
    $salememodetail1->tendertransactionnumber = $_POST["tendertransactionnumber"];
    $salememodetail1->ordertransactionnumber = $_POST["ordertransactionnumber"];
    $salememodetail1->balancequantity = $_POST["balancequantity"];
    $flag_de = fnDecrypt($_GET['flag']);
    $transactionnumber_en = fnEncrypt($salememodetail1->transactionnumber);
    $goodscategorycode_en = fnEncrypt($goodscategorycode);
    $salecategorycode_en = fnEncrypt($salecategorycode);
  switch ($_POST['btn'])
  {
    case 'Add':
      $ret = $salememodetail1->insert();
      if ($ret==1)
      {
        oci_commit($connection);
        
        echo '<span class="w3-container" style="background-color:#0a0;color:#ff8;text-align:left;">Sale Detail is added successfully</span></br>';
        //echo '<a href="../ip_view/salememodetail.php">New Sale Detail</a></br>';
        header("Location: ../ip_view/salememoheader.php?goodscategorycode='.$goodscategorycode_en.'&salecategorycode='.$salecategorycode_en.'&transactionnumber='.$transactionnumber_en.'&flag='.$flag_en.'");
      }
      else
      {
        oci_rollback($connection);
        echo '<span style="background-color:#f44;color:#ff8;text-align:left;">'.$salememodetail1->Get_invalidmessagetext().'</span></br>';
        echo '<button onclick="history.go(-1);">Back </button>';
      }
      break;
    case 'Change':
      $salememodetail1->transactionnumber = $_POST["transactionnumber"];
      $salememodetail1->serialnumber = $_POST["serialnumber"];
      $ret = $salememodetail1->update();
      if ($ret==1)
      {
        oci_commit($connection);
        $flag_en = fnEncrypt('Query');
        echo '<span class="w3-container" style="background-color:#0a0;color:#ff8;text-align:left;">Sale Detail is Updated successfully</span></br>';  
        //echo '<a href="../ip_view/salememodetail.php?flag='.$flag_en.'">Find Sale Detail</a></br>';
        header("Location: ../ip_view/salememoheader.php?goodscategorycode='.$goodscategorycode_en.'&salecategorycode='.$salecategorycode_en.'&transactionnumber='.$transactionnumber_en.'&flag='.$flag_en.'");
      }
      else
      {
        oci_rollback($connection);
        echo '<span style="background-color:#f44;color:#ff8;text-align:left;">'.$salememodetail1->Get_invalidmessagetext().'</span></br>';
        echo '<button onclick="history.go(-1);">Back </button>';
			}
			break;
		case 'Display':
      $salememodetail1->transactionnumber = $_POST["transactionnumber"];
      $salememodetail1->serialnumber = $_POST["serialnumber"];
      include("../mis/list.php");
      echo '<nav "w3-container">';
      echo '    <ul class="navbar">';
      echo '    <li><a class="navbar" href="../mis/entitymenu.php">Entity Menu</a><br/>';
      $flag_en = fnEncrypt('Query');
      echo '    <li><a class="navbar" href="../ip_view/salememodetail.php">New Sale Detail</a>';
      echo '    <li><a class="navbar" href="../ip_view/salememodetail.php?flag='.$flag_en.'">Find Sale Detail</a>';
      echo '<li><a style="color:#f48" class="navbar" href="../../../../../sqlproc/logout.php">Log Out</a><br/>';
      echo '    </ul>';
      echo '  </nav>';
      echo '<section>';
      echo '<table border="0" >';
      echo '<tr>';
      echo '<td><label for="" class="thick">List of Sale Detail</label></td>';
      echo '</tr>';
			$result1 = $salememodetail1->display();
			if ($salememodetail1->Get_invalidid()==0)
			{
        $flag_en = fnEncrypt('Display');
				while ($row1 = oci_fetch_array($result1,OCI_ASSOC+OCI_RETURN_NULLS))
				{
					if ($_SESSION['lng']=='English')
					{
            echo '<tr>';
						echo '<td><a href="../ip_view/salememodetail.php?transactionnumber='.fnEncrypt($row1['TRANSACTIONNUMBER']).'&serialnumber='.fnEncrypt($row1['SERIALNUMBER']).'&flag='.$flag_en.'">'.$row1['finishedgoodscode'].'</td>';
            echo '</tr>';
					}
					else
					{
            echo '<tr>';
						echo '<td><a href="../ip_view/salememodetail.php?transactionnumber='.fnEncrypt($row1['TRANSACTIONNUMBER']).'&serialnumber='.fnEncrypt($row1['SERIALNUMBER']).'&flag='.$flag_en.'">'.$row1['finishedgoodscode'].'</td>';
            echo '</tr>';
					}
				}	
			}
			else
			{
				echo '<span style="background-color:#f44;color:#ff8;text-align:left;">'.$salememodetail1->Get_invalidmessagetext().'</span></br>';
        echo '<button onclick="history.go(-1);">Back </button>';
			}
			break;
		case 'Delete':
      $salememodetail1->transactionnumber = $_POST["transactionnumber"];
      $salememodetail1->serialnumber = $_POST["serialnumber"];
			$ret = $salememodetail1->delete();
			if ($ret == 1)
			{
				oci_commit($connection);
        $flag_en = fnEncrypt('Query');
				echo '<span class="w3-container" style="background-color:#0a0;color:#ff8;text-align:left;">Sale Detail is Deleted Successfully</span></br>';
				//echo '<a href="../ip_view/salememodetail.php?flag='.$flag_en.'">Find Sale Detail</a></br>';
        header("Location: ../ip_view/salememoheader.php?goodscategorycode='.$goodscategorycode_en.'&salecategorycode='.$salecategorycode_en.'&transactionnumber='.$transactionnumber_en.'&flag='.$flag_en.'");
			}
			else
			{
				oci_rollback($connection);
				echo '<span style="background-color:#f44;color:#ff8;text-align:left;">'.$salememodetail1->Get_invalidmessagetext().'</span></br>';
				echo '<a href="../ip_view/salememodetail.php">Find salememodetail</a></br>';
        echo '<button onclick="history.go(-1);">Back </button>';
			}
			break;
		default:
			echo 'Communication Error';
      echo '<button onclick="history.go(-1);">Back </button>';
			break;
	}