<?php
    //This is generated by Swapp Software Application on 25/05/2021 05:14:06 pm for PHP
    require_once("../info/phpsqlajax_dbinfo.php");
    require_once("../info/phpgetloginview.php");
    require_once("../info/routine.php");
    $connection =swapp_connection();
    $searchTerm = $_GET['term'];
    if (preg_match('/^[0-9]*$/', $searchTerm))
    {
    }
    elseif (strlen($searchTerm)<3 and $searchTerm != '**')
    {
        exit;
    }
   if ($searchTerm == '**')
   {
       $query = "select PERIODCODE,
       PERIONAMEUNI,
       PERIONAMEENG
       from PERIOD order by PERIODCODE";
   }
   else
   {
       $query = "select PERIODCODE,
       PERIONAMEUNI,
       PERIONAMEENG
       from PERIOD where (upper(PERIONAMEENG) like upper('%".$searchTerm."%')
       or PERIONAMEUNI like '%".$searchTerm."%'
       or to_char(PERIODCODE) like '".$searchTerm."') order by PERIODCODE";
   }
   $result = oci_parse($connection, $query); $r = oci_execute($result);
   $r = oci_execute($result);
   while ($row = oci_fetch_array($result,OCI_ASSOC+OCI_RETURN_NULLS))
   {
       $id = $row['PERIODCODE'];
       if ($_SESSION['lng'] == "English")
       {
           $name = $row['PERIONAMEENG'];
       }
       else
       {
           $name = $row['PERIONAMEUNI'];
       }
       $data[] = array( 
           'id' => $id
           ,'label' => $name
           ,'value' => $name
           );
   }
   //return json data
   echo json_encode($data);
?>

